- java/docs/api/class-accessibility.mdx
- java/docs/api/class-browser.mdx
- java/docs/api/class-browsercontext.mdx
- java/docs/api/class-browsertype.mdx
- java/docs/api/class-elementhandle.mdx
- java/docs/api/class-filechooser.mdx
- java/docs/api/class-frame.mdx
- java/docs/api/class-keyboard.mdx
- java/docs/api/class-mouse.mdx
- java/docs/api/class-page.mdx
- java/docs/api/class-route.mdx
- java/docs/api/class-selectors.mdx
- java/docs/api/class-websocket.mdx
- java/docs/api/class-worker.mdx
- nodejs/docs/api/class-elementhandle.mdx
- nodejs/docs/api/class-filechooser.mdx
- nodejs/docs/api/class-frame.mdx
- nodejs/docs/api/class-page.mdx
- python/docs/api/class-elementhandle.mdx
- python/docs/api/class-filechooser.mdx
- python/docs/api/class-frame.mdx
- python/docs/api/class-page.mdx
- src/generator.js
* Custom type names are properly replaced in the template params: List<Cookie> instead of List<Map> etc.
* Fix type names for nested options classes such as geolocation (it's now Geolocation instead of Map)
> fix: type names for collections such as List<FilePayload>

- java/docusaurus.config.js
We don't wanna have any versions before going stable.
> fix: remove versions dropdown for java

- java/docusaurus.config.js
- python/docusaurus.config.js
Fixes syntax highlighting for python & java docs @pavelfeldman @mxschmitt
> feat: syntax highlighting for python & java docs

- .github/workflows/deploy.yml
Since its now the same repo, it should work with the access token provided by GitHub automatically.
This won't require the custom PAT anymore -> won't create these notifications too.
> devops: remove pushing over Arjuns PAT

- src/theme/Heading/index.js
- src/theme/Heading/styles.css
- src/theme/Heading/styles.module.css
Fixes #129
Before: After clicking on the anchor link it ended up in `http://localhost:3000/docs/api/class-page?_highlight=screenshot#pagescreenshotoptions`
After: After clicking on the anchor link it ends up now in `http://localhost:3000/docs/api/class-page#pagescreenshotoptions`
For further reference, see here:
- `npx docusaurus swizzle @docusaurus/theme-classic Heading --danger`
- https://docusaurus.io/docs/2.0.0-alpha.71/using-themes#swizzling-theme-components
> chore: strip out the search parameter in shared link

- dotnet/docusaurus.config.js
- java/docusaurus.config.js
- nodejs/docusaurus.config.js
- python/docusaurus.config.js
Fixes #403 
Previously when searching for results on search bar shows too much results that some results chip at the end of screen also you cannot scroll. 
**This situation gets worse if you are reading docs from mobile as you are totally stuck in search results.**
See this 👇
This PR sets the Docusaurus search `searchResultLimits` to 8 so that it can fit and gives a great experience for developers reading docs.
##How did you test this change
By building the docs and serving them on `localhost:3000` and I pretty satisfied with the results.
After Results
> Fix for search showing too much results

- .github/workflows/azure-static-web-apps-delightful-forest-0a29f6210.yml
This fixes that Azure Static WebApps did not pick up the right NPM version. It picked up NPM 6 instead which can't handle lock format v2.
> chore: use right version of NPM with Azure Static WebApps

- package-lock.json
- package.json
Seems there was a bug in the CSS minifier, this change should fix it and enable again the hoverable hashtags for referencing to individual properties.
changelog: https://docusaurus.io/changelog/2.0.0-beta.18
> chore: bump docusaurus to beta.18

- nodejs/sidebars.js
This PR adds the new `accessibility-testing-js.md` guide authored in https://github.com/microsoft/playwright/pull/15154 to the nodejs sidebar, per discussion in https://github.com/microsoft/playwright/issues/14112.
I verified the change locally by rolling the docs, verifying that the new page shows up in the "Next" docs, and manually reviewing its contents. This resulted in followup PRs https://github.com/microsoft/playwright/pull/15204 and https://github.com/microsoft/playwright/pull/15205 (neither of which block this one)
> docs(nodejs): add accessibility testing to js sidebar

- src/format_csharp.js
- src/format_java.js
- src/format_js.js
- src/format_python.js
- src/generate.js
When `npm run start-nodejs` was used and e.g. debug.md was changed, it generated nodejs/debug.md as intended but not python/debug.md, which required another npm run roll before pushing. This fixes it.
(Fix for Debbie)
> chore: generate all languages on watch

- .github/workflows/deploy.yml
Tested on my private fork, seems to work fine.
See [here](https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta) about the announcement.
> devops: migrate deployment to official GitHub Action

- nodejs/sidebars.js
Puppeteer migration guide was merged to Playwright repo. This PR adds the migration guide to the sidebar
I believe `Playwright Service` will roll the doc from the main repo
> docs: add puppeteer migration to nodejs sidebar

- dotnet/docusaurus.config.js
- java/docusaurus.config.js
- nodejs/docusaurus.config.js
- python/docusaurus.config.js
Add image for meta tags. This will populate the share image for social networks such as Twitter, Facebook or LinkedIn and create a nice preview card.
Result for Twitter will be as below
I tried my best to fit Playwright's website style, fonts and used the SVG logo. Source PSD file is available here : https://drive.google.com/file/d/1XyV2UzzoslFWYDRkSM1p0tYMmzQckSiJ/view?usp=sharing
> Add default image for meta tags

- community/0-welcome.mdx
- community/ambassadors.mdx
- dotnet/docusaurus.config.js
- dotnet/sidebarCommunity.js
- java/docusaurus.config.js
- java/sidebarCommunity.js
- nodejs/docusaurus.config.js
- nodejs/sidebarCommunity.js
- python/docusaurus.config.js
- python/sidebarCommunity.js
Hi there! When clicking "Join our community Slack Channel" on the Community page, I noticed it redirected me to a Discord Server invite. This pull request updates all references to Slack by replacing it with Discord. Notice how the new link uses a slash, rather than a dash.
Thank you for everything you've been doing, Playwright is truly amazing!
> chore: Update Slack community to Discord community

- dotnet/docs/api/class-accessibility.mdx
- dotnet/docs/api/class-frame.mdx
- dotnet/docs/api/class-locator.mdx
- dotnet/docs/api/class-page.mdx
- java/docs/api/class-frame.mdx
- java/docs/api/class-locator.mdx
- java/docs/api/class-page.mdx
- nodejs/docs/api/class-accessibility.mdx
- nodejs/docs/api/class-androiddevice.mdx
- nodejs/docs/api/class-browser.mdx
- nodejs/docs/api/class-browsercontext.mdx
- nodejs/docs/api/class-browsertype.mdx
- nodejs/docs/api/class-frame.mdx
- nodejs/docs/api/class-locator.mdx
- nodejs/docs/api/class-page.mdx
- nodejs/docs/api/class-test.mdx
- nodejs/docs/api/class-testconfig.mdx
- python/docs/api/class-accessibility.mdx
- python/docs/api/class-frame.mdx
- python/docs/api/class-locator.mdx
- python/docs/api/class-page.mdx
- src/generator.js
Looks now like that:
Before we did not say anymore that `Page.isVisible.timeout` is deprecated, the red stuff is new.
Drive-by: Caution -> Deprecated / Discouraged.
Fixes https://github.com/microsoft/playwright/issues/20033
> chore: show property discouraged and deprecated warnings

- src/data/conference-videos.tsx
they uploaded a new version of the talk so this is the updated youtube link
> docs: update video youtube link

- common/links-csharp.md
- common/links-java.md
- common/links-js.md
- common/links-python.md
fix #1055
Probably this requires changing `common/links-*.md` files that I cannot find the main `microsoft/playwright` repository. Let me know if I can fix it on the main repository. Thanks.
> fix: update broken Dockefile.jammy links

- .github/workflows/azure-static-web-apps-delightful-forest-0a29f6210.yml
- .github/workflows/create_release.yml
- .github/workflows/deploy.yml
- .github/workflows/roll.yml
- package.json
We require Node.js 18 now since we use fetch during rolling. Let's upgrade it everywhere.
> devops: bump Node.js versions

- src/generate.js
This prevents https://github.com/microsoft/playwright.dev/pull/1092/files#diff-97dbf4cf97d3d5b41bd6897743930f75536805c5cca49f3730eeb4e0c6296df8 from happening again.
> chore: use only stable versions for .NET latest version

- python/docs/api/class-apiresponse.mdx
- python/docs/api/class-browser.mdx
- python/docs/api/class-browsercontext.mdx
- python/docs/api/class-browsertype.mdx
- python/docs/api/class-consolemessage.mdx
- python/docs/api/class-dialog.mdx
- python/docs/api/class-download.mdx
- python/docs/api/class-filechooser.mdx
- python/docs/api/class-frame.mdx
- python/docs/api/class-framelocator.mdx
- python/docs/api/class-jshandle.mdx
- python/docs/api/class-locator.mdx
- python/docs/api/class-page.mdx
- python/docs/api/class-request.mdx
- python/docs/api/class-response.mdx
- python/docs/api/class-route.mdx
- python/docs/api/class-websocket.mdx
- python/docs/api/class-worker.mdx
- src/format_python.js
- src/generate.js
- src/generator.js
Fixes https://github.com/microsoft/playwright-python/issues/2025
> fix: detect Python methods as properties correctly

- src/pages/index.tsx
I believe this is the right repo to update the homepage.
I had a Playwright trace I wanted to open locally, and it took several clicks to get to https://trace.playwright.dev from the homepage. Now, clicking on “Trace Viewer” toward the bottom of the page will take you right to it. (I linked the other two to docs pages since they don’t appear to have dedicated websites, and I wanted all 3 to have a link)
> Add links for the “Powerful Tooling” items on the homepage

- src/format_java.js
This PR allows parsing the new `SoftAssertions` for java docs
cc: @yury-s
> fix(java): Allow parsing of SoftAssertions

- java/sidebars.js
Adding the class to the API sidebar, otherwise [setDefaultAssertionTimeout()](https://playwright.dev/java/docs/api/class-playwrightassertions#playwright-assertions-set-default-assertion-timeout) is only accessible through search.
Reference https://github.com/microsoft/playwright-java/issues/1395
> docs: add PlaywrightAssertions to the API sidebar

- dotnet/docs/api/class-locator.mdx
- java/docs/api/class-locator.mdx
- nodejs/docs/api/class-locator.mdx
- nodejs/docs/api/class-test.mdx
- python/docs/api/class-locator.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/ac9d1ec421b572d6ac23f1dd169f292a1108e102
> feat(roll): roll to ToT Playwright (roll/30-09-23)

- .github/workflows/create_release.yml
- .github/workflows/roll.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> ci: Use GITHUB_OUTPUT envvar instead of set-output command

- nodejs/docs/api/class-test.mdx
- nodejs/docs/ci-intro.mdx
- nodejs/docs/release-notes.mdx
- nodejs/docs/service-workers-experimental-network-events.mdx
- nodejs/docs/test-typescript.mdx
- src/documentation.js
- src/format_csharp.js
> fix: docs roll after csharp LocatorHandlerAsync type changes

- dotnet/sidebarCommunity.js
- java/sidebarCommunity.js
- nodejs/sidebarCommunity.js
- python/sidebarCommunity.js
- src/data/learn-videos.tsx
- src/data/video-nav.tsx
- src/pages/community/learn-videos.tsx
Add videos from VS Code course published late last year on a new section in videos called Learn Videos
> docs: Add "Learn Videos" section

- package-lock.json
- package.json
- patches/@docusaurus+theme-search-algolia+3.0.0.patch
This backports https://github.com/facebook/docusaurus/pull/9945.
Relates https://github.com/microsoft/playwright.dev/issues/1269
> fix(a11y): backport docusaurus search bar focus fix

- dotnet/docs/api/class-browsertype.mdx
- dotnet/docs/api/class-elementhandle.mdx
- dotnet/docs/api/class-frame.mdx
- dotnet/docs/api/class-locator.mdx
- dotnet/docs/api/class-page.mdx
- java/docs/api/class-browsertype.mdx
- java/docs/api/class-elementhandle.mdx
- java/docs/api/class-frame.mdx
- java/docs/api/class-locator.mdx
- java/docs/api/class-page.mdx
- nodejs/docs/api/class-androiddevice.mdx
- nodejs/docs/api/class-browser.mdx
- nodejs/docs/api/class-browsertype.mdx
- nodejs/docs/api/class-elementhandle.mdx
- nodejs/docs/api/class-frame.mdx
- nodejs/docs/api/class-locator.mdx
- nodejs/docs/api/class-page.mdx
- nodejs/docs/api/class-test.mdx
- nodejs/docs/api/class-testconfig.mdx
- python/docs/api/class-browsertype.mdx
- python/docs/api/class-elementhandle.mdx
- python/docs/api/class-frame.mdx
- python/docs/api/class-locator.mdx
- python/docs/api/class-page.mdx
- src/generator.js
`:::caution` is deprecated since v3 of Docusaurus and they also have a new way of specifying a custom [Admonitors title](https://docusaurus.io/docs/markdown-features/admonitions#specifying-title). Old one is [best-effort](https://docusaurus.io/docs/markdown-features/admonitions#specifying-title).
See https://github.com/facebook/docusaurus/pull/9308
Demo: https://delightful-forest-0a29f6210-1333.centralus.azurestaticapps.net/docs/next/api/class-browsertype#browser-type-launch
> chore: migrate :::caution to :::warning

- .azure-pipelines/guardian/SDL/.gdnsuppress
- .azure-pipelines/publish.yml
- package-lock.json
- package.json
- playwright.config.ts
- tests/a11y.spec.ts
- tests/export-to-sarif.ts
Motivation: As per Microsoft Accessibility Standards we need to setup automation for running a11y tests on our website. Starting with `/` and `/intro` for now. They don't provide a GitHub Actions integration so we need to use Azure Pipelines in order to report the results back to their platform.
> test: add a11y tests

- src/theme/NavbarItem/index.js
One idea was to hide the language from the drop-down if the page does not exist, Debbie instead prefers redirecting to /docs/intro so the user always is aware that we are compatible with 4 languages.
Closes https://github.com/microsoft/playwright/issues/30890
> chore: redirect to docs/test-runners for non-existing port guides

- community/0-welcome.mdx
- dotnet/docusaurus.config.ts
- java/docusaurus.config.ts
- nodejs/docusaurus.config.ts
- python/docusaurus.config.ts
add LinkedIn and learn module to community welcome page
improve footer to add links to linkedIn and to learn playwright module and to some videos
> community: add linked in plus improve footer

- nodejs/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/2ae2fb421c6b6ec115721a8b0a5215442e5411c3
> feat(roll): roll to ToT Playwright (roll/15-06-24)

- src/format_js.js
Fixes https://playwright.dev/docs/api/class-clock#clock-fast-forward-option-ticks
> fix: treat long in Node.js as number

- src/components/VideoCards/index.tsx
- src/data/conference-videos.tsx
- src/data/learn-videos.tsx
- src/data/release-videos.tsx
- src/data/types.ts
When release videos were specified with two versions [here](https://github.com/microsoft/playwright.dev/blob/f591850f3decde10860ba389ce71fbfd55bb438c/src/data/release-videos.tsx#L13), the anchor link wasn't generated correctly and it was yielding to [this](https://github.com/microsoft/playwright.dev/actions/runs/9954951874/job/27501690410#step:4:771) warning / user facing UX issue.
> fix: release note link for videos with two versions

- dotnet/docs/api/class-apirequestcontext.mdx
- dotnet/docs/ci-intro.mdx
- dotnet/docs/ci.mdx
- dotnet/docs/docker.mdx
- java/docs/api/class-requestoptions.mdx
- java/docs/ci-intro.mdx
- java/docs/ci.mdx
- java/docs/docker.mdx
- java/docs/intro.mdx
- java/docs/test-runners.mdx
- nodejs/docs/api/class-apirequestcontext.mdx
- nodejs/docs/ci-intro.mdx
- nodejs/docs/test-cli.mdx
- nodejs/docs/test-components.mdx
- python/docs/api/class-apirequestcontext.mdx
- python/docs/ci-intro.mdx
- python/docs/ci.mdx
- python/docs/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/f23d02a2116947369ff6206f9c73050dd36fe95c
> feat(roll): roll to ToT Playwright (roll/23-07-24)

- nodejs/docs/ci-intro.mdx
- nodejs/docs/release-notes.mdx
- nodejs/docs/test-cli.mdx
- nodejs/docs/test-fixtures.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/57c7d9e9bb4a884c6432a518043a0368bc6ef97b
> feat(roll): roll to ToT Playwright (roll/26-07-24)

- dotnet/docs/api-testing.mdx
- dotnet/docs/screenshots.mdx
- java/docs/accessibility-testing.mdx
- java/docs/api-testing.mdx
- java/docs/ci-intro.mdx
- java/docs/ci.mdx
- java/docs/docker.mdx
- java/docs/intro.mdx
- java/docs/junit.mdx
- java/docs/screenshots.mdx
- java/docs/test-runners.mdx
- nodejs/docs/api-testing.mdx
- nodejs/docs/screenshots.mdx
- python/docs/api-testing.mdx
- python/docs/screenshots.mdx
- src/markdown.js
Upstream commit: https://github.com/microsoft/playwright/commit/e8d845be64e3d989cd5a9988b66b70c4d7d3270a
> feat(roll): roll to ToT Playwright (roll/10-08-24)

- dotnet/docs/api/class-browser.mdx
- dotnet/docs/api/class-browsercontext.mdx
- dotnet/docs/api/class-page.mdx
- java/docs/api/class-browser.mdx
- java/docs/api/class-browsercontext.mdx
- java/docs/api/class-page.mdx
- nodejs/docs/api/class-browser.mdx
- nodejs/docs/api/class-browsercontext.mdx
- nodejs/docs/api/class-page.mdx
- python/docs/api/class-browser.mdx
- python/docs/api/class-browsercontext.mdx
- python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/3f085d568935b9a4422f689185f720c1206bac84
> feat(roll): roll to ToT Playwright (roll/27-08-24)

- .github/workflows/roll-next.yml
- .github/workflows/roll-stable.yml
- README.md
We are always interested in only the last release-* branch to update with our stable playwright.dev docs, hence we can automate the process of finding the correct version. This also allows us to run it scheduled, which makes it easier to keep cherry-picked docs changes in sync with the actual deployed version.
> devops: determine release update branch automatically

- dotnet/docs/ci.mdx
- dotnet/docs/docker.mdx
- dotnet/docs/release-notes.mdx
- java/docs/release-notes.mdx
- python/docs/ci.mdx
- python/docs/docker.mdx
- python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/cd4dabef8bd0c80cf91c93fd170be1aaf87cc7a9
> feat(roll): roll to ToT Playwright (roll/next-13-09-24)

- .github/workflows/azure-static-web-apps-delightful-forest-0a29f6210.yml
- .github/workflows/roll-next.yml
- .github/workflows/roll-stable.yml
drive-by: actions/github-script@v6 -> actions/github-script@v7 in order to fix a outdated Node.js warning.
> devops: fix stable docs roll workflow

- dotnet/docs/api/class-page.mdx
- dotnet/docs/api/class-tracing.mdx
- dotnet/docs/trace-viewer.mdx
- java/docs/api/class-page.mdx
- java/docs/api/class-tracing.mdx
- java/docs/ci.mdx
- java/docs/docker.mdx
- java/docs/intro.mdx
- java/docs/test-runners.mdx
- java/docs/trace-viewer-intro.mdx
- java/docs/trace-viewer.mdx
- nodejs/docs/api/class-apirequestcontext.mdx
- nodejs/docs/api/class-page.mdx
- nodejs/docs/api/class-tracing.mdx
- nodejs/docs/ci.mdx
- nodejs/docs/docker.mdx
- nodejs/docs/test-global-setup-teardown.mdx
- nodejs/docs/trace-viewer-intro.mdx
- nodejs/docs/trace-viewer.mdx
- python/docs/api/class-page.mdx
- python/docs/api/class-tracing.mdx
- python/docs/trace-viewer-intro.mdx
- python/docs/trace-viewer.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/aeb4d182f749f8185797b66f28bff6828d35b867
> feat(roll): roll to ToT Playwright (roll/next-14-09-24)

- src/generate.js
Maven seems to be unavailable [sometimes](https://github.com/microsoft/playwright.dev/actions/runs/11050137379/job/30697258827#step:6:19).
> chore: use GitHub API for Java version determination logic

- dotnet/docs/api/class-page.mdx
- java/docs/api/class-page.mdx
- nodejs/docs/api/class-androiddevice.mdx
- nodejs/docs/api/class-test.mdx
- nodejs/docs/api/class-testinfo.mdx
- src/api_parser.js
Upstream commit: https://github.com/microsoft/playwright/commit/d6f584c2d49a93c2559bc355bfd0a7389cfc46eb
> feat(roll): roll to ToT Playwright (roll/next-27-09-24)

- .github/workflows/roll-stable.yml
Before this script created a new PR every day with the latest changes. Now it will instead have a single branch name and force-push to it so we don't spam the PRs.
Looking at: https://github.com/microsoft/playwright.dev/pulls?q=is%3Apr+author%3Aplaywrightmachine+48+in%3Atitle
> devops: use same branch and override stable rolls

- dotnet/versioned_sidebars/version-stable-sidebars.json
- java/versioned_sidebars/version-stable-sidebars.json
- nodejs/versioned_sidebars/version-stable-sidebars.json
- python/versioned_docs/version-stable/ci.mdx
- python/versioned_docs/version-stable/docker.mdx
- python/versioned_sidebars/version-stable-sidebars.json
Upstream commit: https://github.com/microsoft/playwright/commit/1781bf35b3867855e8aeb922e8083e85aa0c11f3
> feat(roll): roll to 1.49 Playwright

- README.md
- package.json
Makes `roll` runnable on Windows by default. This removes the need for Bash on Windows mentions in the README.
> fix: make roll runnable by default on Windows

- dotnet/docusaurus.config.ts
- java/docusaurus.config.ts
- nodejs/docusaurus.config.ts
- package-lock.json
- package.json
- python/docusaurus.config.ts
- src/components/ProfileCard/index.tsx
- src/pages/community/conference-videos.tsx
- src/pages/community/feature-videos.tsx
- src/pages/community/learn-videos.tsx
- src/pages/community/live-streams.tsx
- src/pages/community/release-videos.tsx
- tsconfig.json
Looks like `"@docusaurus/tsconfig": "3.6.2"` introduced a regression for us in https://github.com/facebook/docusaurus/commit/5344bc105e720ff6d2b588bcd1568eb71e957148 where we had to add it manually back. Without that it ended up in:
```
src/pages/versions.tsx:22:7 - error TS2322: Type '{ children: Element; title: string; description: string; }' is not assignable to type 'IntrinsicAttributes & Props'.
Property 'title' does not exist on type 'IntrinsicAttributes & Props'.
22       title="Versions"
~~~~~
```
cc @slorber
> chore: bump docusaurus to 5.6.2

- src/generate.js
toString does not contain the stack trace.
> chore: show full watch error

- dotnet/docs/docker.mdx
- java/docs/docker.mdx
- nodejs/docs/docker.mdx
- python/docs/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/b0cec5b3518b8fa5d107068ea39612bcc1341b53
> feat(roll): roll to ToT Playwright (roll/next-13-12-24)

- nodejs/docs/api/class-teststep.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/04a3574f8054f00c34129a2b1b8acc2a58594956
> feat(roll): roll to ToT Playwright (roll/next-03-01-25)

- nodejs/docs/api/class-testconfig.mdx
- nodejs/docs/test-webserver.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/5a22475ea81380bbb432fe6a135e0047ff36ad25
> feat(roll): roll to ToT Playwright (roll/next-04-01-25)

- dotnet/docs/touch-events.mdx
- java/docs/api/class-locator.mdx
- java/docs/touch-events.mdx
- nodejs/docs/api/class-locator.mdx
- nodejs/docs/touch-events.mdx
- python/docs/api/class-locator.mdx
- python/docs/touch-events.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/ff9242104bdf2b0396924c951f7a2f6fb51551e9
> feat(roll): roll to ToT Playwright (roll/next-08-01-25)

- README.md
Multiple times I have forgotten that my change can only be found in `/next` mode, and it's likely other contributors have the same issue. Document this common issue.
> docs: Add comment explaining how Docusaurus starts up in current release mode

- nodejs/docs/api/class-locatorassertions.mdx
- nodejs/docs/api/class-test.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/372d4196d7b92868d855d3737642f008a28df808
> feat(roll): roll to ToT Playwright (roll/next-18-01-25)

- nodejs/docs/test-fixtures.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/cf90c0f122578141e8c7a961133c2c652a0285db
> feat(roll): roll to ToT Playwright (roll/next-22-01-25)

- nodejs/docs/api/class-testconfig.mdx
- nodejs/docs/release-notes.mdx
- nodejs/docs/test-webserver.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/34cb35859aef71fc35f7b8a9dbfe4009c1e64bd5
> feat(roll): roll to ToT Playwright (roll/next-23-01-25)

- nodejs/docs/api/class-testconfig.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/61d595ae48fea77af7d701fe619499d0d354b4fb
> feat(roll): roll to ToT Playwright (roll/next-28-01-25)

- dotnet/docs/api/class-browsercontext.mdx
- dotnet/docs/auth.mdx
- dotnet/docs/codegen.mdx
- java/docs/api/class-browsercontext.mdx
- java/docs/auth.mdx
- java/docs/codegen.mdx
- nodejs/docs/api/class-apirequest.mdx
- nodejs/docs/api/class-apirequestcontext.mdx
- nodejs/docs/api/class-browser.mdx
- nodejs/docs/api/class-browsercontext.mdx
- nodejs/docs/api/class-testoptions.mdx
- nodejs/docs/api/class-testproject.mdx
- nodejs/docs/api/class-teststepinfo.mdx
- nodejs/docs/auth.mdx
- nodejs/docs/codegen.mdx
- python/docs/api/class-apirequest.mdx
- python/docs/api/class-apirequestcontext.mdx
- python/docs/api/class-browser.mdx
- python/docs/api/class-browsercontext.mdx
- python/docs/auth.mdx
- python/docs/codegen.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/7aac96d780152e297bd420d3eaf29a9395a37bb6
> feat(roll): roll to ToT Playwright (roll/next-06-02-25)

- dotnet/docs/api/class-apirequestcontext.mdx
- dotnet/docs/api/class-browsercontext.mdx
- java/docs/api/class-apirequestcontext.mdx
- java/docs/api/class-browsercontext.mdx
- nodejs/docs/api/class-apirequestcontext.mdx
- nodejs/docs/api/class-browsercontext.mdx
- python/docs/api/class-apirequestcontext.mdx
- python/docs/api/class-browsercontext.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/bc8d6ce34473fdce398defcef4df8c0da0beffa9
> feat(roll): roll to ToT Playwright (roll/next-07-02-25)

- nodejs/docs/api/class-testconfig.mdx
- nodejs/docs/api/class-testinfo.mdx
- nodejs/docs/api/class-testproject.mdx
- nodejs/docs/auth.mdx
- nodejs/docs/chrome-extensions.mdx
- nodejs/docs/evaluating.mdx
- nodejs/docs/test-parameterize.mdx
- nodejs/docs/webview2.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/88c01434c64e48c1abbc6bdb14d95d3f33c48897
> feat(roll): roll to ToT Playwright (roll/next-08-02-25)

- dotnet/docs/api/class-apirequest.mdx
- dotnet/docs/api/class-browser.mdx
- dotnet/docs/api/class-browsertype.mdx
- java/docs/api/class-apirequest.mdx
- java/docs/api/class-browser.mdx
- java/docs/api/class-browsertype.mdx
- nodejs/docs/api/class-androiddevice.mdx
- nodejs/docs/api/class-apirequest.mdx
- nodejs/docs/api/class-browser.mdx
- nodejs/docs/api/class-browsertype.mdx
- nodejs/docs/api/class-testoptions.mdx
- python/docs/api/class-apirequest.mdx
- python/docs/api/class-browser.mdx
- python/docs/api/class-browsertype.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/bd74fc496461cc3c76b6d5def48580e2f535dac1
> feat(roll): roll to ToT Playwright (roll/next-12-02-25)

- nodejs/docs/api/class-testconfig.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/ea67eca5bef5f2258c3f6db19080df35ad0f6771
> feat(roll): roll to ToT Playwright (roll/next-13-02-25)

- nodejs/docs/test-components.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/0baadb513b4435cf4d89ccc2621408746a486487
> feat(roll): roll to ToT Playwright (roll/next-19-02-25)

- .azure-pipelines/publish.yml
- .github/workflows/azure-static-web-apps-delightful-forest-0a29f6210.yml
- .github/workflows/deploy.yml
- .github/workflows/roll-next.yml
- .github/workflows/roll-stable.yml
- package-lock.json
- package.json
Note: `react-loadable` was unused and Node.js 22.X is LTS.
> chore: update Node.js version to 22.x in workflows and package.json

- nodejs/docs/api/class-testconfig.mdx
- nodejs/docs/api/class-testinfo.mdx
- nodejs/docs/api/class-testproject.mdx
- nodejs/docs/auth.mdx
- nodejs/docs/chrome-extensions.mdx
- nodejs/docs/evaluating.mdx
- nodejs/docs/test-fixtures.mdx
- nodejs/docs/test-parameterize.mdx
- nodejs/docs/webview2.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/aca3fb275b5ac5828e5acdb60de43fdd20818f8c
> feat(roll): roll to ToT Playwright (roll/next-20-02-25)

- dotnet/docs/api/class-elementhandle.mdx
- dotnet/docs/api/class-locator.mdx
- dotnet/docs/api/class-page.mdx
- java/docs/api/class-elementhandle.mdx
- java/docs/api/class-locator.mdx
- java/docs/api/class-page.mdx
- nodejs/docs/api/class-elementhandle.mdx
- nodejs/docs/api/class-locator.mdx
- nodejs/docs/api/class-locatorassertions.mdx
- nodejs/docs/api/class-page.mdx
- nodejs/docs/api/class-pageassertions.mdx
- python/docs/api/class-elementhandle.mdx
- python/docs/api/class-locator.mdx
- python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/e091baad79b24952afad1df56474f9c4c35d4937
> feat(roll): roll to ToT Playwright (roll/next-22-02-25)

- dotnet/docs/api/class-locator.mdx
- dotnet/docs/api/class-touchscreen.mdx
- dotnet/docs/network.mdx
- dotnet/docs/touch-events.mdx
- java/docs/api/class-locator.mdx
- java/docs/api/class-touchscreen.mdx
- java/docs/network.mdx
- java/docs/touch-events.mdx
- nodejs/docs/api/class-locator.mdx
- nodejs/docs/api/class-touchscreen.mdx
- nodejs/docs/network.mdx
- nodejs/docs/touch-events.mdx
- python/docs/api/class-locator.mdx
- python/docs/api/class-touchscreen.mdx
- python/docs/network.mdx
- python/docs/touch-events.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/9b633ddd2f889941f356a965cb94a60ed4d859b3
> feat(roll): roll to ToT Playwright (roll/next-25-02-25)

- dotnet/docs/api/class-locator.mdx
- dotnet/docs/locators.mdx
- java/docs/api/class-locator.mdx
- java/docs/locators.mdx
- nodejs/docs/api/class-locator.mdx
- nodejs/docs/api/class-testconfig.mdx
- nodejs/docs/locators.mdx
- nodejs/docs/test-configuration.mdx
- nodejs/docs/test-use-options.mdx
- nodejs/docs/test-webserver.mdx
- python/docs/api/class-locator.mdx
- python/docs/locators.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/aaac9923fddfd782e3fb573a71787bb77b8f40a8
> feat(roll): roll to ToT Playwright (roll/next-26-02-25)

- dotnet/docs/api/class-apirequestcontext.mdx
- dotnet/docs/api/class-browsercontext.mdx
- dotnet/docs/api/class-locator.mdx
- dotnet/docs/api/class-pageassertions.mdx
- dotnet/docs/locators.mdx
- java/docs/api/class-apirequestcontext.mdx
- java/docs/api/class-browsercontext.mdx
- java/docs/api/class-locator.mdx
- java/docs/api/class-pageassertions.mdx
- java/docs/locators.mdx
- nodejs/docs/api/class-apirequest.mdx
- nodejs/docs/api/class-apirequestcontext.mdx
- nodejs/docs/api/class-browser.mdx
- nodejs/docs/api/class-browsercontext.mdx
- nodejs/docs/api/class-fullconfig.mdx
- nodejs/docs/api/class-locator.mdx
- nodejs/docs/api/class-locatorassertions.mdx
- nodejs/docs/api/class-pageassertions.mdx
- nodejs/docs/api/class-testconfig.mdx
- nodejs/docs/api/class-testoptions.mdx
- nodejs/docs/aria-snapshots.mdx
- nodejs/docs/locators.mdx
- python/docs/api/class-apirequest.mdx
- python/docs/api/class-apirequestcontext.mdx
- python/docs/api/class-browser.mdx
- python/docs/api/class-browsercontext.mdx
- python/docs/api/class-locator.mdx
- python/docs/api/class-pageassertions.mdx
- python/docs/locators.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/2573a80893cae186c5126c9403148565524c00e2
> feat(roll): roll to ToT Playwright (roll/next-28-02-25)

- dotnet/docs/release-notes.mdx
- java/docs/release-notes.mdx
- nodejs/docs/api/class-apirequest.mdx
- nodejs/docs/api/class-apirequestcontext.mdx
- nodejs/docs/api/class-browser.mdx
- nodejs/docs/api/class-browsercontext.mdx
- nodejs/docs/api/class-testconfig.mdx
- nodejs/docs/api/class-testoptions.mdx
- nodejs/docs/api/class-teststepinfo.mdx
- nodejs/docs/release-notes.mdx
- python/docs/api/class-apirequest.mdx
- python/docs/api/class-apirequestcontext.mdx
- python/docs/api/class-browser.mdx
- python/docs/api/class-browsercontext.mdx
- python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/6fe490469aa449c96064b0f31040e1d1f8e18a9d
> feat(roll): roll to ToT Playwright (roll/next-06-03-25)

- dotnet/docs/api/class-locator.mdx
- dotnet/docs/debug.mdx
- dotnet/docs/intro.mdx
- java/docs/api/class-locator.mdx
- java/docs/debug.mdx
- java/docs/intro.mdx
- nodejs/docs/api/class-locator.mdx
- nodejs/docs/api/class-testconfig.mdx
- nodejs/docs/debug.mdx
- nodejs/docs/intro.mdx
- nodejs/docs/test-webserver.mdx
- python/docs/api/class-locator.mdx
- python/docs/debug.mdx
- python/docs/intro.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/2965c5790aee45ae100e403f6831919f094a3a24
> feat(roll): roll to ToT Playwright (roll/next-11-03-25)

- nodejs/docs/api/class-fullconfig.mdx
- nodejs/docs/api/class-testconfig.mdx
- nodejs/docs/test-webserver.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/3c14cb8d8459b28d2abab64528d0409b95126091
> feat(roll): roll to ToT Playwright (roll/next-12-03-25)

- dotnet/docs/api/class-browsertype.mdx
- dotnet/docs/aria-snapshots.mdx
- java/docs/accessibility-testing.mdx
- java/docs/api/class-browsertype.mdx
- java/docs/aria-snapshots.mdx
- java/docs/intro.mdx
- java/docs/test-runners.mdx
- java/docs/writing-tests.mdx
- nodejs/docs/accessibility-testing.mdx
- nodejs/docs/api/class-accessibility.mdx
- nodejs/docs/api/class-browsertype.mdx
- nodejs/docs/api/class-testoptions.mdx
- nodejs/docs/aria-snapshots.mdx
- nodejs/docs/best-practices.mdx
- nodejs/docs/ci-intro.mdx
- nodejs/docs/intro.mdx
- nodejs/docs/test-components.mdx
- python/docs/api-testing.mdx
- python/docs/api/class-accessibility.mdx
- python/docs/api/class-browsertype.mdx
- python/docs/aria-snapshots.mdx
- python/docs/browsers.mdx
- python/docs/library.mdx
- python/docs/test-runners.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/e976acc8eaf77905fae6da2debeed097b7bd038a
> feat(roll): roll to ToT Playwright (roll/next-13-03-25)

- dotnet/docs/api/class-locator.mdx
- java/docs/api/class-locator.mdx
- nodejs/docs/api/class-locator.mdx
- nodejs/docs/test-global-setup-teardown.mdx
- python/docs/api/class-locator.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/b3d19e2f80e0adcafc0cb4bd4790c2b228ef2de3
> feat(roll): roll to ToT Playwright (roll/next-22-03-25)

- python/docs/test-runners.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/cbed3f73e110ca819422449c64ba214cff15bfa5
> feat(roll): roll to ToT Playwright (roll/next-26-03-25)

- .github/workflows/azure-static-web-apps-delightful-forest-0a29f6210.yml
- .github/workflows/roll-next.yml
- .github/workflows/roll-stable.yml
> devops: fix roll automation

- .github/workflows/roll-next.yml
- .github/workflows/roll-stable.yml
> devops: use PW GitHub App as committer for rolls

- src/components/LiteYouTube/index.tsx
- src/data/conference-videos.tsx
- src/data/feature-videos.tsx
- src/data/learn-videos.tsx
- src/data/live-streams.tsx
- src/data/mcp-videos.tsx
- src/data/release-videos.tsx
- src/data/video-nav.tsx
- src/pages/community/mcp-videos.tsx
This PR includes several video content updates across different sections of the documentation site and introduces a new MCP (Model Context Protocol) videos page.
- New MCP videos page with dedicated content
- Multiple new videos across different categories:
- Conference videos
- Feature videos
- Learning videos
- Live streams
- Release videos
- Updated video navigation to include new sections
- Created new MCP videos page component
- Added new video data files
- Enhanced existing video collections
- Minor update to LiteYouTube component
> Video Content Update and MCP Integration

- nodejs/docs/api/class-testconfig.mdx
- nodejs/docs/test-agents.mdx
- nodejs/docs/test-reporters.mdx
- nodejs/docs/test-use-options.mdx
- nodejs/sidebars.js
- src/generator.js
> chore: roll playwright to latest
