microsoft/playwright.dev

src/fetcher.js
Fixes https://github.com/microsoft/playwright/issues/4574
=> fix: usage with localStorage when no IndexDB is available

java/docs/api/class-browsertype.mdx, java/docs/api/class-frame.mdx, java/docs/events.mdx, java/docs/network.mdx, java/docs/release-notes.mdx, nodejs/docs/api/class-android.mdx, nodejs/docs/api/class-browsertype.mdx, nodejs/docs/events.mdx, nodejs/docs/network.mdx, nodejs/docs/release-notes.mdx, python/docs/api/class-browsertype.mdx, python/docs/events.mdx, python/docs/network.mdx, python/docs/release-notes.mdx
Roll to https://github.com/microsoft/playwright/commit/4fea83c6d8f4a6b78cc6f167185cd4b84ae2c64d
=> feat: roll to v1.10

python/versioned_docs/version-1.10.0/network.mdx, python/versioned_docs/version-1.11.0/network.mdx, python/versioned_docs/version-1.9.0/network.mdx
Backport https://github.com/microsoft/playwright/pull/6716
=> fix(proxy): wrong option name for username

.github/workflows/azure-static-web-apps-delightful-forest-0a29f6210.yml, dotnet/docusaurus.config.js, java/docusaurus.config.js, nodejs/docusaurus.config.js, python/docusaurus.config.js, src/pages/index.tsx
Probably also a good way to get more stars across the languages.
Relates https://github.com/microsoft/playwright/pull/7019
=> feat: have link to the individual repositories

.github/workflows/azure-static-web-apps-delightful-forest-0a29f6210.yml
=> devops: do not deploy Azure Static Apps on external PRs

dotnet/docusaurus.config.js, dotnet/sidebars.js, java/docusaurus.config.js, java/sidebars.js, nodejs/sidebars.js, python/docusaurus.config.js, python/sidebars.js
This patch includes two changes:
a) adding the language name to the titles of the generated pages. This reduces that people end up on the wrong page when using search engines.
b) Moved the Guides section out of the Intro section into an own Guides section. Still not perfect but better so they don't need to scroll infinitely.
=> chore: improve documentation structure by adding a Guides section

.github/workflows/roll.yml, .gitignore
Demo: https://github.com/microsoft/playwright.dev/pull/266
=> feat: add automatic ToT Playwright roll

src/generator.js
Supersedes https://github.com/microsoft/playwright.dev/pull/276
See https://github.com/microsoft/playwright/pull/7860 for more information.
=> feat: support multiple language identifiers in file name

dotnet/docusaurus.config.js, java/docusaurus.config.js, nodejs/docusaurus.config.js, python/docusaurus.config.js, src/theme/NotFound.js
Actual diff to the original default implementation:
=> chore: add custom NotFound page

src/pages/versions.tsx
=> chore: fixed 404 link in versions.tsx

python/sidebars.js, python/versioned_sidebars/version-1.17-sidebars.json
=> chore: add API request to Python sidebar

dotnet/sidebars.js, dotnet/versioned_sidebars/version-1.17-sidebars.json, java/sidebars.js, java/versioned_sidebars/version-1.17-sidebars.json, nodejs/sidebars.js, nodejs/versioned_sidebars/version-1.17-sidebars.json, python/sidebars.js, python/versioned_sidebars/version-1.17-sidebars.json
=> chore: add missing framelocator to the sidebar

dotnet/sidebars.js, dotnet/versioned_sidebars/version-1.17-sidebars.json, java/sidebars.js, java/versioned_sidebars/version-1.17-sidebars.json, nodejs/sidebars.js, nodejs/versioned_sidebars/version-1.17-sidebars.json, python/sidebars.js, python/versioned_sidebars/version-1.17-sidebars.json
Reverts microsoft/playwright.dev#420
Let's get #419 in first
=> Revert "chore: add missing framelocator to the sidebar"

blog/2021-11-18-whats-new-in-playwright-1-17.md
=> chore: add whats new in 1.17 video

dotnet/docs/cli.mdx, dotnet/docs/intro.mdx, dotnet/versioned_docs/version-1.17/cli.mdx, dotnet/versioned_docs/version-1.17/intro.mdx
=> chore: roll to ToT

java/sidebars.js, java/versioned_sidebars/version-1.17-sidebars.json, python/sidebars.js, python/versioned_sidebars/version-1.17-sidebars.json
=> fix(sidebars): align sidebars, add missing items

dotnet/docusaurus.config.js, java/docusaurus.config.js, nodejs/docusaurus.config.js, python/docusaurus.config.js
Fixes https://github.com/microsoft/playwright/issues/10849
=> chore: use trailingSlash: false and fix links

java/docs/release-notes.mdx, java/versioned_docs/version-1.18/release-notes.mdx
=> fix: docs build

dotnet/sidebars.js, dotnet/versioned_sidebars/version-1.18-sidebars.json, nodejs/sidebars.js, nodejs/versioned_sidebars/version-1.18-sidebars.json, python/sidebars.js, python/versioned_sidebars/version-1.18-sidebars.json
It's available in all the languages: https://github.com/microsoft/playwright/blob/main/docs/src/selenium-grid.md
=> chore: add selenium-grid to sidebars

src/pages/index.tsx
Hi, this PR addresses some grammar on the landing page.
It also changes the links to the TypeScript and JavaScript API's to be consistent with the other languages (redirect to home VS redirect to docs).
=> Landing page grammar

blog/2022-02-09-whats-new-in-playwright-1-18.md
=> chore: add 1.18 blog video

src/components/GitHubStarButton/LICENSE, src/components/GitHubStarButton/README.md, src/components/GitHubStarButton/index.css, src/components/GitHubStarButton/index.tsx, src/pages/index.tsx
Fixes https://github.com/microsoft/playwright.dev/issues/474
=> chore: have a static GitHub star button

blog/2022-02-22-whats-new-in-playwright-1-19.md
=> chore: add what's new in pw 1.19

dotnet/sidebars.js, java/sidebars.js, nodejs/sidebars.js, python/sidebars.js, static/js/redirection.js
https://github.com/microsoft/playwright/issues/12319
=> chore: redirect away from /docs/assertions

dotnet/docs/api/class-locator.mdx, java/docs/api/class-locator.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-pageassertions.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/api/class-testproject.mdx, nodejs/docs/test-assertions.mdx, nodejs/docs/test-parallel.mdx, python/docs/api/class-locator.mdx
=> chore: roll to 03/02/22

nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-pageassertions.mdx, src/api_parser.js
=> chore: roll #12467 with assertions options fix

dotnet/docs/api/class-locatorassertions.mdx, dotnet/docs/api/class-pageassertions.mdx, java/docs/api/class-apiresponseassertions.mdx, java/docs/api/class-locatorassertions.mdx, java/docs/api/class-pageassertions.mdx, nodejs/docs/api/class-apiresponseassertions.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-pageassertions.mdx, nodejs/docs/api/class-playwrightassertions.mdx, src/format_js.js
=> fix: expect(locator). instead of locatorAssertions.

dotnet/docs/api/class-locatorassertions.mdx, dotnet/docs/api/class-pageassertions.mdx, dotnet/docs/api/class-playwrightassertions.mdx, java/docs/api/class-apiresponseassertions.mdx, java/docs/api/class-locatorassertions.mdx, java/docs/api/class-pageassertions.mdx, java/docs/api/class-playwrightassertions.mdx, python/docs/api/class-apiresponseassertions.mdx, python/docs/api/class-locatorassertions.mdx, python/docs/api/class-pageassertions.mdx, python/docs/api/class-playwrightassertions.mdx, src/format_csharp.js, src/format_java.js, src/format_js.js, src/format_python.js
=> fix: buitify assertions formatiing

dotnet/docs/api/class-elementhandle.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/pom.mdx, java/docs/api/class-elementhandle.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-page.mdx, java/docs/pom.mdx, nodejs/docs/api/class-test.mdx, nodejs/docs/intro.mdx, nodejs/docs/pom.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-pom.mdx, python/docs/docker.mdx, python/docs/pom.mdx, src/documentation.js
=> chore: roll to 3/9/22

staticwebapp.config.json
=> chore: Azure Static WebApps custom 404 page

dotnet/docusaurus.config.js, java/docusaurus.config.js, nodejs/docusaurus.config.js, package-lock.json, package.json, python/docusaurus.config.js
Relates and applying https://github.com/facebook/docusaurus/issues/6901#issuecomment-1065740929
=> chore: bump esbuild-loader

java/docs/release-notes.mdx, nodejs/docs/release-notes.mdx, python/docs/release-notes.mdx, src/format_csharp.js, src/format_java.js, src/format_js.js, src/format_python.js, src/generator.js
https://github.com/microsoft/playwright/issues/13030
=> chore: fix code snippets in release-notes

dotnet/docusaurus.config.js, java/docusaurus.config.js, python/docusaurus.config.js
This should help significant with reducing the amount of issues that language specific issues were targeting the main repo.
=> chore: have correct language specific GH links

src/theme/NotFound.js
=> chore: remove file issue logic in NotFound page

src/css/custom.css
=> fix: function parameter anchor selector

dotnet/docs/actionability.mdx, java/docs/actionability.mdx, nodejs/docs/actionability.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/api/class-testproject.mdx, nodejs/docs/test-assertions.mdx, python/docs/actionability.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/3047ef423880de57749343a68c316dbf3859f5ae
=> feat(roll): roll to ToT Playwright (roll/27-05-22)

dotnet/docs/network.mdx, dotnet/docs/test-assertions.mdx, java/docs/network.mdx, java/docs/test-assertions.mdx, nodejs/docs/test-assertions.mdx, python/docs/network.mdx, python/docs/test-assertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/40bfdb0f4e7614257c6470a7ac04d4d188bda2cf
=> feat(roll): roll to ToT Playwright (roll/03-06-22)

nodejs/docs/test-typescript.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/2d5572abd8a0f2acec65adfce08dcc2e0f7f70ca
=> feat(roll): roll to ToT Playwright (roll/06-06-22)

README.md
=> docs: document using the docs

dotnet/sidebars.js, java/sidebars.js, nodejs/sidebars.js, python/sidebars.js
Fixes https://github.com/microsoft/playwright/issues/14301
=> chore: move test assertions to guides section

README.md
=> chore: update readme to show better DX workflows

dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/browsers.mdx, java/docs/api/class-browsercontext.mdx, java/docs/api/class-page.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/browsers.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/fab12c70f7c782a82a780d460ee5bf4a291845e5
=> feat(roll): roll to ToT Playwright (roll/27-06-22)

java/versioned_docs/version-1.23/release-notes.mdx, nodejs/versioned_docs/version-1.23/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/7db695ffb5f2d3b107f2ddb401662f27de12b8bb
=> feat(roll): roll to 1.23 Playwright

dotnet/docs/api/class-browser.mdx, dotnet/docs/browsers.mdx, java/docs/api/class-browser.mdx, java/docs/browsers.mdx, nodejs/docs/accessibility-testing.mdx, nodejs/docs/api/class-browser.mdx, nodejs/docs/browsers.mdx, python/docs/api/class-browser.mdx, python/docs/browsers.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/3d1d723c564ca6840a12dda752fe29ccd22ba11b
=> feat(roll): roll to ToT Playwright (roll/30-06-22)

java/docs/release-notes.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-components.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/239119e59f1633e2b274b11da7e02bdb6e41f87f
=> feat(roll): roll to ToT Playwright (roll/01-07-22)

dotnet/docs/api/class-request.mdx, dotnet/docs/release-notes.mdx, java/docs/api/class-request.mdx, java/docs/release-notes.mdx, nodejs/docs/api/class-request.mdx, python/docs/api/class-request.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/9e62cc4da970b2256b4ecf35a4485adc4c40dd33
=> feat(roll): roll to ToT Playwright (roll/04-07-22)

nodejs/docs/api/class-suite.mdx, nodejs/docs/api/class-test.mdx, nodejs/docs/api/class-testcase.mdx, nodejs/docs/api/class-testinfo.mdx, nodejs/docs/test-auth.mdx, nodejs/docs/test-components.mdx, nodejs/docs/test-configuration.mdx, python/docs/test-runners.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/ddad16faf82f8b0e742ab7bd93067e56e1dffbd7
=> feat(roll): roll to ToT Playwright (roll/07-07-22)

dotnet/docs/inspector.mdx, java/docs/inspector.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/chrome-extensions.mdx, nodejs/docs/inspector.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-advanced.mdx, nodejs/docs/test-auth.mdx, python/docs/chrome-extensions.mdx, python/docs/inspector.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/6d030e666ea506ff9bfbdf06dc4c60e8cd5082ff
=> feat(roll): roll to ToT Playwright (roll/08-07-22)

nodejs/docs/getting-started-cli.mdx, nodejs/docs/getting-started-vscode.mdx, nodejs/docs/html-reporter.mdx, nodejs/docs/vs-code-extension.mdx, python/docs/chrome-extensions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/dd0eb5fb1d7438d76034cb7b2034ed761eaa41eb
=> feat(roll): roll to ToT Playwright (roll/11-07-22)

nodejs/sidebars.js
=> docs: sidebar improvements

community/2-live-streams.mdx
sidebar is automatic so no changes needed for this section to be shown
=> feat: add live streams to community

dotnet/sidebars.js, java/sidebars.js, nodejs/sidebars.js, python/sidebars.js
=> chore: add Service Workers guide to sidebar

dotnet/sidebars.js, java/sidebars.js, nodejs/sidebars.js, python/sidebars.js
This reverts commit aadf7d0f2a5402cc1a92b9d0483519fba685dc95.
=> Revert "chore: add Service Workers guide to sidebar (#648)"

dotnet/sidebars.js
=> chore: enhance .NET intro and update test-runner docs

dotnet/docs/auth.mdx, dotnet/docs/intro.mdx, dotnet/docs/writing-tests.mdx, java/docs/auth.mdx, nodejs/docs/auth.mdx, nodejs/docs/getting-started-vscode.mdx, nodejs/docs/intro.mdx, nodejs/docs/test-configuration.mdx, nodejs/docs/writing-tests.mdx, nodejs/sidebars.js, python/docs/api-testing.mdx, python/docs/auth.mdx, python/docs/intro.mdx, python/docs/library.mdx, python/docs/running-tests.mdx, python/docs/test-runners.mdx, python/docs/writing-tests.mdx, python/sidebars.js
=> docs: new Python onboarding story

dotnet/docs/locators.mdx, dotnet/docs/release-notes.mdx, dotnet/docs/selectors.mdx, dotnet/docs/writing-tests.mdx, java/docs/locators.mdx, java/docs/release-notes.mdx, java/docs/selectors.mdx, nodejs/docs/codegen.mdx, nodejs/docs/locators.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/selectors.mdx, nodejs/docs/test-snapshots.mdx, nodejs/docs/writing-tests.mdx, python/docs/library.mdx, python/docs/locators.mdx, python/docs/release-notes.mdx, python/docs/selectors.mdx, python/docs/writing-tests.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/6625456f3389bab74d61819d8dfd07572004bb98
=> feat(roll): roll to ToT Playwright (roll/21-07-22)

dotnet/versioned_docs/version-1.24/release-notes.mdx, java/versioned_docs/version-1.24/release-notes.mdx, python/versioned_docs/version-1.24/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/19a19ae1b7c01f65aed7fcd12ffc69c5247eb9f8
=> feat(roll): roll to 1.24 Playwright

nodejs/docs/test-typescript.mdx, nodejs/docs/troubleshooting.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/532cf453931e043cdf0b470883bf6a343f20f0d9
=> feat(roll): roll to ToT Playwright (roll/22-07-22)

README.md
=> chore: document doc cherry-pick workflow

dotnet/sidebars.js, nodejs/sidebars.js
Fixes https://github.com/microsoft/playwright/issues/15884.
=> chore: add class-accessibility to sidebars

dotnet/docs/intro.mdx, dotnet/docs/troubleshooting.mdx, java/docs/troubleshooting.mdx, nodejs/docs/library.mdx, python/docs/library.mdx, python/docs/test-runners.mdx, python/docs/troubleshooting.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/4bec6309df2c45ecbbb2767201a98f89f1cf8f5e
=> feat(roll): roll to ToT Playwright (roll/25-07-22)

common/links-csharp.md, common/links-java.md, common/links-js.md, common/links-python.md
=> chore: update outdated Docker links

dotnet/docs/api-testing.mdx, dotnet/docs/debug.mdx, dotnet/docs/release-notes.mdx, dotnet/docs/running-tests.mdx, dotnet/docs/test-assertions.mdx, dotnet/docs/troubleshooting.mdx, java/docs/debug.mdx, java/docs/troubleshooting.mdx, nodejs/docs/api/class-reporter.mdx, nodejs/docs/debug.mdx, nodejs/docs/troubleshooting.mdx, python/docs/debug.mdx, python/docs/running-tests.mdx, python/docs/troubleshooting.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/54f7141877600cd396f882a685b95dad875422d6
=> feat(roll): roll to ToT Playwright (roll/27-07-22)

dotnet/sidebars.js, java/sidebars.js, nodejs/sidebars.js, python/sidebars.js
=> dos: Troubleshooting sidebar

src/components/ProfileCard/index.tsx
=> New ambassador

src/components/ProfileCard/index.tsx
=> docs: add next ambassador

src/components/ProfileCard/index.tsx, src/components/ProfileCard/styles.module.css
=> docs: improve resonsive for ambassadors

community/1-conference-videos.mdx
=> docs: add new talk

dotnet/docs/selectors.mdx, java/docs/selectors.mdx, nodejs/docs/api/class-testcase.mdx, nodejs/docs/selectors.mdx, python/docs/selectors.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/62e4e80599efc00a799a389ee4be76c74c9f172b
=> feat(roll): roll to ToT Playwright (roll/29-07-22)

dotnet/docs/codegen.mdx, java/docs/codegen.mdx, nodejs/docs/api/class-test.mdx, nodejs/docs/codegen.mdx, nodejs/docs/intro.mdx, nodejs/docs/running-tests.mdx, python/docs/codegen.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/4112eb815ecccdc926e56051d822c921b78fbc23
=> feat(roll): roll to ToT Playwright (roll/01-08-22)

package-lock.json, package.json
=> chore: pwt to 1.24

community/1-conference-videos.mdx
=> docs: change order and fix layout

dotnet/docs/api/class-browsertype.mdx, java/docs/api/class-browsertype.mdx, nodejs/docs/api/class-browsertype.mdx, nodejs/docs/api/class-testcase.mdx, nodejs/docs/api/class-testinfo.mdx, nodejs/docs/api/class-testproject.mdx, nodejs/docs/api/class-testresult.mdx, nodejs/docs/getting-started-vscode.mdx, nodejs/docs/library.mdx, nodejs/docs/test-advanced.mdx, nodejs/docs/test-parallel.mdx, python/docs/api/class-browsertype.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/8ef01cd07e142dc2e914f81c3d29df6620edca5a
=> feat(roll): roll to ToT Playwright (roll/03-08-22)

dotnet/docusaurus.config.js, java/docusaurus.config.js, nodejs/docusaurus.config.js, python/docusaurus.config.js
drive-by formatting and removal of the unused blog plugin.
=> chore: hide stable version in docs

community/1-conference-videos.mdx
=> docs: add python conf videos

dotnet/docusaurus.config.js, java/docusaurus.config.js, nodejs/docusaurus.config.js, python/docusaurus.config.js
=> chore: do not break build if there is no stable version

.github/workflows/create_release.yml, .github/workflows/deploy.yml, .github/workflows/test.yml, package-lock.json, package.json
~~Depends on https://github.com/microsoft/playwright.dev/pull/702~~
=> chore: upgrade docusaurus to 2.0.0

src/theme/NavbarItem/NavbarNavLink.js, src/theme/NavbarItem/index.js
=> chore: do not show language dropdown as external links

dotnet/docs/selenium-grid.mdx, java/docs/selenium-grid.mdx, nodejs/docs/selenium-grid.mdx, python/docs/running-tests.mdx, python/docs/selenium-grid.mdx, python/docs/test-runners.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/93a96347c22a2e5db2b57b9f424db2c998ce2d1e
=> feat(roll): roll to ToT Playwright (roll/05-08-22)

src/components/ProfileCard/index.tsx
=> docs: remove Ross linkedin from ambassador page

community/4-release-videos.mdx
=> docs: add 1.24 release video

dotnet/docs/emulation.mdx, dotnet/docs/release-notes.mdx, dotnet/docs/selectors.mdx, java/docs/emulation.mdx, java/docs/release-notes.mdx, java/docs/selectors.mdx, nodejs/docs/auth.mdx, nodejs/docs/canary-releases.mdx, nodejs/docs/emulation.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/selectors.mdx, nodejs/sidebars.js, python/docs/emulation.mdx, python/docs/release-notes.mdx, python/docs/selectors.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/0013531c8152a5a77a65e8679ea820df988bc0b7
=> feat(roll): roll to ToT Playwright (roll/09-08-22)

dotnet/docs/codegen.mdx, dotnet/docs/intro.mdx, dotnet/docs/trace-viewer-intro.mdx, dotnet/docs/writing-tests.mdx, java/docs/codegen.mdx, java/docs/trace-viewer-intro.mdx, nodejs/docs/ci-intro.mdx, nodejs/docs/getting-started-vscode.mdx, nodejs/docs/intro.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/running-tests.mdx, nodejs/docs/trace-viewer-intro.mdx, nodejs/docs/trace-viewer.mdx, nodejs/docs/writing-tests.mdx, python/docs/codegen.mdx, python/docs/running-tests.mdx, python/docs/trace-viewer-intro.mdx, python/docs/writing-tests.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/16d9f66ff97b3fb2759bc6fec80cefc1e2843502
=> feat(roll): roll to ToT Playwright (roll/10-08-22)

dotnet/docs/codegen-intro.mdx, java/docs/codegen-intro.mdx, nodejs/docs/api/class-test.mdx, nodejs/docs/codegen-intro.mdx, nodejs/docs/test-reporters.mdx, python/docs/codegen-intro.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/d12afa7ff399c8a9479394bcb1fc492d192e8173
=> feat(roll): roll to ToT Playwright (roll/11-08-22)

dotnet/sidebars.js, java/sidebars.js, nodejs/sidebars.js, python/sidebars.js
=> docs: add trace viewer intro to sidebars

dotnet/versioned_docs/version-stable/codegen-intro.mdx, dotnet/versioned_docs/version-stable/codegen.mdx, dotnet/versioned_docs/version-stable/intro.mdx, dotnet/versioned_docs/version-stable/trace-viewer-intro.mdx, dotnet/versioned_docs/version-stable/writing-tests.mdx, dotnet/versioned_sidebars/version-stable-sidebars.json, java/versioned_docs/version-stable/codegen-intro.mdx, java/versioned_docs/version-stable/trace-viewer-intro.mdx, java/versioned_sidebars/version-stable-sidebars.json, nodejs/versioned_docs/version-stable/api/class-test.mdx, nodejs/versioned_docs/version-stable/ci-intro.mdx, nodejs/versioned_docs/version-stable/codegen-intro.mdx, nodejs/versioned_docs/version-stable/getting-started-vscode.mdx, nodejs/versioned_docs/version-stable/intro.mdx, nodejs/versioned_docs/version-stable/running-tests.mdx, nodejs/versioned_docs/version-stable/test-reporters.mdx, nodejs/versioned_docs/version-stable/trace-viewer-intro.mdx, nodejs/versioned_docs/version-stable/trace-viewer.mdx, nodejs/versioned_docs/version-stable/writing-tests.mdx, nodejs/versioned_sidebars/version-stable-sidebars.json, python/versioned_docs/version-stable/codegen-intro.mdx, python/versioned_docs/version-stable/running-tests.mdx, python/versioned_docs/version-stable/trace-viewer-intro.mdx, python/versioned_docs/version-stable/writing-tests.mdx, python/versioned_sidebars/version-stable-sidebars.json
Upstream commit: https://github.com/microsoft/playwright/commit/3bc6b4b644f3aa4bd7ecdd506c479a6841e986f8
=> feat(roll): roll to 1.25 Playwright

java/docs/test-assertions.mdx, src/generator.js
=> fix: add setDefaultAssertionTimeout to the assertions page

nodejs/docs/mock.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/3dc1920ce83b56a408d84e2d43e07ec8976d924d
=> feat(roll): roll to ToT Playwright (roll/12-08-22)

dotnet/docs/browsers.mdx, dotnet/docs/ci.mdx, dotnet/docs/cli.mdx, dotnet/docs/codegen-intro.mdx, dotnet/docs/codegen.mdx, dotnet/docs/debug.mdx, dotnet/docs/intro.mdx, dotnet/docs/library.mdx, dotnet/docs/network.mdx, dotnet/docs/release-notes.mdx, dotnet/docs/test-runners.mdx, dotnet/docs/trace-viewer-intro.mdx, dotnet/docs/trace-viewer.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/8170432fabd51bec26e833ec7a4a1bb55dcf37d4
=> feat(roll): roll to ToT Playwright (roll/15-08-22)

dotnet/docs/auth.mdx, java/docs/auth.mdx, nodejs/docs/auth.mdx, nodejs/docs/test-components.mdx, python/docs/auth.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/80389c7d476c4ff3c5d863fb9e95635db257299c
=> feat(roll): roll to ToT Playwright (roll/24-08-22)

dotnet/docs/api/class-selectors.mdx, dotnet/docs/test-assertions.mdx, java/docs/api/class-selectors.mdx, java/docs/extensibility.mdx, java/docs/test-assertions.mdx, nodejs/docs/api/class-selectors.mdx, nodejs/docs/ci.mdx, nodejs/docs/test-assertions.mdx, nodejs/docs/trace-viewer-intro.mdx, python/docs/test-assertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/29d4397a0b5a89e80d0d311d98470f2cd6132506
=> feat(roll): roll to ToT Playwright (roll/31-08-22)

community/4-release-videos.mdx
=> chore: add 1.25 release video

nodejs/docs/api/class-testconfig.mdx, nodejs/docs/test-cli.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/da1921932357b19505b83d95c9be5e3b5f5f0d8c
=> feat(roll): roll to ToT Playwright (roll/02-09-22)

package-lock.json, package.json
=> chore: bump docusaurus to 2.1.0

dotnet/docs/ci.mdx, dotnet/docs/test-assertions.mdx, java/docs/ci.mdx, java/docs/test-assertions.mdx, nodejs/docs/ci.mdx, nodejs/docs/puppeteer.mdx, nodejs/docs/test-assertions.mdx, python/docs/ci.mdx, python/docs/test-assertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/6e1c94b5fefbb7da8392c2b1e2a3a04692c992e8
=> feat(roll): roll to ToT Playwright (roll/07-09-22)

dotnet/docs/events.mdx, dotnet/docs/input.mdx, dotnet/docs/pom.mdx, dotnet/docs/test-assertions.mdx, dotnet/docs/trace-viewer-intro.mdx, java/docs/events.mdx, java/docs/input.mdx, java/docs/pom.mdx, java/docs/test-assertions.mdx, java/docs/trace-viewer-intro.mdx, nodejs/docs/events.mdx, nodejs/docs/input.mdx, nodejs/docs/pom.mdx, nodejs/docs/running-tests.mdx, nodejs/docs/test-assertions.mdx, nodejs/docs/trace-viewer-intro.mdx, python/docs/events.mdx, python/docs/input.mdx, python/docs/pom.mdx, python/docs/test-assertions.mdx, python/docs/trace-viewer-intro.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/47b9595b95e56301007c4c0deea2ac5aafa0018b
=> feat(roll): roll to ToT Playwright (roll/09-09-22)

dotnet/docs/api-testing.mdx, dotnet/docs/intro.mdx, dotnet/docs/release-notes.mdx, dotnet/docs/test-assertions.mdx, dotnet/docs/test-runners.mdx, dotnet/docs/writing-tests.mdx, java/docs/release-notes.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/api/class-testproject.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-assertions.mdx, nodejs/docs/test-configuration.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/58873908ba6db65ea9500331bf1770ad50528fe3
=> feat(roll): roll to ToT Playwright (roll/14-09-22)

dotnet/docs/release-notes.mdx, dotnet/docs/test-assertions.mdx, java/docs/release-notes.mdx, java/docs/test-assertions.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-assertions.mdx, nodejs/docs/test-components.mdx, python/docs/release-notes.mdx, python/docs/test-assertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/ee83694372e2cd8a03131c042189a5359504f1b6
=> feat(roll): roll to ToT Playwright (roll/19-09-22)

dotnet/versioned_docs/version-stable/release-notes.mdx, java/versioned_docs/version-stable/release-notes.mdx, nodejs/versioned_docs/version-stable/release-notes.mdx, python/versioned_docs/version-stable/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/5455a5a5fb3e1f29f1b9bbd85a4bc342ac73d189
=> feat(roll): roll to 1.26 Playwright

nodejs/docs/api/class-testconfig.mdx, nodejs/docs/pom.mdx, nodejs/docs/test-reporters.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/ec40e4997877341089b25141a10ddb4fd9870dc6
=> feat(roll): roll to ToT Playwright (roll/26-09-22)

dotnet/docs/webview2.mdx, dotnet/sidebars.js, java/docs/webview2.mdx, java/docusaurus.config.js, java/sidebars.js, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/pom.mdx, nodejs/docs/test-reporters.mdx, nodejs/docs/webview2.mdx, nodejs/docusaurus.config.js, nodejs/sidebars.js, python/docs/webview2.mdx, python/docusaurus.config.js, python/sidebars.js, src/generator.js
=> chore: add webview2 guide

dotnet/docs/input.mdx, dotnet/docs/network.mdx, java/docs/input.mdx, java/docs/network.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/input.mdx, nodejs/docs/network.mdx, python/docs/input.mdx, python/docs/network.mdx, src/api_parser.js
Upstream commit: https://github.com/microsoft/playwright/commit/43ccd7bc9675c029176fba12796a9df476dd5e38
=> feat(roll): roll to ToT Playwright (roll/29-09-22)

dotnet/docs/api/class-frame.mdx, dotnet/docs/api/class-framelocator.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/test-assertions.mdx, java/docs/api/class-frame.mdx, java/docs/api/class-framelocator.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-page.mdx, java/docs/test-assertions.mdx, nodejs/docs/api/class-frame.mdx, nodejs/docs/api/class-framelocator.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-testproject.mdx, nodejs/docs/docker.mdx, nodejs/docs/test-assertions.mdx, nodejs/docs/test-components.mdx, nodejs/docs/testing-library.mdx, python/docs/api/class-frame.mdx, python/docs/api/class-framelocator.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-page.mdx, python/docs/test-assertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/0e740f85eaf913b6c86b1881a82a8f1e7262b445
=> feat(roll): roll to ToT Playwright (roll/30-09-22)

dotnet/docs/locators.mdx, java/docs/locators.mdx, nodejs/docs/locators.mdx, python/docs/locators.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/f14f69624f3793c84537a546b67969cae67ceff9
=> feat(roll): roll to ToT Playwright (roll/03-10-22)

dotnet/docs/api/class-frame.mdx, dotnet/docs/api/class-framelocator.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/release-notes.mdx, java/docs/api/class-frame.mdx, java/docs/api/class-framelocator.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-page.mdx, nodejs/docs/api/class-frame.mdx, nodejs/docs/api/class-framelocator.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-testproject.mdx, python/docs/api/class-frame.mdx, python/docs/api/class-framelocator.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/693ed9b19e03f7d29ef188e8b71d6f9485093c8b
=> feat(roll): roll to ToT Playwright (roll/14-10-22)

dotnet/docs/writing-tests.mdx, nodejs/docs/writing-tests.mdx, python/docs/writing-tests.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/7219a68b1203b9fcb74d970630cb87a4f1b4e756
=> feat(roll): roll to ToT Playwright (roll/17-10-22)

dotnet/docs/languages.mdx, java/docs/languages.mdx, nodejs/docs/api/class-testproject.mdx, nodejs/docs/languages.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-assertions.mdx, nodejs/docs/test-timeouts.mdx, python/docs/languages.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/1b541c993296c27f6bcde349aa830fe9baabaf96
=> feat(roll): roll to ToT Playwright (roll/19-10-22)

dotnet/docs/debug.mdx, dotnet/docs/intro.mdx, dotnet/docs/writing-tests.mdx, java/docs/debug.mdx, java/docs/running-tests.mdx, java/docs/test-runners.mdx, java/docs/writing-tests.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/debug.mdx, nodejs/docs/intro.mdx, nodejs/docs/pom.mdx, nodejs/docs/test-pom.mdx, nodejs/docs/writing-tests.mdx, python/docs/debug.mdx, python/docs/intro.mdx, python/docs/writing-tests.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/3c0832a0d94c6c88984e0b5db246d7b3c660df74
=> feat(roll): roll to ToT Playwright (roll/24-10-22)

dotnet/docs/api/class-elementhandle.mdx, dotnet/docs/api/class-frame.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/browser-contexts.mdx, java/docs/api/class-elementhandle.mdx, java/docs/api/class-frame.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-page.mdx, java/docs/browser-contexts.mdx, nodejs/docs/api/class-android.mdx, nodejs/docs/api/class-androiddevice.mdx, nodejs/docs/api/class-elementhandle.mdx, nodejs/docs/api/class-frame.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/browser-contexts.mdx, nodejs/docs/library.mdx, nodejs/docs/test-cli.mdx, nodejs/docs/test-reporters.mdx, python/docs/api/class-elementhandle.mdx, python/docs/api/class-frame.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-page.mdx, python/docs/browser-contexts.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/e25537f94193fe74174698f65b66d3bf3586f41d
=> feat(roll): roll to ToT Playwright (roll/26-10-22)

dotnet/docs/api/class-selectors.mdx, dotnet/docs/locators.mdx, dotnet/docs/writing-tests.mdx, java/docs/locators.mdx, nodejs/docs/locators.mdx, nodejs/docs/writing-tests.mdx, python/docs/api/class-jshandle.mdx, python/docs/locators.mdx, python/docs/writing-tests.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/490513a01798fe2acc58e0927f2d10c82c33337e
=> feat(roll): roll to ToT Playwright (roll/31-10-22)

community/1-conference-videos.mdx, community/4-release-videos.mdx
=> docs: add release and conf videos

dotnet/docs/locators.mdx, java/docs/locators.mdx, nodejs/docs/locators.mdx, python/docs/locators.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/0387d96cd5d86bb4309629b707408a39ff4ae3ff
=> feat(roll): roll to ToT Playwright (roll/16-11-22)

dotnet/docusaurus.config.js, java/docusaurus.config.js, nodejs/docusaurus.config.js, python/docusaurus.config.js, src/config/prismDark.js, src/config/prismLight.js
=> chore: respect theme in code snippets

src/data/conference-videos.tsx, src/data/video-nav.tsx, src/pages/community/conference-videos.tsx
=> docs: add more videos

dotnet/docs/api/class-page.mdx, dotnet/docs/locators.mdx, java/docs/locators.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/1ec0bb277df00f78593f7e522f9fc825d48e1403
=> feat(roll): roll to ToT Playwright (roll/18-11-22)

dotnet/versioned_docs/version-stable/locators.mdx, java/versioned_docs/version-stable/locators.mdx, nodejs/versioned_docs/version-stable/locators.mdx, python/versioned_docs/version-stable/locators.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/36f8a6399c8dfe894526f6022d492d1226a33801
=> feat(roll): roll to 1.28 Playwright

src/format_csharp.js, src/format_java.js, src/format_js.js, src/format_python.js, src/generator.js
=> chore: trim the signatures from the links

src/api_parser.js, src/documentation.js, src/format_utils.js, src/generator.js, src/markdown.js
=> chore: roll to the new docs/markdown versions

common/links-js.md
=> fix: fs.ReadStrem link

nodejs/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/9e91ca353c27cda89d16d2fff8ab270894866c0d
=> feat(roll): roll to ToT Playwright (roll/28-11-22)

dotnet/docs/intro.mdx, dotnet/docs/locators.mdx, dotnet/docs/writing-tests.mdx, java/docs/locators.mdx, nodejs/docs/locators.mdx, python/docs/locators.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/307a0b6ea7508306dd99c5819c47a23081760531
=> feat(roll): roll to ToT Playwright (roll/30-11-22)

src/theme/NavbarItem/index.js, static/js/redirection.js
Fixes https://github.com/microsoft/playwright/issues/19144
=> chore: remember selected language

dotnet/docs/api/class-locator.mdx, java/docs/api/class-locator.mdx, nodejs/docs/api/class-locator.mdx, python/docs/api/class-locator.mdx, src/generator.js
=> chore: introduce details

dotnet/docs/api/class-elementhandle.mdx, dotnet/docs/api/class-frame.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-page.mdx, java/docs/api/class-elementhandle.mdx, java/docs/api/class-frame.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-page.mdx, nodejs/docs/api/class-elementhandle.mdx, nodejs/docs/api/class-frame.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-testoptions.mdx, python/docs/api/class-locator.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/858c2453b3fe35f79da3a8c4abdf093ca346aff4
=> feat(roll): roll to ToT Playwright (roll/09-12-22)

dotnet/docs/api/class-locator.mdx, dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, dotnet/docs/locators.mdx, java/docs/api/class-locator.mdx, java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, java/docs/locators.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-pageassertions.mdx, nodejs/docs/api/class-snapshotassertions.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/api/class-testproject.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/locators.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-assertions.mdx, nodejs/docs/test-cli.mdx, nodejs/docs/test-fixtures.mdx, nodejs/docs/test-snapshots.mdx, python/docs/api/class-locator.mdx, python/docs/ci.mdx, python/docs/docker.mdx, python/docs/locators.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/ba8a6c4b086f1cf6caa2107ee19764931beee85f
=> feat(roll): roll to ToT Playwright (roll/16-12-22)

java/docs/api/class-route.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/b5f908d31f821a7462cf6caa92a2a85e9602a25b
=> feat(roll): roll to ToT Playwright (roll/17-12-22)

dotnet/docs/intro.mdx, dotnet/docs/writing-tests.mdx, nodejs/docs/api/class-testresult.mdx, nodejs/docs/auth.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/412c11db208da0543137ac781e775578a72eaece
=> feat(roll): roll to ToT Playwright (roll/20-12-22)

src/data/ambassadors.tsx, src/data/team.tsx
=> docs: add new ambassadors, update team

nodejs/versioned_docs/version-stable/auth.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/efa3756c1620502d715a4595b91e8e41ad6a320f
=> feat(roll): roll to 1.29 Playwright

nodejs/docs/emulation.mdx, nodejs/docs/network.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/cce29215f927beb182f92516eda787c0cd61b8b8
=> feat(roll): roll to ToT Playwright (roll/25-12-22)

dotnet/docs/languages.mdx, java/docs/languages.mdx, nodejs/docs/languages.mdx, python/docs/languages.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/9f27b300f45a843c880e67b4bfb0fc5646a0ccae
=> feat(roll): roll to ToT Playwright (roll/03-01-23)

dotnet/docs/api/class-route.mdx, dotnet/docs/languages.mdx, java/docs/languages.mdx, nodejs/docs/languages.mdx, python/docs/api/class-route.mdx, python/docs/languages.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/711a1aadbf82129a5cf5f108b062bcf70478646f
=> feat(roll): roll to ToT Playwright (roll/04-01-23)

java/sidebars.js
=> chore: add new intro to java sidebar

dotnet/docs/api/class-locator.mdx, dotnet/docs/ci.mdx, java/docs/api/class-locator.mdx, java/docs/browsers.mdx, java/docs/ci.mdx, java/docs/cli.mdx, java/docs/codegen-intro.mdx, java/docs/codegen.mdx, java/docs/debug.mdx, java/docs/intro.mdx, java/docs/network.mdx, java/docs/release-notes.mdx, java/docs/trace-viewer-intro.mdx, java/docs/trace-viewer.mdx, java/docs/writing-tests.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/chrome-extensions.mdx, nodejs/docs/ci.mdx, nodejs/docs/test-advanced.mdx, python/docs/api/class-locator.mdx, python/docs/chrome-extensions.mdx, python/docs/ci.mdx, src/generator.js
Title.
Since.
Deprecation note.
Short description.
Usage.
Arguments.
Return type.
Details.
=> feat(api docs): explicitly sort sections

dotnet/docs/ci.mdx, java/docs/ci.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/ci.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-page.mdx, python/docs/ci.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/2394debce573135a998198ec798f42acbec5f4cc
=> feat(roll): roll to ToT Playwright (roll/11-01-23)

community/ambassadors.mdx, src/data/ambassadors.tsx
improve message for discord channels
remove non active ambassador
fix broken image
=> docs: update ambassadors

dotnet/docs/network.mdx, java/docs/network.mdx, nodejs/docs/network.mdx, nodejs/docs/test-fixtures.mdx, python/docs/network.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/9a5df720ff2d529b38cd5f58ab6ce95bae93a16d
=> feat(roll): roll to ToT Playwright (roll/12-01-23)

nodejs/docs/best-practices.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/e780a5c1acf4927a515515086c8d5f69a23b19e1
=> feat(roll): roll to ToT Playwright (roll/16-01-23)

nodejs/docs/writing-tests.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/92375f63338c32aee8c4f3f9b70660577e1a87f2
=> feat(roll): roll to ToT Playwright (roll/17-01-23)

dotnet/docs/api/class-apirequest.mdx, dotnet/docs/api/class-apirequestcontext.mdx, dotnet/docs/api/class-browser.mdx, dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-browsertype.mdx, dotnet/docs/api/class-elementhandle.mdx, dotnet/docs/api/class-filechooser.mdx, dotnet/docs/api/class-frame.mdx, dotnet/docs/api/class-keyboard.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-locatorassertions.mdx, dotnet/docs/api/class-mouse.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/api/class-pageassertions.mdx, dotnet/docs/api/class-request.mdx, dotnet/docs/api/class-response.mdx, dotnet/docs/api/class-touchscreen.mdx, nodejs/docs/writing-tests.mdx, src/format_csharp.js
Fixes https://github.com/microsoft/playwright-dotnet/issues/2443
=> chore: .NET s/double/float/g

dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, dotnet/docs/release-notes.mdx, java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, java/docs/release-notes.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-snapshots.mdx, python/docs/ci.mdx, python/docs/docker.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/b700c08dc5e6bed3dc23fa6f210d6f9d7a7c6500
=> feat(roll): roll to ToT Playwright (roll/21-01-23)

java/docs/input.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/953f96b49397a9eb1aa47931f80841d38a3a0d55
=> feat(roll): roll to ToT Playwright (roll/23-01-23)

nodejs/sidebars.js
=> docs: add best practices to js sidebar

java/docs/api/class-playwright.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/d7366cfc7c68a9c2f9454c99e305f0dc2e8cf532
=> feat(roll): roll to ToT Playwright (roll/25-01-23)

nodejs/versioned_sidebars/version-stable-sidebars.json
Upstream commit: https://github.com/microsoft/playwright/commit/aea542f7a283a305eb10b1d2cfec29b5742eacc9
=> feat(roll): roll to 1.30 Playwright

dotnet/docs/api/class-page.mdx, dotnet/docs/api/class-touchscreen.mdx, java/docs/api/class-page.mdx, java/docs/api/class-touchscreen.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-touchscreen.mdx, nodejs/docs/test-components.mdx, python/docs/api/class-page.mdx, python/docs/api/class-touchscreen.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/821949d580eb953176d5bc38a2aa416b2707dd88
=> feat(roll): roll to ToT Playwright (roll/28-01-23)

nodejs/docs/api/class-reporter.mdx, nodejs/docs/getting-started-vscode.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/32724cd5ce4e2717b38ca37a26f25e2331217fe4
=> feat(roll): roll to ToT Playwright (roll/29-01-23)

dotnet/docs/api/class-consolemessage.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/b39079b51ed6227b274dce7d9ccee5ad4c61f94a
=> feat(roll): roll to ToT Playwright (roll/31-01-23)

dotnet/docs/auth.mdx, dotnet/docs/docker.mdx, java/docs/auth.mdx, java/docs/docker.mdx, nodejs/docs/auth.mdx, nodejs/docs/docker.mdx, nodejs/docs/test-components.mdx, python/docs/auth.mdx, python/docs/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/758246bb9e82e3724ee5cc777e2232bf1533755e
=> feat(roll): roll to ToT Playwright (roll/04-02-23)

nodejs/docs/chrome-extensions.mdx, nodejs/docs/test-advanced.mdx, python/docs/chrome-extensions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/bcecce6b6e5215a6b129e4fadcd60bd42838ddf2
=> feat(roll): roll to ToT Playwright (roll/06-02-23)

dotnet/docs/api/class-selectors.mdx, dotnet/docs/extensibility.mdx, java/docs/api/class-selectors.mdx, java/docs/extensibility.mdx, nodejs/docs/api/class-selectors.mdx, nodejs/docs/api/class-test.mdx, nodejs/docs/extensibility.mdx, nodejs/docs/test-advanced.mdx, nodejs/docs/test-assertions.mdx, nodejs/docs/writing-tests.mdx, python/docs/api/class-selectors.mdx, python/docs/downloads.mdx, python/docs/extensibility.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/d3c5430080666174de4a221ecaf886cd625784b1
=> feat(roll): roll to ToT Playwright (roll/07-02-23)

src/documentation.js
Upstream commit: https://github.com/microsoft/playwright/commit/6b0a7003c4e2d155fdb04301dd8e6b2e52646a85
=> feat(roll): roll to ToT Playwright (roll/09-02-23)

nodejs/docs/test-components.mdx, python/docs/api/class-selectors.mdx, src/documentation.js
Upstream commit: https://github.com/microsoft/playwright/commit/778dd204035db6318a658de7041b0c81d76975dd
=> feat(roll): roll to ToT Playwright (roll/10-02-23)

dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-frame.mdx, dotnet/docs/api/class-locatorassertions.mdx, dotnet/docs/api/class-page.mdx, java/docs/api/class-browsercontext.mdx, java/docs/api/class-frame.mdx, java/docs/api/class-locatorassertions.mdx, java/docs/api/class-page.mdx, java/docs/api/class-websocket.mdx, java/docs/api/class-worker.mdx, nodejs/docs/api/class-elementhandle.mdx, nodejs/docs/api/class-frame.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/test-assertions.mdx, python/docs/api/class-locatorassertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/de69b766d9f8d8bdbc20c1a1b4ffcfc9869d0625
=> feat(roll): roll to ToT Playwright (roll/11-02-23)

package-lock.json, package.json, src/components/LiteYouTube/index.tsx, src/components/LiteYouTube/styles.module.css
make youtube embeds more performant by not loading the iframe until the button is clicked
=> feat: new component for youtube embeds

src/components/LiteYouTube/index.tsx, src/components/LiteYouTube/styles.module.css, src/components/VideoCards/index.tsx, src/components/VideoCards/styles.module.css, src/css/custom.css, src/data/conference-videos.tsx, src/data/live-streams.tsx, src/data/release-videos.tsx
update conference videos, release videos etc
add manual thumbnail for those that don't have a thumbnail
remove unused styling and add new styles for button
=> chore: update videos to use new component

dotnet/docs/auth.mdx, java/docs/auth.mdx, nodejs/docs/auth.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-components.mdx, python/docs/auth.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/91da67fab16d76fbf1c174cd7f335f805cd16833
=> feat(roll): roll to ToT Playwright (roll/15-02-23)

dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, nodejs/docs/best-practices.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-reporters.mdx, nodejs/docs/test-snapshots.mdx, python/docs/ci.mdx, python/docs/docker.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/e77e2d8c7f5ec14ddb34f56c4987b8b112bc2d12
=> feat(roll): roll to ToT Playwright (roll/16-02-23)

dotnet/docs/auth.mdx, java/docs/auth.mdx, nodejs/docs/auth.mdx, python/docs/auth.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/595502ac46694843b443303ad78cd659fd995cc5
=> feat(roll): roll to ToT Playwright (roll/19-02-23)

dotnet/docs/browsers.mdx, java/docs/browsers.mdx, nodejs/docs/browsers.mdx, nodejs/docs/release-notes.mdx, python/docs/browsers.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/cda830645dd8ec1bca604c59d6f95a3a4b65c4fc
=> feat(roll): roll to ToT Playwright (roll/21-02-23)

nodejs/docs/api/class-genericassertions.mdx, nodejs/docs/running-tests.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/135e9f828127723b1ed00f1702a4b69ae41514ba
=> feat(roll): roll to ToT Playwright (roll/22-02-23)

common/links-csharp.md, common/links-java.md, common/links-js.md, common/links-python.md
https://github.com/microsoft/playwright/issues/21095
=> chore: not mention DockerHub anymore

python/docs/test-assertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/a031cec1596caec15a7050948af69d10409d1807
=> feat(roll): roll to ToT Playwright (roll/24-02-23)

nodejs/docs/api/class-reporter.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/09f77c41dd61c06d0dcdf2d7617fca7622ecd6ba
=> feat(roll): roll to ToT Playwright (roll/25-02-23)

dotnet/docs/api/class-frame.mdx, dotnet/docs/api/class-page.mdx, src/generator.js
Fixes https://github.com/microsoft/playwright-dotnet/issues/2434
=> fix(dotnet): fix literal type overrides

dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/selenium-grid.mdx, java/docs/api/class-browsercontext.mdx, java/docs/api/class-page.mdx, java/docs/selenium-grid.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-electronapplication.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/selenium-grid.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-page.mdx, python/docs/selenium-grid.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/daf914b3981740f25a2e8c2e6e534bbf9f4310df
=> feat(roll): roll to ToT Playwright (roll/28-02-23)

dotnet/docs/browsers.mdx, java/docs/browsers.mdx, nodejs/docs/browsers.mdx, nodejs/docs/running-tests.mdx, python/docs/browsers.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/d12d35f1241d5e38bda541b63fffae65ecdda009
=> feat(roll): roll to ToT Playwright (roll/01-03-23)

dotnet/docs/api/class-frame.mdx, java/docs/api/class-frame.mdx, nodejs/docs/api/class-frame.mdx, python/docs/api/class-frame.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/bfc895787fdff1c22b15ef775092585bc2c88791
=> feat(roll): roll to ToT Playwright (roll/02-03-23)

nodejs/docs/test-parallel.mdx, nodejs/docs/test-retries.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/6769a311ed05f079375e3b5d28e01d6c7bbf7efd
=> feat(roll): roll to ToT Playwright (roll/03-03-23)

src/data/ambassadors.tsx
=> updating my country

dotnet/docs/api/class-framelocator.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/locators.mdx, java/docs/api/class-framelocator.mdx, java/docs/api/class-locator.mdx, java/docs/locators.mdx, nodejs/docs/api/class-framelocator.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/locators.mdx, nodejs/docs/test-global-setup-teardown.mdx, nodejs/docs/test-reporters.mdx, python/docs/api/class-framelocator.mdx, python/docs/api/class-locator.mdx, python/docs/locators.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/0ebe090b8c6ec596f45fed8645f73a942dad92b0
=> feat(roll): roll to ToT Playwright (roll/04-03-23)

src/data/conference-videos.tsx, src/data/release-videos.tsx
=> community: add videos

.github/workflows/roll.yml, package-lock.json, package.json
=> chore: update dependencies

dotnet/docs/browsers.mdx, dotnet/docs/debug.mdx, java/docs/browsers.mdx, java/docs/debug.mdx, nodejs/docs/api/class-genericassertions.mdx, nodejs/docs/browsers.mdx, nodejs/docs/debug.mdx, python/docs/browsers.mdx, python/docs/debug.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/a2490a8fc8413db5a86fe38dff2a05d5cb5f2b16
=> feat(roll): roll to ToT Playwright (roll/08-03-23)

nodejs/docs/test-api-testing.mdx, nodejs/docs/test-parameterize.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/c3b4820f1e1be659b5ced46bec5b031bf43947cc
=> feat(roll): roll to ToT Playwright (roll/10-03-23)

src/data/feature-videos.tsx
- added video
- removed speakers as it didn't make sense for these videos
=> community: add feature video

dotnet/docs/trace-viewer.mdx, java/docs/trace-viewer.mdx, nodejs/docs/trace-viewer-intro.mdx, nodejs/docs/trace-viewer.mdx, python/docs/trace-viewer.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/428ea665785c79449e00927511c8194d705f89e2
=> feat(roll): roll to ToT Playwright (roll/11-03-23)

dotnet/docs/api/class-locator.mdx, dotnet/docs/trace-viewer.mdx, java/docs/api/class-locator.mdx, java/docs/trace-viewer.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/trace-viewer.mdx, python/docs/api/class-locator.mdx, python/docs/trace-viewer.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/ec10308c1b0e324c6eed321b35c9c5c0bf3c2e73
=> feat(roll): roll to ToT Playwright (roll/14-03-23)

dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-elementhandle.mdx, dotnet/docs/api/class-filechooser.mdx, dotnet/docs/api/class-frame.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-page.mdx, java/docs/api/class-browsercontext.mdx, java/docs/api/class-elementhandle.mdx, java/docs/api/class-filechooser.mdx, java/docs/api/class-frame.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-page.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-elementhandle.mdx, nodejs/docs/api/class-filechooser.mdx, nodejs/docs/api/class-frame.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-testinfo.mdx, nodejs/docs/api/class-websocket.mdx, nodejs/docs/auth.mdx, nodejs/docs/best-practices.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-elementhandle.mdx, python/docs/api/class-filechooser.mdx, python/docs/api/class-frame.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/69a94ed04403568bc6ef31549ca33be28a126e6f
=> feat(roll): roll to ToT Playwright (roll/15-03-23)

dotnet/docs/api/class-tracing.mdx, java/docs/api/class-tracing.mdx, nodejs/docs/api/class-tracing.mdx, python/docs/api/class-tracing.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/c45d8749b06cbd8e376abe9c970b1cc871f2d721
=> feat(roll): roll to ToT Playwright (roll/16-03-23)

src/format_utils.js
https://github.com/microsoft/playwright/issues/21385
=> chore: drop JS code snippets

nodejs/docs/test-cli.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/f192a74c5d3c191f3ee3a6da9033f7bed83d5bd9
=> feat(roll): roll to ToT Playwright (roll/17-03-23)

nodejs/docs/test-projects.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/04fd5435db36eab18c9879bfdbf5c6345fccd785
=> feat(roll): roll to ToT Playwright (roll/21-03-23)

dotnet/docs/api/class-locator.mdx, dotnet/docs/other-locators.mdx, dotnet/docs/release-notes.mdx, java/docs/api/class-locator.mdx, java/docs/other-locators.mdx, java/docs/release-notes.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/other-locators.mdx, nodejs/docs/release-notes.mdx, python/docs/api/class-locator.mdx, python/docs/other-locators.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/3477c89f203574a2cd97b299cad1743221a46a43
=> feat(roll): roll to ToT Playwright (roll/23-03-23)

static/js/redirection.js
https://github.com/microsoft/playwright/issues/21683
=> chore: redirect CLI to browsers

java/docs/api/class-jshandle.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/86af908fa73db3d0cfa7d2856ac9c82364b5ab37
=> feat(roll): roll to ToT Playwright (roll/24-03-23)

src/data/release-videos.tsx
- add new video
- improve tags for this video and last video
=> community: add 1.32 release video

dotnet/docs/locators.mdx, java/docs/locators.mdx, nodejs/docs/locators.mdx, nodejs/docs/test-cli.mdx, nodejs/docs/test-projects.mdx, python/docs/locators.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/c3d7ffb7731e028d0c0cab6b778be25e326ea51b
=> feat(roll): roll to ToT Playwright (roll/25-03-23)

dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-dialog.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/other-locators.mdx, java/docs/api/class-browsercontext.mdx, java/docs/api/class-dialog.mdx, java/docs/api/class-page.mdx, java/docs/other-locators.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-dialog.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/other-locators.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-dialog.mdx, python/docs/api/class-page.mdx, python/docs/other-locators.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/7f1de6568c7c68be91a14b8c26409981388c80d2
=> feat(roll): roll to ToT Playwright (roll/29-03-23)

dotnet/docs/api/class-locatorassertions.mdx, java/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-testerror.mdx, nodejs/docs/writing-tests.mdx, python/docs/api/class-locatorassertions.mdx, src/markdown.js
Upstream commit: https://github.com/microsoft/playwright/commit/896a03e7763b10eb7008f5b4aeb7d4575b95740c
=> feat(roll): roll to ToT Playwright (roll/30-03-23)

dotnet/docs/api/class-frame.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/trace-viewer.mdx, java/docs/api/class-frame.mdx, java/docs/api/class-page.mdx, java/docs/trace-viewer.mdx, nodejs/docs/api/class-electronapplication.mdx, nodejs/docs/api/class-frame.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-testoptions.mdx, nodejs/docs/test-cli.mdx, nodejs/docs/test-parallel.mdx, nodejs/docs/trace-viewer.mdx, python/docs/api/class-frame.mdx, python/docs/api/class-page.mdx, python/docs/trace-viewer.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/41e4ca0257351381e1e03e298ad656cd01f22521
=> feat(roll): roll to ToT Playwright (roll/01-04-23)

dotnet/docs/api/class-websocket.mdx, nodejs/docs/api/class-websocket.mdx, python/docs/api/class-websocket.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/87acda74ff0870c86b303eaa0955b50e8eb6d5ac
=> feat(roll): roll to ToT Playwright (roll/04-04-23)

dotnet/docs/api/class-frame.mdx, dotnet/docs/api/class-framelocator.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/api/class-request.mdx, dotnet/docs/locators.mdx, dotnet/docs/other-locators.mdx, java/docs/api/class-frame.mdx, java/docs/api/class-framelocator.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-page.mdx, java/docs/api/class-request.mdx, java/docs/locators.mdx, java/docs/other-locators.mdx, nodejs/docs/api/class-frame.mdx, nodejs/docs/api/class-framelocator.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-request.mdx, nodejs/docs/locators.mdx, nodejs/docs/other-locators.mdx, python/docs/api/class-frame.mdx, python/docs/api/class-framelocator.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-page.mdx, python/docs/api/class-request.mdx, python/docs/locators.mdx, python/docs/other-locators.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/f610577a1884f621bf6eede4a1fa0175175b4021
=> feat(roll): roll to ToT Playwright (roll/06-04-23)

dotnet/docs/api/class-frame.mdx, dotnet/docs/api/class-page.mdx, java/docs/api/class-frame.mdx, java/docs/api/class-page.mdx, nodejs/docs/api/class-frame.mdx, nodejs/docs/api/class-page.mdx, python/docs/api/class-frame.mdx, python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/1ea9f02944a66aa16325c598addbaf0b40e8eca2
=> feat(roll): roll to ToT Playwright (roll/07-04-23)

nodejs/docs/api/class-consolemessage.mdx, nodejs/docs/api/class-test.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/5cd9f83c7b3d2532cf6fb948efe50acd39afe8c6
=> feat(roll): roll to ToT Playwright (roll/08-04-23)

nodejs/docs/api-testing.mdx, nodejs/docs/release-notes.mdx, nodejs/sidebars.js
Upstream commit: https://github.com/microsoft/playwright/commit/56dcab844a5af2f73ca13030ec784820180052c4
=> feat(roll): roll to ToT Playwright (roll/12-04-23)

dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, java/docs/ci.mdx, java/docs/docker.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/test-snapshots.mdx, python/docs/ci.mdx, python/docs/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/90182a319dd1d5cb9eee73be51724bd0b12f73c6
=> feat(roll): roll to ToT Playwright (roll/13-04-23)

dotnet/docs/api/class-browser.mdx, dotnet/docs/api/class-browsertype.mdx, dotnet/docs/emulation.mdx, java/docs/api/class-browser.mdx, java/docs/api/class-browsertype.mdx, java/docs/emulation.mdx, nodejs/docs/api/class-androiddevice.mdx, nodejs/docs/api/class-browser.mdx, nodejs/docs/api/class-browsertype.mdx, nodejs/docs/api/class-electron.mdx, nodejs/docs/api/class-testoptions.mdx, nodejs/docs/emulation.mdx, nodejs/docs/test-reporters.mdx, python/docs/api/class-browser.mdx, python/docs/api/class-browsertype.mdx, python/docs/emulation.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/49c9284bc7d173c29957cf22302d9e52b064ba95
=> feat(roll): roll to ToT Playwright (roll/19-04-23)

dotnet/docs/api/class-route.mdx, java/docs/api/class-route.mdx, nodejs/docs/api/class-route.mdx, python/docs/api/class-route.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/b45e3556e530b3d16eae205f2ea689d8d0d309a2
=> feat(roll): roll to ToT Playwright (roll/21-04-23)

src/data/feature-videos.tsx, src/data/live-streams.tsx
=> docs: add new videos to community page

nodejs/sidebars.js
=> docs: add ui mode to sidebar

static/js/redirection.js
Merge after 1.33 release.
https://github.com/microsoft/playwright.dev/issues/1010
=> docs: redirect api testing to new home

dotnet/docs/trace-viewer-intro.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/auth.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-webserver.mdx, python/docs/test-runners.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/5043648762d7f5099b320671c2b45da5f7db2c4c
=> feat(roll): roll to ToT Playwright (roll/27-04-23)

nodejs/docs/api/class-testproject.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/a01df2ff5b33932f8f76eb9eabc78f89c3e436d1
=> feat(roll): roll to ToT Playwright (roll/29-04-23)

dotnet/versioned_docs/version-stable/release-notes.mdx, java/versioned_docs/version-stable/release-notes.mdx, nodejs/versioned_docs/version-stable/release-notes.mdx, python/versioned_docs/version-stable/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/1aabc97379ddcfc3b4603ee7db0400251b6a080e
=> feat(roll): roll to 1.33 Playwright

dotnet/docs/release-notes.mdx, java/docs/release-notes.mdx, nodejs/docs/release-notes.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/10ce7af411edf5c31a4e81fd0f96bfde47de8c24
=> feat(roll): roll to ToT Playwright (roll/03-05-23)

dotnet/docs/release-notes.mdx, java/docs/release-notes.mdx, nodejs/docs/release-notes.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/78203bf48d34d3cb19fe14ef0c3916bf3ef8265f
=> feat(roll): roll to ToT Playwright (roll/04-05-23)

dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-consolemessage.mdx, dotnet/docs/api/class-dialog.mdx, dotnet/docs/api/class-page.mdx, java/docs/api/class-browsercontext.mdx, java/docs/api/class-consolemessage.mdx, java/docs/api/class-dialog.mdx, java/docs/api/class-page.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-consolemessage.mdx, nodejs/docs/api/class-dialog.mdx, nodejs/docs/api/class-page.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-consolemessage.mdx, python/docs/api/class-dialog.mdx, python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/236c329ea9eaf5fa2a9bb2b586c7061e2a501989
=> feat(roll): roll to ToT Playwright (roll/05-05-23)

dotnet/docs/api/class-locator.mdx, dotnet/docs/locators.mdx, java/docs/api/class-locator.mdx, java/docs/locators.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/locators.mdx, python/docs/api/class-locator.mdx, python/docs/locators.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/21ffa0b6ad43c02ebe9039d83cfae89c4982068e
=> feat(roll): roll to ToT Playwright (roll/06-05-23)

dotnet/docs/ci.mdx, java/docs/ci.mdx, nodejs/docs/ci.mdx, nodejs/docs/test-parallel.mdx, nodejs/docs/test-reporters.mdx, python/docs/ci.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/2704601d0cb9b1e40aa66c2bd3715f315f48306a
=> feat(roll): roll to ToT Playwright (roll/09-05-23)

dotnet/docs/navigations.mdx, java/docs/navigations.mdx, nodejs/docs/navigations.mdx, nodejs/docs/test-annotations.mdx, nodejs/docs/test-fixtures.mdx, nodejs/docs/test-typescript.mdx, python/docs/navigations.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/154120648207db780f6f26e0458957d3dc7a20e4
=> feat(roll): roll to ToT Playwright (roll/10-05-23)

src/theme/Details/index.js, src/theme/Details/styles.module.css
Entirely generated except the "Playwright changes" block.
https://github.com/microsoft/playwright/issues/21597
=> chore: make details less prominent

dotnet/docs/api/class-frame.mdx, dotnet/docs/navigations.mdx, java/docs/api/class-frame.mdx, java/docs/navigations.mdx, nodejs/docs/api/class-frame.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/api/class-testproject.mdx, nodejs/docs/navigations.mdx, nodejs/docs/test-timeouts.mdx, python/docs/api/class-frame.mdx, python/docs/navigations.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/e6d8cf9693668e4eb82360551953bda35096aab5
=> feat(roll): roll to ToT Playwright (roll/12-05-23)

dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-page.mdx, java/docs/api/class-browsercontext.mdx, java/docs/api/class-page.mdx, nodejs/docs/api/class-browser.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-pageassertions.mdx, nodejs/docs/api/class-testoptions.mdx, python/docs/api/class-browser.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/c9d5b05440bdca7346cf181427c1d99f188bb1e5
=> feat(roll): roll to ToT Playwright (roll/13-05-23)

nodejs/docs/auth.mdx, python/docs/api/class-route.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/17ab777db5ae8b24c6654e1c8ecb0b9672538c86
=> feat(roll): roll to ToT Playwright (roll/15-05-23)

src/data/ambassadors.tsx, src/data/conference-videos.tsx, src/data/live-streams.tsx
=> community: add videos, fix image

dotnet/docs/troubleshooting.mdx, java/docs/troubleshooting.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/api/class-testproject.mdx, nodejs/docs/emulation.mdx, nodejs/docs/test-assertions.mdx, nodejs/docs/test-configuration.mdx, nodejs/docs/test-use-options.mdx, nodejs/docs/test-webserver.mdx, nodejs/docs/troubleshooting.mdx, python/docs/troubleshooting.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/2e5ddd4361fa50d06b07c32ff42fbdef79d84a8b
=> feat(roll): roll to ToT Playwright (roll/17-05-23)

dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-snapshots.mdx, python/docs/ci.mdx, python/docs/docker.mdx, python/docs/test-assertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/28504f6dc7ffbd920244365c6f890410f1a5d9a1
=> feat(roll): roll to ToT Playwright (roll/18-05-23)

nodejs/docs/release-notes.mdx, nodejs/docs/test-assertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/33f3a6002d0e3ffd34f469836da5480d2820aedc
=> feat(roll): roll to ToT Playwright (roll/20-05-23)

dotnet/docs/release-notes.mdx, java/docs/intro.mdx, java/docs/release-notes.mdx, java/docs/threading.mdx, nodejs/docs/library.mdx, nodejs/docs/puppeteer.mdx, python/docs/api/class-playwright.mdx, python/docs/library.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/342bae6c5924b5201d2cd8139eccfb728694c28a
=> feat(roll): roll to ToT Playwright (roll/25-05-23)

dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-consolemessage.mdx, dotnet/docs/api/class-dialog.mdx, dotnet/docs/api/class-locator.mdx, java/docs/api/class-browsercontext.mdx, java/docs/api/class-consolemessage.mdx, java/docs/api/class-dialog.mdx, java/docs/api/class-locator.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-consolemessage.mdx, nodejs/docs/api/class-dialog.mdx, nodejs/docs/api/class-locator.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-consolemessage.mdx, python/docs/api/class-dialog.mdx, python/docs/api/class-locator.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/ec972fb7c140908560347ea215d30016fda2508d
=> feat(roll): roll to ToT Playwright (roll/27-05-23)

dotnet/docs/api/class-apirequest.mdx, dotnet/docs/api/class-browser.mdx, dotnet/docs/api/class-browsertype.mdx, dotnet/docs/api/class-locatorassertions.mdx, dotnet/docs/api/class-pageassertions.mdx, java/docs/api/class-apirequest.mdx, java/docs/api/class-browser.mdx, java/docs/api/class-browsertype.mdx, java/docs/api/class-locatorassertions.mdx, java/docs/api/class-pageassertions.mdx, nodejs/docs/api/class-androiddevice.mdx, nodejs/docs/api/class-apirequest.mdx, nodejs/docs/api/class-browser.mdx, nodejs/docs/api/class-browsertype.mdx, nodejs/docs/api/class-electron.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-pageassertions.mdx, nodejs/docs/api/class-testoptions.mdx, nodejs/docs/release-notes.mdx, python/docs/api/class-apirequest.mdx, python/docs/api/class-browser.mdx, python/docs/api/class-browsertype.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-locatorassertions.mdx, python/docs/api/class-pageassertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/658b1dfea382c28dda1cbf1ca919a4f22a62b9f6
=> feat(roll): roll to ToT Playwright (roll/31-05-23)

dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/test-snapshots.mdx, python/docs/ci.mdx, python/docs/docker.mdx, src/generate.js, src/generator.js
https://github.com/microsoft/playwright/issues/23395
=> chore: use live versions for docs

src/data/live-streams.tsx, src/data/release-videos.tsx
add latest release video and playwright live stream to community pages
=> community: add release video and live stream

dotnet/docs/api/class-elementhandle.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/browsers.mdx, java/docs/api/class-elementhandle.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-page.mdx, java/docs/browsers.mdx, nodejs/docs/api/class-elementhandle.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-pageassertions.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/best-practices.mdx, nodejs/docs/browsers.mdx, nodejs/docs/test-assertions.mdx, nodejs/docs/test-ui-mode.mdx, nodejs/docs/test-webserver.mdx, python/docs/api/class-elementhandle.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-page.mdx, python/docs/browsers.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/7d2201561f743da83899ffda366f803fc1020b47
=> feat(roll): roll to ToT Playwright (roll/07-06-23)

dotnet/docs/selenium-grid.mdx, java/docs/selenium-grid.mdx, nodejs/docs/auth.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/selenium-grid.mdx, nodejs/docs/test-snapshots.mdx, nodejs/docs/test-ui-mode.mdx, python/docs/selenium-grid.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/c242dfac4c4ab73af950c74db6176a3c17d75f11
=> feat(roll): roll to ToT Playwright (roll/09-06-23)

nodejs/versioned_docs/version-stable/test-global-setup-teardown.mdx, nodejs/versioned_docs/version-stable/test-projects.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/615e2e8fa80ff3ba7f10c34df397d21749b086bb
=> feat(roll): roll to 1.35 Playwright

nodejs/docs/test-global-setup-teardown.mdx, nodejs/docs/test-projects.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/dd9a49690b2d93da2a068a53ea891896810caafb
=> feat(roll): roll to ToT Playwright (roll/10-06-23)

dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, dotnet/docs/release-notes.mdx, java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, java/docs/release-notes.mdx, python/docs/ci.mdx, python/docs/docker.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/ea7e9822aa90f7fe83aa65ded29875a8464ae3b7
=> feat(roll): roll to ToT Playwright (roll/13-06-23)

dotnet/docs/library.mdx, dotnet/docs/release-notes.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/5b2e8a6a7a80c161fa26f62e86eeb732908b7183
=> feat(roll): roll to ToT Playwright (roll/14-06-23)

nodejs/docs/auth.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/test-snapshots.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/fc8f0101c8890e1932a7bbe5494be085f9daa9d3
=> feat(roll): roll to ToT Playwright (roll/16-06-23)

python/docs/intro.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/f6d86c20f3195b6da8035e747ce25d92cfaed753
=> feat(roll): roll to ToT Playwright (roll/17-06-23)

dotnet/docs/browsers.mdx, dotnet/docs/ci.mdx, java/docs/browsers.mdx, java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, nodejs/docs/api/class-testoptions.mdx, nodejs/docs/browsers.mdx, nodejs/docs/ci.mdx, python/docs/browsers.mdx, python/docs/ci.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/b154ff11909ffc82f6bc26f79c6619da476a4fa6
=> feat(roll): roll to ToT Playwright (roll/22-06-23)

src/data/release-videos.tsx
- adds the release video to community release video page
=> community: add release video

nodejs/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/6f67f6b52b4c69afcbc68b9b5848d08c00dd8295
=> feat(roll): roll to ToT Playwright (roll/24-06-23)

dotnet/docs/mock.mdx, dotnet/docs/network.mdx, java/docs/mock.mdx, java/docs/network.mdx, nodejs/docs/api/class-testoptions.mdx, nodejs/docs/mock.mdx, nodejs/docs/network.mdx, nodejs/docs/protractor.mdx, nodejs/docs/service-workers-experimental-network-events.mdx, nodejs/docs/test-components.mdx, nodejs/docs/test-configuration.mdx, nodejs/docs/test-global-setup-teardown.mdx, nodejs/docs/test-projects.mdx, nodejs/docs/test-retries.mdx, python/docs/mock.mdx, python/docs/network.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/c6a0f3e8a0897d5b77b18f030a6b29c2390f1712
=> feat(roll): roll to ToT Playwright (roll/28-06-23)

dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, dotnet/docs/input.mdx, dotnet/docs/mock.mdx, dotnet/docs/other-locators.mdx, java/docs/input.mdx, java/docs/mock.mdx, java/docs/other-locators.mdx, java/docs/release-notes.mdx, nodejs/docs/api/class-electron.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/api/class-testproject.mdx, nodejs/docs/canary-releases.mdx, nodejs/docs/chrome-extensions.mdx, nodejs/docs/docker.mdx, nodejs/docs/input.mdx, nodejs/docs/mock.mdx, nodejs/docs/other-locators.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-components.mdx, nodejs/docs/test-snapshots.mdx, nodejs/docs/test-timeouts.mdx, nodejs/docs/test-typescript.mdx, python/docs/api/class-playwright.mdx, python/docs/input.mdx, python/docs/library.mdx, python/docs/mock.mdx, python/docs/other-locators.mdx, python/docs/release-notes.mdx, python/docs/test-runners.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/7e310f79af8732d40e41042d437623f632610509
=> feat(roll): roll to ToT Playwright (roll/01-07-23)

dotnet/docs/mock.mdx, java/docs/mock.mdx, nodejs/docs/mock.mdx, python/docs/mock.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/90c92c5724a25e1d9717908581abd35cc0410bde
=> feat(roll): roll to ToT Playwright (roll/07-07-23)

python/docs/emulation.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/37b3531a1181c99990899c15000925a98f035eb7
=> feat(roll): roll to ToT Playwright (roll/08-07-23)

nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/test-snapshots.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/778798804333cd16a357e03c2aa8657d5c564de4
=> feat(roll): roll to ToT Playwright (roll/13-07-23)

dotnet/docs/intro.mdx, java/docs/intro.mdx, nodejs/docs/intro.mdx, python/docs/intro.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/5d799606c323a60abdc8d7b5082b743a8b8fe08a
=> feat(roll): roll to ToT Playwright (roll/14-07-23)

dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, dotnet/docs/selenium-grid.mdx, java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, java/docs/selenium-grid.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/selenium-grid.mdx, nodejs/docs/test-snapshots.mdx, python/docs/ci.mdx, python/docs/docker.mdx, python/docs/selenium-grid.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/d92db9a513f4c397eb1898849c622a6f0dd2ba4e
=> feat(roll): roll to ToT Playwright (roll/15-07-23)

nodejs/docs/ci.mdx, nodejs/docs/test-ui-mode.mdx, python/docs/ci.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/9af0c6d822d379182ce1b6ac288f74f6d842ff25
=> feat(roll): roll to ToT Playwright (roll/19-07-23)

dotnet/docs/ci.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/aa39f39bda52a35ca16d791e8d2a0bd57308c9b1
=> feat(roll): roll to ToT Playwright (roll/21-07-23)

nodejs/docs/test-annotations.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/f453a17edee93fdb048cffcb4aa7c4be6912143e
=> feat(roll): roll to ToT Playwright (roll/22-07-23)

src/generator.js
=> chore: add ini code blocks

dotnet/docs/api/class-locator.mdx, dotnet/docs/codegen.mdx, dotnet/docs/locators.mdx, java/docs/api/class-locator.mdx, java/docs/codegen.mdx, java/docs/locators.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/ci.mdx, nodejs/docs/codegen.mdx, nodejs/docs/docker.mdx, nodejs/docs/locators.mdx, nodejs/docs/test-annotations.mdx, nodejs/docs/test-snapshots.mdx, python/docs/api/class-locator.mdx, python/docs/codegen.mdx, python/docs/locators.mdx, python/docs/test-runners.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/5c41c6e79923d9cb0953fd51d4a37ee0f20e06af
=> feat(roll): roll to ToT Playwright (roll/25-07-23)

dotnet/docs/navigations.mdx, java/docs/navigations.mdx, nodejs/docs/navigations.mdx, python/docs/navigations.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/ed99ac7395267324ec56fa57ed4597b10502cdce
=> feat(roll): roll to ToT Playwright (roll/26-07-23)

nodejs/docs/api-testing.mdx, nodejs/docs/api/class-genericassertions.mdx, nodejs/docs/test-assertions.mdx, nodejs/docs/test-configuration.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/d92fe16b76272afb19e7af5a2496f7efce45441d
=> feat(roll): roll to ToT Playwright (roll/29-07-23)

nodejs/docs/test-assertions.mdx, nodejs/docs/test-sharding.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/578e8e01b76038b9605f3d6813701bd6cda33496
=> feat(roll): roll to ToT Playwright (roll/01-08-23)

dotnet/docs/api/class-locator.mdx, dotnet/docs/debug.mdx, dotnet/docs/input.mdx, dotnet/docs/locators.mdx, dotnet/docs/other-locators.mdx, java/docs/api/class-locator.mdx, java/docs/debug.mdx, java/docs/input.mdx, java/docs/locators.mdx, java/docs/other-locators.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/debug.mdx, nodejs/docs/input.mdx, nodejs/docs/locators.mdx, nodejs/docs/other-locators.mdx, nodejs/docs/puppeteer.mdx, nodejs/docs/writing-tests.mdx, python/docs/api/class-locator.mdx, python/docs/debug.mdx, python/docs/input.mdx, python/docs/locators.mdx, python/docs/other-locators.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/120de62798d8108bc626601033b97fc90a6dac78
=> feat(roll): roll to ToT Playwright (roll/05-08-23)

nodejs/docs/api/class-testconfig.mdx, nodejs/docs/api/class-testproject.mdx, nodejs/docs/test-cli.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/0e20d352cfbc0b44196d91edc9c036c96656de5d
=> feat(roll): roll to ToT Playwright (roll/08-08-23)

nodejs/docs/ci.mdx, nodejs/docs/test-sharding.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/a61431f6bbaa44038829132eabb1766f7227c1ba
=> feat(roll): roll to ToT Playwright (roll/09-08-23)

nodejs/docs/test-sharding.mdx, python/docs/intro.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/d44a12701498ecea78d001df2ecfd65fcbd139a5
=> feat(roll): roll to ToT Playwright (roll/10-08-23)

dotnet/docs/api/class-download.mdx, dotnet/docs/api/class-elementhandle.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/downloads.mdx, java/docs/api/class-download.mdx, java/docs/api/class-elementhandle.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-page.mdx, java/docs/downloads.mdx, nodejs/docs/api/class-download.mdx, nodejs/docs/api/class-elementhandle.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-testoptions.mdx, nodejs/docs/auth.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/downloads.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-projects.mdx, nodejs/docs/test-snapshots.mdx, python/docs/api/class-download.mdx, python/docs/api/class-elementhandle.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-page.mdx, python/docs/downloads.mdx, src/api_parser.js
Upstream commit: https://github.com/microsoft/playwright/commit/b899d61a516f2a2018c4218d728a732e28611a38
=> feat(roll): roll to ToT Playwright (roll/11-08-23)

src/data/release-videos.tsx
=> chore: add 1.37 video to release-videos page

common/links-java.md, java/sidebars.js
=> docs: add CDPSession to java sidebar, linkify JsonObject

nodejs/docs/test-reporters.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/d849c7c81d8728c034c045b4a3ae8845bc4a19b4
=> feat(roll): roll to ToT Playwright (roll/14-08-23)

dotnet/versioned_docs/version-stable/release-notes.mdx, java/versioned_docs/version-stable/release-notes.mdx, nodejs/versioned_docs/version-stable/release-notes.mdx, nodejs/versioned_docs/version-stable/test-sharding.mdx, python/versioned_docs/version-stable/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/ca975a92ebf6d05ddc834dc384ae0bff2b92a688
=> feat(roll): roll to 1.37 Playwright

dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, dotnet/docs/release-notes.mdx, java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, java/docs/release-notes.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-sharding.mdx, python/docs/ci.mdx, python/docs/docker.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/6e51b95e2c15e714b98ec0f6dfeedcb6613a58cc
=> feat(roll): roll to ToT Playwright (roll/15-08-23)

dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, java/docs/test-runners.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/d2165f3e2deb3dae0a79a23311248f41f93de64f
=> feat(roll): roll to ToT Playwright (roll/16-08-23)

nodejs/docs/test-reporters.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/8f31191637bca917b90a15e589b5734aa379fa41
=> feat(roll): roll to ToT Playwright (roll/19-08-23)

java/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/e2a11bed190e723b10116238da5bd02cbae04f3e
=> feat(roll): roll to ToT Playwright (roll/20-08-23)

nodejs/docs/api/class-genericassertions.mdx, nodejs/docs/api/class-test.mdx, nodejs/docs/api/class-testinfo.mdx, nodejs/docs/puppeteer.mdx, nodejs/docs/test-retries.mdx, nodejs/docs/test-sharding.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/1ceaa923ea8169ba80f8eacb86a15c8a261c2aba
=> feat(roll): roll to ToT Playwright (roll/22-08-23)

dotnet/docs/api/class-elementhandle.mdx, dotnet/docs/api/class-frame.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/api/class-request.mdx, dotnet/docs/input.mdx, java/docs/api/class-elementhandle.mdx, java/docs/api/class-frame.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-page.mdx, java/docs/api/class-request.mdx, java/docs/input.mdx, java/docs/test-runners.mdx, nodejs/docs/api/class-elementhandle.mdx, nodejs/docs/api/class-filechooser.mdx, nodejs/docs/api/class-frame.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-request.mdx, nodejs/docs/browsers.mdx, nodejs/docs/chrome-extensions.mdx, nodejs/docs/input.mdx, nodejs/docs/library.mdx, python/docs/api/class-elementhandle.mdx, python/docs/api/class-frame.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-page.mdx, python/docs/api/class-request.mdx, python/docs/input.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/cfa8206a93e404171790d566fd815a5c8d6fa79d
=> feat(roll): roll to ToT Playwright (roll/23-08-23)

dotnet/docs/api/class-pageerror.mdx, java/docs/api/class-pageerror.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/697429d2225fefa205424bc3144a77d69f5e094f
=> feat(roll): roll to ToT Playwright (roll/24-08-23)

.github/workflows/azure-static-web-apps-delightful-forest-0a29f6210.yml, .github/workflows/create_release.yml, .github/workflows/roll.yml
=> devops: update GitHub Action workflows

nodejs/docs/test-retries.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/8c494e25191a2da940afe1dabde920a78b94cbb4
=> feat(roll): roll to ToT Playwright (roll/02-09-23)

nodejs/docs/chrome-extensions.mdx, nodejs/docs/test-typescript.mdx, python/docs/chrome-extensions.mdx, python/docs/evaluating.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/e0db46ae145f9f838467e2534b8d58928688fd82
=> feat(roll): roll to ToT Playwright (roll/06-09-23)

dotnet/sidebars.js, java/sidebars.js, python/sidebars.js
- add ci intro to sidebar for missing langs
=> docs: update sidebar to add ci intro

python/docs/running-tests.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/99047cba038987fc9d6ade7df1326d8a674e9438
=> feat(roll): roll to ToT Playwright (roll/08-09-23)

nodejs/docs/release-notes.mdx, nodejs/docs/writing-tests.mdx, python/docs/intro.mdx, python/docs/writing-tests.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/80b9e0283708997753e4f495ad638eb36d016914
=> feat(roll): roll to ToT Playwright (roll/09-09-23)

nodejs/docs/api/class-reporter.mdx, nodejs/docs/intro.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/466088215e7c81c1ed4dd3e50e7d6edab4ef4e45
=> feat(roll): roll to ToT Playwright (roll/12-09-23)

nodejs/docs/api/class-reporter.mdx, nodejs/docs/running-tests.mdx, nodejs/docs/test-ui-mode.mdx, python/docs/running-tests.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/3203b6c31f59354ee4bfb9b934a23c328942b7ac
=> feat(roll): roll to ToT Playwright (roll/13-09-23)

nodejs/docs/ci-intro.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-snapshots.mdx, python/docs/api/class-browser.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-browsertype.mdx, python/docs/api/class-dialog.mdx, python/docs/api/class-frame.mdx, python/docs/api/class-page.mdx, python/docs/api/class-playwright.mdx, python/docs/api/class-selectors.mdx, python/docs/api/class-timeouterror.mdx, python/docs/browser-contexts.mdx, python/docs/chrome-extensions.mdx, python/docs/emulation.mdx, python/docs/network.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/f9298cfff6c652b53a3f928b9c5e68f229057ee8
=> feat(roll): roll to ToT Playwright (roll/14-09-23)

dotnet/docs/api/class-elementhandle.mdx, dotnet/docs/api/class-frame.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/browser-contexts.mdx, dotnet/docs/input.mdx, java/docs/api/class-elementhandle.mdx, java/docs/api/class-frame.mdx, java/docs/api/class-page.mdx, java/docs/browser-contexts.mdx, java/docs/input.mdx, nodejs/docs/api/class-elementhandle.mdx, nodejs/docs/api/class-frame.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-snapshotassertions.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/api/class-testinfo.mdx, nodejs/docs/api/class-testproject.mdx, nodejs/docs/browser-contexts.mdx, nodejs/docs/input.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-assertions.mdx, nodejs/docs/test-configuration.mdx, nodejs/docs/test-snapshots.mdx, python/docs/api/class-elementhandle.mdx, python/docs/api/class-frame.mdx, python/docs/api/class-page.mdx, python/docs/browser-contexts.mdx, python/docs/input.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/ebf6a082903d3b7b952d0db87a581ce0d0272466
=> feat(roll): roll to ToT Playwright (roll/15-09-23)

dotnet/docs/codegen-intro.mdx, dotnet/docs/running-tests.mdx, java/docs/codegen-intro.mdx, java/docs/running-tests.mdx, nodejs/docs/codegen-intro.mdx, nodejs/docs/running-tests.mdx, nodejs/docs/test-ui-mode.mdx, python/docs/codegen-intro.mdx, python/docs/running-tests.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/3bcf9687e6505c4145510c9f1c637646a31ed55e
=> feat(roll): roll to ToT Playwright (roll/16-09-23)

dotnet/docs/release-notes.mdx, java/docs/release-notes.mdx, nodejs/docs/intro.mdx, python/docs/ci-intro.mdx, python/docs/ci.mdx, python/docs/docker.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/f064fb68404ee021f91de3cb460d2dda6bdce45b
=> feat(roll): roll to ToT Playwright (roll/19-09-23)

dotnet/versioned_docs/version-stable/ci-intro.mdx, dotnet/versioned_docs/version-stable/ci.mdx, dotnet/versioned_docs/version-stable/docker.mdx, dotnet/versioned_docs/version-stable/release-notes.mdx, java/versioned_docs/version-stable/ci-intro.mdx, java/versioned_docs/version-stable/ci.mdx, java/versioned_docs/version-stable/docker.mdx, java/versioned_docs/version-stable/intro.mdx, java/versioned_docs/version-stable/release-notes.mdx, java/versioned_docs/version-stable/test-runners.mdx, nodejs/versioned_docs/version-stable/api/class-snapshotassertions.mdx, nodejs/versioned_docs/version-stable/api/class-testconfig.mdx, nodejs/versioned_docs/version-stable/api/class-testinfo.mdx, nodejs/versioned_docs/version-stable/api/class-testproject.mdx, nodejs/versioned_docs/version-stable/release-notes.mdx, nodejs/versioned_docs/version-stable/test-assertions.mdx, nodejs/versioned_docs/version-stable/test-configuration.mdx, nodejs/versioned_docs/version-stable/test-snapshots.mdx, python/versioned_docs/version-stable/ci-intro.mdx, python/versioned_docs/version-stable/ci.mdx, python/versioned_docs/version-stable/docker.mdx, python/versioned_docs/version-stable/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/35d8604f8d1ad4715d6774ff0228a62d23f22ea7
=> feat(roll): roll to 1.38 Playwright

dotnet/docs/ci-intro.mdx, dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, java/docs/ci-intro.mdx, java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, java/docs/test-runners.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/2af7d672efeef92ca45577b2c3eeef3de6edb40f
=> feat(roll): roll to ToT Playwright (roll/20-09-23)

dotnet/docs/ci-intro.mdx, java/docs/ci-intro.mdx, nodejs/docs/ci-intro.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/test-snapshots.mdx, python/docs/ci-intro.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/ccaec034d8ca7c140e13041412d1877a100a0997
=> feat(roll): roll to ToT Playwright (roll/22-09-23)

dotnet/docs/trace-viewer-intro.mdx, dotnet/docs/trace-viewer.mdx, java/docs/trace-viewer-intro.mdx, java/docs/trace-viewer.mdx, nodejs/docs/ci-intro.mdx, nodejs/docs/test-configuration.mdx, nodejs/docs/trace-viewer-intro.mdx, nodejs/docs/trace-viewer.mdx, python/docs/trace-viewer-intro.mdx, python/docs/trace-viewer.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/d6ec1ae3994f127e38b866a231a34efc6a4cac0d
=> feat(roll): roll to ToT Playwright (roll/23-09-23)

dotnet/docs/api/class-locatorassertions.mdx, dotnet/docs/locators.mdx, java/docs/api/class-locatorassertions.mdx, java/docs/locators.mdx, java/docs/screenshots.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/locators.mdx, python/docs/api/class-locatorassertions.mdx, python/docs/locators.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/c0dc2328aa042012a59370d3249d71b9631102b5
=> feat(roll): roll to ToT Playwright (roll/26-09-23)

nodejs/docs/best-practices.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/20f20e9fbae1ae50894de0b687d558c9d0243099
=> feat(roll): roll to ToT Playwright (roll/27-09-23)

dotnet/docs/extensibility.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/28924678397cb01001096fa4c2df0d4b46b73dc3
=> feat(roll): roll to ToT Playwright (roll/28-09-23)

nodejs/docs/intro.mdx, nodejs/docs/test-components.mdx, nodejs/docs/test-global-setup-teardown.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/b5a40a90c2d29445854b2a7d472f602eb770cc3d
=> feat(roll): roll to ToT Playwright (roll/03-10-23)

dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-weberror.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-page.mdx, java/docs/api/class-weberror.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-weberror.mdx, nodejs/docs/emulation.mdx, nodejs/docs/test-assertions.mdx, nodejs/docs/test-components.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-weberror.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/89e1f697386179eefe4817ca23d9cd7802ead8bf
=> feat(roll): roll to ToT Playwright (roll/05-10-23)

src/data/conference-videos.tsx, src/data/live-streams.tsx, src/data/release-videos.tsx
- add release video
- add new conf videos
- add live stream video
=> community: add new videos

nodejs/docs/test-reporters.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/e70b10ac2ec4fd405c89ad4a3589fbc1164837b1
=> feat(roll): roll to ToT Playwright (roll/08-10-23)

nodejs/docs/test-configuration.mdx, python/docs/test-runners.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/2407041090c5e662c33e6a0d66334f2906818cad
=> feat(roll): roll to ToT Playwright (roll/10-10-23)

dotnet/docs/release-notes.mdx, java/docs/release-notes.mdx, nodejs/docs/api/class-test.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-configuration.mdx, python/docs/intro.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/ebd0ff9422fb24bf7bdd651ae883b66792ecced9
=> feat(roll): roll to ToT Playwright (roll/11-10-23)

dotnet/docs/release-notes.mdx, java/docs/release-notes.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/ci-intro.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-configuration.mdx, nodejs/docs/test-snapshots.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/117f3f12986bc36c93a180f185eb2b3804495ebb
=> feat(roll): roll to ToT Playwright (roll/12-10-23)

dotnet/docs/ci-intro.mdx, dotnet/docs/ci.mdx, dotnet/docs/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/6b31b30df9edc4c0b64a89ed5c29222ee4dea5a0
=> feat(roll): roll to ToT Playwright (roll/16-10-23)

dotnet/docs/api/class-browser.mdx, dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-page.mdx, java/docs/api/class-browser.mdx, java/docs/api/class-browsercontext.mdx, java/docs/api/class-page.mdx, java/docs/ci-intro.mdx, java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, java/docs/test-runners.mdx, nodejs/docs/api/class-browser.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-page.mdx, python/docs/api/class-browser.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/a54dbfdadf82d5bc201f816a419604557a207611
=> feat(roll): roll to ToT Playwright (roll/17-10-23)

src/config/prismLight.js
=> chore: make more code snippets AAA compliant

dotnet/versioned_docs/version-stable/ci-intro.mdx, dotnet/versioned_docs/version-stable/ci.mdx, dotnet/versioned_docs/version-stable/docker.mdx, java/versioned_docs/version-stable/ci-intro.mdx, java/versioned_docs/version-stable/ci.mdx, java/versioned_docs/version-stable/docker.mdx, java/versioned_docs/version-stable/intro.mdx, java/versioned_docs/version-stable/test-runners.mdx, nodejs/versioned_docs/version-stable/test-timeouts.mdx, python/versioned_docs/version-stable/ci-intro.mdx, python/versioned_docs/version-stable/ci.mdx, python/versioned_docs/version-stable/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/2ee3aaa0f5d1500f576f40004b36bda3263be94b
=> feat(roll): roll to 1.39 Playwright

dotnet/docs/api/class-download.mdx, java/docs/api/class-download.mdx, nodejs/docs/api/class-download.mdx, nodejs/docs/intro.mdx, nodejs/docs/test-timeouts.mdx, python/docs/api/class-download.mdx, python/docs/ci-intro.mdx, python/docs/ci.mdx, python/docs/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/3aa147914c5eafdf5a4ecc61d791e4a7deb920d4
=> feat(roll): roll to ToT Playwright (roll/18-10-23)

dotnet/docs/test-runners.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/fe7847b126ce2059d02fbbbc1f632b04fdae3ef7
=> feat(roll): roll to ToT Playwright (roll/24-10-23)

src/documentation.js
Upstream commit: https://github.com/microsoft/playwright/commit/0bb9f7cdf7367185c89a24305ca21d0768e5d54f
=> feat(roll): roll to ToT Playwright (roll/25-10-23)

nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/getting-started-vscode.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/00d3b4bdc3178c03c9d402b4005089b45383aa96
=> feat(roll): roll to ToT Playwright (roll/26-10-23)

java/docs/intro.mdx, nodejs/docs/test-reporters.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/4d8dd55b908f365cc5f683e7806ea7345d9de4d9
=> feat(roll): roll to ToT Playwright (roll/27-10-23)

src/data/conference-videos.tsx
Adding new conference video in French
=> community: add new video

dotnet/docs/api/class-browsertype.mdx, java/docs/api/class-browsertype.mdx, nodejs/docs/api/class-browsertype.mdx, nodejs/docs/release-notes.mdx, python/docs/api/class-browsertype.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/462e70ab82fc309099b7b5d8d1c844d34fbbf5a3
=> feat(roll): roll to ToT Playwright (roll/28-10-23)

dotnet/docs/api/class-apirequestcontext.mdx, java/docs/api/class-apirequestcontext.mdx, nodejs/docs/api/class-apirequestcontext.mdx, python/docs/api/class-apirequestcontext.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/50342a0c9dda5cdb23afc1e5a9f75d5681838adb
=> feat(roll): roll to ToT Playwright (roll/02-11-23)

nodejs/docs/test-sharding.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/53a78a315e15820de82524810e2f77b156aca9da
=> feat(roll): roll to ToT Playwright (roll/04-11-23)

dotnet/docs/api/class-frame.mdx, dotnet/docs/api/class-framelocator.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/api/class-pageassertions.mdx, dotnet/docs/api/class-playwrightassertions.mdx, dotnet/docs/locators.mdx, dotnet/docs/other-locators.mdx, dotnet/docs/release-notes.mdx, dotnet/docs/writing-tests.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/19b0f5ccb38fb0dee6e04b44448a8a2a212ee393
=> feat(roll): roll to ToT Playwright (roll/07-11-23)

dotnet/docs/api/class-locatorassertions.mdx, java/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/ci.mdx, python/docs/api/class-locatorassertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/557f3afd74cf48a98ba01143f4516f9031626230
=> feat(roll): roll to ToT Playwright (roll/15-11-23)

dotnet/docs/input.mdx, dotnet/docs/release-notes.mdx, java/docs/input.mdx, java/docs/release-notes.mdx, nodejs/docs/input.mdx, nodejs/docs/release-notes.mdx, python/docs/input.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/8150b27413d1cd4606375eed626416edc0c45ef5
=> feat(roll): roll to ToT Playwright (roll/16-11-23)

dotnet/docs/release-notes.mdx, java/docs/release-notes.mdx, nodejs/docs/ci-intro.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-snapshots.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/11bf96fe98decb99a6abd08578b4d27c06e49cd9
=> feat(roll): roll to ToT Playwright (roll/17-11-23)

.gitignore, dotnet/docs/api/class-browser.mdx, dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-cdpsessionevent.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/api/class-websocket.mdx, dotnet/docs/api/class-worker.mdx, src/format_csharp.js
=> fix(dotnet): event handlers

dotnet/docs/browsers.mdx, java/docs/browsers.mdx, java/docs/ci-intro.mdx, java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, java/docs/test-runners.mdx, nodejs/docs/browsers.mdx, python/docs/browsers.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/5ef5e776f65b7d7abcec334333df84c722b2a6e9
=> feat(roll): roll to ToT Playwright (roll/21-11-23)

dotnet/docs/ci-intro.mdx, dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, dotnet/docs/release-notes.mdx, java/docs/release-notes.mdx, python/docs/api/class-locatorassertions.mdx, python/docs/ci-intro.mdx, python/docs/ci.mdx, python/docs/docker.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/91c5bac52b2002509933b7df0a062dddf58ae5ef
=> feat(roll): roll to ToT Playwright (roll/22-11-23)

dotnet/versioned_docs/version-stable/api/class-browser.mdx, dotnet/versioned_docs/version-stable/api/class-browsercontext.mdx, dotnet/versioned_docs/version-stable/api/class-cdpsessionevent.mdx, dotnet/versioned_docs/version-stable/api/class-page.mdx, dotnet/versioned_docs/version-stable/api/class-websocket.mdx, dotnet/versioned_docs/version-stable/api/class-worker.mdx, dotnet/versioned_docs/version-stable/ci-intro.mdx, dotnet/versioned_docs/version-stable/ci.mdx, dotnet/versioned_docs/version-stable/docker.mdx, dotnet/versioned_docs/version-stable/release-notes.mdx, java/versioned_docs/version-stable/ci-intro.mdx, java/versioned_docs/version-stable/ci.mdx, java/versioned_docs/version-stable/docker.mdx, java/versioned_docs/version-stable/intro.mdx, java/versioned_docs/version-stable/release-notes.mdx, java/versioned_docs/version-stable/test-runners.mdx, python/versioned_docs/version-stable/api/class-locatorassertions.mdx, python/versioned_docs/version-stable/ci-intro.mdx, python/versioned_docs/version-stable/ci.mdx, python/versioned_docs/version-stable/docker.mdx, python/versioned_docs/version-stable/release-notes.mdx, python/versioned_docs/version-stable/trace-viewer-intro.mdx, python/versioned_docs/version-stable/trace-viewer.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/480ae58942401b5e27e1eef47dac636923d2e77c
=> feat(roll): roll to 1.40 Playwright

nodejs/docs/test-cli.mdx, nodejs/docs/test-projects.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/958e45316e0df430967d8fbf02676b3c4241a54a
=> feat(roll): roll to ToT Playwright (roll/23-11-23)

src/data/release-videos.tsx
add v1.40 video to release videos
=> docs: add 1.40 release video

nodejs/docs/ci-intro.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/test-snapshots.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/1901a1a1555536e26beb74c77695a866b501f27f
=> feat(roll): roll to ToT Playwright (roll/29-11-23)

dotnet/docs/selenium-grid.mdx, java/docs/selenium-grid.mdx, nodejs/docs/selenium-grid.mdx, python/docs/selenium-grid.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/92a0d24069c2f43ecec89ac9528ff47577273b9d
=> feat(roll): roll to ToT Playwright (roll/30-11-23)

dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-page.mdx, java/docs/api/class-browsercontext.mdx, java/docs/api/class-page.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-testoptions.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/74e51d334e7bf7462ebce4330817b369d1a9b87e
=> feat(roll): roll to ToT Playwright (roll/05-12-23)

dotnet/docs/api/class-tracing.mdx, dotnet/docs/browser-contexts.mdx, dotnet/docs/trace-viewer-intro.mdx, dotnet/docs/trace-viewer.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/test-fixtures.mdx, nodejs/docs/test-reporters.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/411abdb7526596cd0b18a3986a0f80002388eefd
=> feat(roll): roll to ToT Playwright (roll/07-12-23)

dotnet/docs/api/class-frame.mdx, dotnet/docs/api/class-framelocator.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/locators.mdx, java/docs/api/class-frame.mdx, java/docs/api/class-framelocator.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-page.mdx, java/docs/locators.mdx, nodejs/docs/api/class-frame.mdx, nodejs/docs/api/class-framelocator.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/locators.mdx, nodejs/docs/test-cli.mdx, python/docs/api/class-frame.mdx, python/docs/api/class-framelocator.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-page.mdx, python/docs/locators.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/10dda30c7f417a92f782e21368fbb211a679838a
=> feat(roll): roll to ToT Playwright (roll/12-12-23)

src/generator.js
=> chore: include Dockerfile inside common code blocks

nodejs/docs/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/9b2585cd4ef802bc01d4183dd708e127cf62773a
=> feat(roll): roll to ToT Playwright (roll/13-12-23)

src/generator.js
=> chore: include css inside common code blocks

dotnet/docs/api/class-elementhandle.mdx, dotnet/docs/trace-viewer-intro.mdx, dotnet/docs/trace-viewer.mdx, java/docs/api/class-elementhandle.mdx, nodejs/docs/api/class-elementhandle.mdx, python/docs/api/class-elementhandle.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/ff3b70b6259c22a00886cec062b215f20bd7505a
=> feat(roll): roll to ToT Playwright (roll/14-12-23)

dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-browsertype.mdx, dotnet/docs/api/class-elementhandle.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-page.mdx, java/docs/api/class-browsercontext.mdx, java/docs/api/class-browsertype.mdx, java/docs/api/class-elementhandle.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-page.mdx, nodejs/docs/api/class-androiddevice.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-browsertype.mdx, nodejs/docs/api/class-elementhandle.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-pageassertions.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/api/class-testoptions.mdx, nodejs/docs/api/class-testproject.mdx, nodejs/docs/chrome-extensions.mdx, nodejs/docs/test-snapshots.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-browsertype.mdx, python/docs/api/class-elementhandle.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-page.mdx, python/docs/chrome-extensions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/256b2876490a2bd47d65638d38b1bb87a90e1059
=> feat(roll): roll to ToT Playwright (roll/15-12-23)

dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/ci-intro.mdx, dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, dotnet/docs/intro.mdx, dotnet/docs/library.mdx, dotnet/docs/webview2.mdx, java/docs/api/class-browsercontext.mdx, java/docs/api/class-page.mdx, java/docs/webview2.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/webview2.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-page.mdx, python/docs/webview2.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/576b3406e3bbf0957e87e8b0af6c884dd0db90da
=> feat(roll): roll to ToT Playwright (roll/16-12-23)

dotnet/docs/intro.mdx, java/docs/intro.mdx, nodejs/docs/intro.mdx, python/docs/intro.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/6b178d22e23d38a48fd9a805acef473c3a405b0e
=> feat(roll): roll to ToT Playwright (roll/19-12-23)

nodejs/docs/test-annotations.mdx, nodejs/docs/test-assertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/8161a7401f1d9f82ae221908912bf58918e16ff1
=> feat(roll): roll to ToT Playwright (roll/21-12-23)

dotnet/docs/api/class-tracing.mdx, java/docs/api/class-tracing.mdx, nodejs/docs/api/class-route.mdx, nodejs/docs/api/class-tracing.mdx, python/docs/api/class-tracing.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/ff99aa33b0ee6ebaeffcc098a9e52c2f6d995b2f
=> feat(roll): roll to ToT Playwright (roll/22-12-23)

nodejs/docs/ci.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/7bffff5790e28243a815c985135e908247b563db
=> feat(roll): roll to ToT Playwright (roll/01-01-24)

dotnet/docs/extensibility.mdx, java/docs/extensibility.mdx, nodejs/docs/extensibility.mdx, python/docs/extensibility.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/e30c0a6ff7c48a3abc55eab63fa15d31f6241280
=> feat(roll): roll to ToT Playwright (roll/04-01-24)

dotnet/docs/browsers.mdx, java/docs/browsers.mdx, nodejs/docs/browsers.mdx, nodejs/docs/test-sharding.mdx, python/docs/browsers.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/fad703d4eef4c1ecb9ae57c20e249b52589c6191
=> feat(roll): roll to ToT Playwright (roll/05-01-24)

dotnet/docs/api/class-locatorassertions.mdx, java/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-locatorassertions.mdx, python/docs/api/class-locatorassertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/1617779f3ec102c080306ccd379bffeeea937249
=> feat(roll): roll to ToT Playwright (roll/06-01-24)

python/docs/mock.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/a519af6830f9251b27923824c653addbc43e9232
=> feat(roll): roll to ToT Playwright (roll/09-01-24)

dotnet/docs/api/class-formdata.mdx, java/docs/api/class-formdata.mdx, nodejs/docs/api-testing.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/b392c2d39253051114139f988c1d4a23301d627c
=> feat(roll): roll to ToT Playwright (roll/12-01-24)

dotnet/docs/actionability.mdx, dotnet/docs/api/class-elementhandle.mdx, dotnet/docs/api/class-locatorassertions.mdx, dotnet/docs/release-notes.mdx, dotnet/docs/test-assertions.mdx, java/docs/actionability.mdx, java/docs/api/class-elementhandle.mdx, java/docs/api/class-locatorassertions.mdx, java/docs/release-notes.mdx, java/docs/test-assertions.mdx, nodejs/docs/actionability.mdx, nodejs/docs/api/class-elementhandle.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-parallel.mdx, python/docs/actionability.mdx, python/docs/api/class-elementhandle.mdx, python/docs/api/class-locatorassertions.mdx, python/docs/release-notes.mdx, python/docs/test-assertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/92ad1b385c7be5d952e4aa2a94a32d083ba5b9a3
=> feat(roll): roll to ToT Playwright (roll/13-01-24)

dotnet/docs/ci-intro.mdx, dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, java/docs/docker.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/api/class-testproject.mdx, nodejs/docs/ci-intro.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/emulation.mdx, python/docs/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/0fa85143a0053b00565d59db0501b592b1b340df
=> feat(roll): roll to ToT Playwright (roll/17-01-24)

dotnet/docs/ci-intro.mdx, dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, java/docs/ci-intro.mdx, java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, java/docs/test-runners.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/401094031544b79b323db942bcd5be2105f94a6e
=> feat(roll): roll to ToT Playwright (roll/19-01-24)

dotnet/versioned_docs/version-stable/ci-intro.mdx, dotnet/versioned_docs/version-stable/ci.mdx, dotnet/versioned_docs/version-stable/docker.mdx, java/versioned_docs/version-stable/ci-intro.mdx, java/versioned_docs/version-stable/ci.mdx, java/versioned_docs/version-stable/docker.mdx, java/versioned_docs/version-stable/intro.mdx, java/versioned_docs/version-stable/test-runners.mdx, nodejs/versioned_docs/version-stable/ci-intro.mdx, nodejs/versioned_docs/version-stable/ci.mdx, nodejs/versioned_docs/version-stable/docker.mdx, nodejs/versioned_docs/version-stable/test-snapshots.mdx, python/versioned_docs/version-stable/ci-intro.mdx, python/versioned_docs/version-stable/ci.mdx, python/versioned_docs/version-stable/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/8f0163f3f4cf573037b6697e15ab55a0dc910f57
Fixes https://github.com/microsoft/playwright/issues/29083
=> feat(roll): roll to 1.41 Playwright

src/format_csharp.js, src/format_java.js
=> fix: docs roll after upstream changes

dotnet/docs/api/class-page.mdx, java/docs/api/class-page.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/ci-intro.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/test-parameterize.mdx, python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/4b0e55abda3be870f17f35c6dc5db92db61c44d4
=> feat(roll): roll to ToT Playwright (roll/22-01-24)

nodejs/docs/api/class-test.mdx, nodejs/docs/api/class-testinfo.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/9b974e0026156f657824c03a61e81230f7fabb62
=> feat(roll): roll to ToT Playwright (roll/23-01-24)

dotnet/docs/mock.mdx, java/docs/mock.mdx, nodejs/docs/api/class-android.mdx, nodejs/docs/api/class-electron.mdx, nodejs/docs/intro.mdx, nodejs/docs/mock.mdx, nodejs/docs/test-global-setup-teardown.mdx, nodejs/docs/test-projects.mdx, python/docs/mock.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/0752f0202ff908367c57f2522742ea2a66a993f1
=> feat(roll): roll to ToT Playwright (roll/24-01-24)

dotnet/docs/ci-intro.mdx, dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, nodejs/docs/intro.mdx, python/docs/ci-intro.mdx, python/docs/ci.mdx, python/docs/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/f49426b0062156c8a983612eebe7f69cd7bb09d0
=> feat(roll): roll to ToT Playwright (roll/25-01-24)

dotnet/docs/ci.mdx, java/docs/ci-intro.mdx, java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, java/docs/test-runners.mdx, nodejs/docs/ci.mdx, python/docs/ci.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/82981a80919c4c30aee3accb06c07a2f8869c145
=> feat(roll): roll to ToT Playwright (roll/26-01-24)

dotnet/docs/api/class-elementhandle.mdx, dotnet/docs/api/class-frame.mdx, dotnet/docs/api/class-keyboard.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-page.mdx, java/docs/api/class-elementhandle.mdx, java/docs/api/class-frame.mdx, java/docs/api/class-keyboard.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-page.mdx, nodejs/docs/api/class-elementhandle.mdx, nodejs/docs/api/class-frame.mdx, nodejs/docs/api/class-keyboard.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/ci-intro.mdx, nodejs/docs/test-reporters.mdx, python/docs/api/class-elementhandle.mdx, python/docs/api/class-frame.mdx, python/docs/api/class-keyboard.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-page.mdx, python/docs/ci-intro.mdx, python/docs/mock.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/289127d523d7f49ca460f73fa65283f14d06b4de
=> feat(roll): roll to ToT Playwright (roll/30-01-24)

nodejs/docs/test-cli.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/aff6cf3c83d5567ec2c662eebdc246090df39982
=> feat(roll): roll to ToT Playwright (roll/31-01-24)

dotnet/docs/intro.mdx, dotnet/docs/library.mdx, dotnet/docs/test-assertions.mdx, dotnet/docs/writing-tests.mdx, python/docs/mock.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/7cb886ce074c2a83f331d91ac85c3134d51c136d
=> feat(roll): roll to ToT Playwright (roll/01-02-24)

nodejs/docs/release-notes.mdx, nodejs/docs/test-assertions.mdx, python/docs/test-assertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/9e285ce919139c7a2b94edf976c86fc1e2757d13
=> feat(roll): roll to ToT Playwright (roll/06-02-24)

dotnet/docs/api/class-page.mdx, java/docs/api/class-page.mdx, nodejs/docs/api/class-page.mdx, python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/7a86bf4af62fe3e44a41f94c7a4ab7f645c205e1
=> feat(roll): roll to ToT Playwright (roll/09-02-24)

nodejs/docs/test-fixtures.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/217c0618df68985249a282c31954ac5f39cc0b87
=> feat(roll): roll to ToT Playwright (roll/14-02-24)

dotnet/docs/api/class-route.mdx, dotnet/docs/other-locators.mdx, java/docs/api/class-page.mdx, java/docs/other-locators.mdx, nodejs/docs/api-testing.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/network.mdx, nodejs/docs/other-locators.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-webserver.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-page.mdx, python/docs/api/class-route.mdx, python/docs/network.mdx, python/docs/other-locators.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/edc1c13f3125bdc7266d5165d4b627d04e47ce80
=> feat(roll): roll to ToT Playwright (roll/15-02-24)

nodejs/docs/test-cli.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/f414227ed8fdeb2735c35a162bebe957cc2951f4
=> feat(roll): roll to ToT Playwright (roll/17-02-24)

src/data/ambassadors.tsx
Update my links in ambassadors page.
=> community: update ambassador links

nodejs/docs/auth.mdx, nodejs/docs/test-cli.mdx, nodejs/docs/test-reporters.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/a023cd1f5723b88e064a914449049b6b56842769
=> feat(roll): roll to ToT Playwright (roll/21-02-24)

python/docs/intro.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/e846afeb98d5609e6bf7d03353ee3577243d4455
=> feat(roll): roll to ToT Playwright (roll/22-02-24)

.github/workflows/azure-static-web-apps-delightful-forest-0a29f6210.yml
=> devops: fix deploy comments

nodejs/docs/ci-intro.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/8264bec01e778fa9787352a4158edcc10eb8b1f7
=> feat(roll): roll to ToT Playwright (roll/28-02-24)

nodejs/docs/api/class-testoptions.mdx, nodejs/docs/test-reporters.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/f4f26fdf7b5de707da1adbfe0387dad90d081b03
=> feat(roll): roll to ToT Playwright (roll/29-02-24)

dotnet/docs/api/class-page.mdx, java/docs/api/class-page.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/ci-intro.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/ef924c14e7edbf62d2fcb2a75f024aff8bf5b9f1
=> feat(roll): roll to ToT Playwright (roll/02-03-24)

dotnet/docs/api/class-browsercontext.mdx, java/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/test-configuration.mdx, nodejs/docs/test-snapshots.mdx, python/docs/api/class-browsercontext.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/d5d4f591f35970f48ffe82bfc5c9e117660d7f0f
=> feat(roll): roll to ToT Playwright (roll/03-03-24)

dotnet/docs/auth.mdx, dotnet/docs/release-notes.mdx, java/docs/auth.mdx, java/docs/release-notes.mdx, nodejs/docs/release-notes.mdx, python/docs/auth.mdx, python/docs/release-notes.mdx, python/docs/test-runners.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/a678561cda91cb1e7c15d0e23b404e9ad2537f99
=> feat(roll): roll to ToT Playwright (roll/06-03-24)

src/components/GitHubStarButton/index.css, src/pages/styles.module.css
https://github.com/microsoft/playwright.dev/issues/1260
=> fix: overflow of GitHub Stars count button

src/pages/styles.module.css
https://github.com/microsoft/playwright.dev/issues/1271
=> chore: remove logo hover animation

dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/dialogs.mdx, dotnet/docs/network.mdx, nodejs/docs/api/class-testinfo.mdx, python/docs/ci-intro.mdx, python/docs/ci.mdx, python/docs/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/006ee7f3b0a3b7beb3b882d4ff3262229c6c7707
=> feat(roll): roll to ToT Playwright (roll/07-03-24)

dotnet/docs/ci-intro.mdx, dotnet/docs/ci.mdx, dotnet/docs/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/8f2c372bd81cd7dc8ede73cd1b81179a30ec0728
=> feat(roll): roll to ToT Playwright (roll/08-03-24)

dotnet/versioned_docs/version-stable/ci-intro.mdx, dotnet/versioned_docs/version-stable/ci.mdx, dotnet/versioned_docs/version-stable/docker.mdx, java/versioned_docs/version-stable/accessibility-testing.mdx, java/versioned_docs/version-stable/api-testing.mdx, java/versioned_docs/version-stable/junit.mdx, java/versioned_docs/version-stable/test-runners.mdx, python/versioned_docs/version-stable/ci-intro.mdx, python/versioned_docs/version-stable/ci.mdx, python/versioned_docs/version-stable/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/e164ac769729126452ab05d77f44b597aeb913b3
=> feat(roll): roll to 1.42 Playwright

dotnet/docs/api/class-page.mdx, java/docs/api/class-page.mdx, java/docs/ci-intro.mdx, java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, java/docs/test-runners.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/auth.mdx, python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/349b25e61a4814c7a7fc6f9d3bef4c3fdf7d505c
=> feat(roll): roll to ToT Playwright (roll/13-03-24)

src/data/release-videos.tsx
=> docs: add release video

nodejs/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/94348bb3c5be35d002e3cf337119adddfede835f
=> feat(roll): roll to ToT Playwright (roll/15-03-24)

nodejs/docs/api/class-logger.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/306db80d035835335598b9fa0286a46e8e286efd
=> feat(roll): roll to ToT Playwright (roll/16-03-24)

dotnet/docs/api/class-page.mdx, java/docs/api/class-page.mdx, nodejs/docs/api/class-page.mdx, python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/da2b099b5c505b280aff338ff23dbea25dbd5e94
=> feat(roll): roll to ToT Playwright (roll/20-03-24)

dotnet/docs/api/class-browsertype.mdx, java/docs/api/class-browsertype.mdx, nodejs/docs/api/class-browsertype.mdx, python/docs/api/class-browsertype.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/7ad0a12c23ffc898f7f27150a62ac979692049bb
=> feat(roll): roll to ToT Playwright (roll/21-03-24)

dotnet/docs/api/class-elementhandle.mdx, dotnet/docs/api/class-framelocator.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/handles.mdx, dotnet/docs/locators.mdx, java/docs/api/class-elementhandle.mdx, java/docs/api/class-framelocator.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-page.mdx, java/docs/handles.mdx, java/docs/locators.mdx, nodejs/docs/accessibility-testing.mdx, nodejs/docs/api/class-elementhandle.mdx, nodejs/docs/api/class-framelocator.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-testoptions.mdx, nodejs/docs/ci-intro.mdx, nodejs/docs/handles.mdx, nodejs/docs/locators.mdx, nodejs/docs/test-sharding.mdx, python/docs/api/class-elementhandle.mdx, python/docs/api/class-framelocator.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-page.mdx, python/docs/ci-intro.mdx, python/docs/handles.mdx, python/docs/locators.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/05cbb14d280e428456c885bec50e21efa73e40aa
=> feat(roll): roll to ToT Playwright (roll/25-03-24)

dotnet/docs/api/class-apirequestcontext.mdx, dotnet/docs/api/class-formdata.mdx, java/docs/api/class-formdata.mdx, nodejs/docs/api/class-apirequestcontext.mdx, python/docs/api/class-apirequestcontext.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/397244c0268a3261ff44b0ce4ddac267d96f9eaf
=> feat(roll): roll to ToT Playwright (roll/26-03-24)

dotnet/docs/api/class-apirequestcontext.mdx, dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-formdata.mdx, java/docs/api/class-browsercontext.mdx, java/docs/api/class-formdata.mdx, nodejs/docs/api/class-apirequestcontext.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/mock-browser.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-projects.mdx, python/docs/api/class-apirequestcontext.mdx, python/docs/api/class-browsercontext.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/352609c44f35eb8fa43c2448ffa6afaf6088faf8
=> feat(roll): roll to ToT Playwright (roll/27-03-24)

nodejs/docs/api/class-suite.mdx, nodejs/docs/api/class-testcase.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/api/class-testproject.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/a950a7b86b3977e98ef9f2bcfc90817039e38808
=> feat(roll): roll to ToT Playwright (roll/30-03-24)

dotnet/docs/api/class-browsercontext.mdx, java/docs/api/class-browsercontext.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/6d56b453ff03b322be70f90c1079961face257a9
=> feat(roll): roll to ToT Playwright (roll/02-04-24)

dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-page.mdx, java/docs/api/class-browsercontext.mdx, java/docs/api/class-page.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/ci-intro.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/7ad255301f500c323030c2a67415a013e2cf0c35
=> feat(roll): roll to ToT Playwright (roll/05-04-24)

nodejs/docs/test-sharding.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/3e03c800df9fbf1d9ed1e7f580f3fad9efc26bd1
=> feat(roll): roll to ToT Playwright (roll/06-04-24)

nodejs/docs/test-components.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/1a34c85886bd5399517eda5537a0cafe6eb00350
=> feat(roll): roll to ToT Playwright (roll/08-04-24)

dotnet/docs/release-notes.mdx, java/docs/release-notes.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/108b250d86c5d13e0066c1b3632077d893900764
=> feat(roll): roll to ToT Playwright (roll/09-04-24)

dotnet/versioned_docs/version-stable/api/class-browsercontext.mdx, dotnet/versioned_docs/version-stable/release-notes.mdx, java/versioned_docs/version-stable/api/class-browsercontext.mdx, java/versioned_docs/version-stable/release-notes.mdx, python/versioned_docs/version-stable/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/53326391148545543b433e3e6d4e771f179b93a1
=> feat(roll): roll to 1.43 Playwright

dotnet/docs/ci-intro.mdx, dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, python/docs/ci-intro.mdx, python/docs/ci.mdx, python/docs/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/b2ded9fed1a66c13fb19a997808fb300219ec62c
=> feat(roll): roll to ToT Playwright (roll/10-04-24)

java/docs/ci-intro.mdx, java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, java/docs/test-runners.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/bff9f30b6f6fd971f7732fc87d6ce714f15b7d88
=> feat(roll): roll to ToT Playwright (roll/11-04-24)

dotnet/docs/mock.mdx, java/docs/mock.mdx, nodejs/docs/mock.mdx, python/docs/mock.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/1ef85015f3f389d7b968792a39bf6e0550cc1821
=> feat(roll): roll to ToT Playwright (roll/12-04-24)

nodejs/docs/ci-intro.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/c4418875d3e356a16a98f2e6aa7f9988fe7d184b
=> feat(roll): roll to ToT Playwright (roll/13-04-24)

dotnet/docs/auth.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/f7e612fb4bd98e8a2186f4723459e2f62e93fb3b
=> feat(roll): roll to ToT Playwright (roll/15-04-24)

nodejs/docs/test-ui-mode.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/e2c1efad9e076559d4dff0236df558aa34d997d1
=> feat(roll): roll to ToT Playwright (roll/16-04-24)

nodejs/docs/api/class-testconfig.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/82aefd24db1ba9977c3f6953347ee266845790ea
=> feat(roll): roll to ToT Playwright (roll/17-04-24)

dotnet/docs/api/class-locatorassertions.mdx, java/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-locatorassertions.mdx, python/docs/api/class-locatorassertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/8c181f7e2baa31853935afa8df0a7bdea5583c33
=> feat(roll): roll to ToT Playwright (roll/19-04-24)

dotnet/docs/api/class-locatorassertions.mdx, java/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-testproject.mdx, python/docs/api/class-locatorassertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/18dcd6adff488cc1d1fceec2c3f60ce16900901a
=> feat(roll): roll to ToT Playwright (roll/23-04-24)

dotnet/docs/api/class-page.mdx, java/docs/api/class-page.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/api/class-testproject.mdx, python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/a6f0a89169430ad70f945c44618db7ebda328ec3
=> feat(roll): roll to ToT Playwright (roll/25-04-24)

dotnet/docs/api/class-apirequestcontext.mdx, dotnet/docs/api/class-locatorassertions.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/test-assertions.mdx, java/docs/api/class-apirequestcontext.mdx, java/docs/api/class-locatorassertions.mdx, java/docs/api/class-page.mdx, java/docs/test-assertions.mdx, nodejs/docs/api/class-apirequestcontext.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/test-assertions.mdx, nodejs/docs/test-cli.mdx, nodejs/docs/test-reporters.mdx, python/docs/api/class-apirequestcontext.mdx, python/docs/api/class-locatorassertions.mdx, python/docs/api/class-page.mdx, python/docs/test-assertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/b5aca9fca8a721ee2c49b3434850d1473def4627
=> feat(roll): roll to ToT Playwright (roll/26-04-24)

dotnet/docs/api/class-pageassertions.mdx, java/docs/api/class-pageassertions.mdx, nodejs/docs/test-reporters.mdx, python/docs/api/class-pageassertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/1f63cbff08a11f6fad671824adfd4a0f283da29a
=> feat(roll): roll to ToT Playwright (roll/27-04-24)

dotnet/docs/api/class-elementhandle.mdx, dotnet/docs/api/class-frame.mdx, dotnet/docs/api/class-keyboard.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/input.mdx, java/docs/api/class-elementhandle.mdx, java/docs/api/class-frame.mdx, java/docs/api/class-keyboard.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-page.mdx, java/docs/input.mdx, nodejs/docs/api/class-elementhandle.mdx, nodejs/docs/api/class-frame.mdx, nodejs/docs/api/class-keyboard.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/input.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-reporters.mdx, python/docs/api/class-cdpsession.mdx, python/docs/api/class-elementhandle.mdx, python/docs/api/class-frame.mdx, python/docs/api/class-keyboard.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-page.mdx, python/docs/input.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/6c827121bf3f7a0c9492822000861f322840b583
=> feat(roll): roll to ToT Playwright (roll/30-04-24)

nodejs/docs/test-global-setup-teardown.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/c3d8b22198244a692eb059db47c7d80bc9eefed5
=> feat(roll): roll to ToT Playwright (roll/01-05-24)

nodejs/docs/intro.mdx, nodejs/docs/test-reporters.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/980f9c6ad45640da144a6c29edc826cd2a938d19
=> feat(roll): roll to ToT Playwright (roll/02-05-24)

src/data/feature-videos.tsx, src/data/learn-videos.tsx
=> docs: add generate tests videos

dotnet/docs/api/class-apirequest.mdx, dotnet/docs/api/class-browser.mdx, dotnet/docs/api/class-browsertype.mdx, dotnet/docs/ci-intro.mdx, dotnet/docs/codegen-intro.mdx, dotnet/docs/intro.mdx, dotnet/docs/running-tests.mdx, dotnet/docs/test-runners.mdx, dotnet/docs/trace-viewer-intro.mdx, dotnet/docs/writing-tests.mdx, java/docs/api/class-apirequest.mdx, java/docs/api/class-browser.mdx, java/docs/api/class-browsertype.mdx, java/docs/ci-intro.mdx, java/docs/trace-viewer-intro.mdx, nodejs/docs/api/class-androiddevice.mdx, nodejs/docs/api/class-apirequest.mdx, nodejs/docs/api/class-browser.mdx, nodejs/docs/api/class-browsertype.mdx, nodejs/docs/api/class-electron.mdx, nodejs/docs/api/class-testoptions.mdx, nodejs/docs/ci-intro.mdx, nodejs/docs/getting-started-vscode.mdx, python/docs/api/class-apirequest.mdx, python/docs/api/class-browser.mdx, python/docs/api/class-browsertype.mdx, python/docs/ci-intro.mdx, python/docs/trace-viewer-intro.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/d9d760705aa3064bbe8cb12800a861345024e601
=> feat(roll): roll to ToT Playwright (roll/03-05-24)

nodejs/docs/ci-intro.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/d1cdf6826db730507593a0c1045f6495fcae38af
=> feat(roll): roll to ToT Playwright (roll/07-05-24)

src/data/live-streams.tsx
=> community: add playwright live

dotnet/docs/api/class-elementhandle.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-mouse.mdx, dotnet/docs/input.mdx, dotnet/docs/intro.mdx, dotnet/docs/running-tests.mdx, dotnet/docs/writing-tests.mdx, java/docs/api/class-elementhandle.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-mouse.mdx, java/docs/input.mdx, nodejs/docs/api/class-elementhandle.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-mouse.mdx, nodejs/docs/input.mdx, python/docs/api/class-elementhandle.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-mouse.mdx, python/docs/input.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/a5d384c1f63908a32ef00e2d78cc2923aab4fd55
=> feat(roll): roll to ToT Playwright (roll/09-05-24)

dotnet/docs/trace-viewer-intro.mdx, dotnet/docs/trace-viewer.mdx, java/docs/trace-viewer.mdx, nodejs/docs/trace-viewer.mdx, python/docs/trace-viewer.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/00bf7ea815684cc429824e01749cfa7f20be7f48
=> feat(roll): roll to ToT Playwright (roll/10-05-24)

dotnet/docs/api/class-page.mdx, java/docs/api/class-page.mdx, nodejs/docs/api/class-page.mdx, python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/64b4ac1732697044aff4d83b29065a0337848803
=> feat(roll): roll to ToT Playwright (roll/11-05-24)

dotnet/docs/api/class-apirequestcontext.mdx, dotnet/docs/api/class-page.mdx, java/docs/api/class-apirequestcontext.mdx, nodejs/docs/api/class-apirequestcontext.mdx, python/docs/api/class-apirequestcontext.mdx, src/format_csharp.js
Fixes https://github.com/microsoft/playwright.dev/actions/runs/9077516947/job/24942593612#step:6:15
=> feat(roll): roll to ToT Playwright (14-05-24)

python/docs/api/class-browser.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/fda9051c750ba43b9360767443b6bd5c1f40ef45
=> feat(roll): roll to ToT Playwright (roll/15-05-24)

dotnet/docs/ci-intro.mdx, dotnet/docs/ci.mdx, dotnet/docs/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/c9df73bc59799794ab137591828ad1e1e249d0ca
=> feat(roll): roll to ToT Playwright (roll/17-05-24)

dotnet/docs/release-notes.mdx, java/docs/ci-intro.mdx, java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, java/docs/release-notes.mdx, java/docs/test-runners.mdx, python/docs/ci-intro.mdx, python/docs/ci.mdx, python/docs/docker.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/9188ff7917a6b79f47e36fc547b703486e381a80
=> feat(roll): roll to ToT Playwright (roll/18-05-24)

src/data/learn-videos.tsx
=> community: add new video and improve titles

nodejs/sidebarCommunity.js
=> community: add link to learn module

dotnet/docs/api/class-clock.mdx, java/docs/api/class-clock.mdx, nodejs/docs/api/class-clock.mdx, python/docs/api/class-clock.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/8bfd0eb6e4188985c6a5f0ad57306eda10a37266
=> feat(roll): roll to ToT Playwright (roll/01-06-24)

dotnet/docs/api/class-clock.mdx, dotnet/docs/auth.mdx, dotnet/docs/browsers.mdx, dotnet/docs/docker.mdx, dotnet/docs/intro.mdx, java/docs/api/class-clock.mdx, java/docs/auth.mdx, java/docs/browsers.mdx, java/docs/docker.mdx, java/docs/intro.mdx, nodejs/docs/api/class-clock.mdx, nodejs/docs/auth.mdx, nodejs/docs/browsers.mdx, nodejs/docs/docker.mdx, nodejs/docs/intro.mdx, nodejs/docs/test-components.mdx, python/docs/api/class-clock.mdx, python/docs/auth.mdx, python/docs/browsers.mdx, python/docs/docker.mdx, python/docs/intro.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/9e6f0514881c497331d3db62bcba4321f91387eb
=> feat(roll): roll to ToT Playwright (roll/04-06-24)

dotnet/docs/api/class-clock.mdx, dotnet/docs/clock.mdx, java/docs/api/class-clock.mdx, java/docs/clock.mdx, nodejs/docs/api/class-clock.mdx, nodejs/docs/clock.mdx, nodejs/docs/test-parameterize.mdx, python/docs/api/class-clock.mdx, python/docs/clock.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/9a536b0a56a2d083c0a71dfe968bbce509de14bd
=> feat(roll): roll to ToT Playwright (roll/05-06-24)

nodejs/docs/api/class-testproject.mdx, nodejs/docs/testing-library.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/664c4dd44297fc8147d10734b617801a6c464609
=> feat(roll): roll to ToT Playwright (roll/11-06-24)

dotnet/docs/api/class-elementhandle.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/intro.mdx, dotnet/docs/trace-viewer.mdx, java/docs/api/class-elementhandle.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-page.mdx, java/docs/intro.mdx, java/docs/trace-viewer.mdx, nodejs/docs/api/class-elementhandle.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/intro.mdx, nodejs/docs/trace-viewer.mdx, python/docs/api/class-elementhandle.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-page.mdx, python/docs/intro.mdx, python/docs/trace-viewer.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/e8285369f5c080d223ec2eb271d8eab71c580f4f
=> feat(roll): roll to ToT Playwright (roll/13-06-24)

nodejs/docs/test-components.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/6fb214de2378a9d874b46df6ea99d04da5765cba
=> feat(roll): roll to ToT Playwright (roll/17-06-24)

dotnet/docs/input.mdx, nodejs/docs/release-notes.mdx, python/docs/input.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/e1e6c287226e4503e04b1b704ba370b9177a6209
=> feat(roll): roll to ToT Playwright (roll/18-06-24)

dotnet/docs/dialogs.mdx, java/docs/dialogs.mdx, nodejs/docs/dialogs.mdx, nodejs/docs/test-parameterize.mdx, python/docs/dialogs.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/8ba4cff10f2b62f851242e564855eecc6aef116d
=> feat(roll): roll to ToT Playwright (roll/19-06-24)

dotnet/docs/api/class-apirequestcontext.mdx, java/docs/api/class-requestoptions.mdx, nodejs/docs/api/class-apirequestcontext.mdx, python/docs/api/class-apirequestcontext.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/0694474fe1b3de087f633e204ec7c183969394ad
=> feat(roll): roll to ToT Playwright (roll/20-06-24)

nodejs/docs/test-sharding.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/d74ddaebe74c36457428567ca912154f1715dbb2
=> feat(roll): roll to ToT Playwright (roll/22-06-24)

dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/docker.mdx, dotnet/docs/release-notes.mdx, java/docs/api/class-browsercontext.mdx, java/docs/api/class-clock.mdx, java/docs/api/class-page.mdx, java/docs/clock.mdx, java/docs/docker.mdx, java/docs/release-notes.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/ci-intro.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/test-fixtures.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-page.mdx, python/docs/docker.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/122818c62c129455862246a2f6cac57e8fb39321
=> feat(roll): roll to ToT Playwright (roll/25-06-24)

dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/locators.mdx, java/docs/api/class-browsercontext.mdx, java/docs/locators.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/locators.mdx, python/docs/api/class-browsercontext.mdx, python/docs/locators.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/111876d52619ea662d691f68552ba44ef757224b
=> feat(roll): roll to ToT Playwright (roll/27-06-24)

dotnet/docs/api/class-touchscreen.mdx, java/docs/api/class-touchscreen.mdx, java/docs/ci-intro.mdx, java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, java/docs/test-runners.mdx, nodejs/docs/api/class-touchscreen.mdx, python/docs/api/class-touchscreen.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/a3e31fd2c4146e67a63ff4d3dc4f655533adcbde
=> feat(roll): roll to ToT Playwright (roll/28-06-24)

community/ambassadors.mdx
=> community: update ambassador page

dotnet/docs/clock.mdx, java/docs/clock.mdx, nodejs/docs/clock.mdx, nodejs/docs/release-notes.mdx, python/docs/clock.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/4089f4593b3430dda5e4aca28119c50b71bd85e7
=> feat(roll): roll to ToT Playwright (roll/29-06-24)

dotnet/docs/release-notes.mdx, nodejs/docs/ci.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/9dc7e400849e26226a14084524e53900d7a08661
=> feat(roll): roll to ToT Playwright (roll/02-07-24)

dotnet/docs/api/class-clock.mdx, java/docs/api/class-clock.mdx, nodejs/docs/api/class-clock.mdx, nodejs/docs/ci-intro.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/test-annotations.mdx, python/docs/api/class-clock.mdx, src/documentation.js, src/markdown.js
Upstream commit: https://github.com/microsoft/playwright/commit/2b974f2139e0eb15644fb4c8e2d52fa0ba583025
=> feat(roll): roll to ToT Playwright (roll/03-07-24)

nodejs/sidebarCommunity.js
=> community: add samples link

common/links-python.md, src/format_python.js, src/theme/NavbarItem/index.js
=> docs: fix Clock API types in Python

nodejs/versioned_docs/version-stable/api/class-clock.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/4bd2d2502ea7c0b4019afe187060052e92ecf451
=> feat(roll): roll to 1.45 Playwright

dotnet/docs/clock.mdx, java/docs/clock.mdx, nodejs/docs/api/class-clock.mdx, nodejs/docs/browsers.mdx, nodejs/docs/clock.mdx, python/docs/clock.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/b2bda9fce2a7e50f6c51e66321802a574bbb2541
=> feat(roll): roll to ToT Playwright (roll/06-07-24)

nodejs/docs/test-components.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/bc27ca225e69995f238192426df4ccb3f940a50d
=> feat(roll): roll to ToT Playwright (roll/07-07-24)

dotnet/docs/clock.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/00131c1e3fb9c524b2b2b4496ebebcabf46b326e
=> feat(roll): roll to ToT Playwright (roll/09-07-24)

dotnet/docs/api/class-mouse.mdx, dotnet/docs/api/class-touchscreen.mdx, java/docs/api/class-mouse.mdx, java/docs/api/class-touchscreen.mdx, nodejs/docs/api/class-mouse.mdx, nodejs/docs/api/class-touchscreen.mdx, python/docs/api/class-mouse.mdx, python/docs/api/class-touchscreen.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/f374f8db38c8ab1fe9674a1839bd9fdbc5023842
=> feat(roll): roll to ToT Playwright (roll/10-07-24)

dotnet/docs/api/class-browsercontext.mdx, java/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-browsercontext.mdx, python/docs/api/class-browsercontext.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/a5ca9b7d37a9c09b6da62a5d18d929a9c44e054e
=> feat(roll): roll to ToT Playwright (roll/16-07-24)

dotnet/docs/api/class-elementhandle.mdx, dotnet/docs/api/class-filechooser.mdx, dotnet/docs/api/class-frame.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-page.mdx, java/docs/api/class-elementhandle.mdx, java/docs/api/class-filechooser.mdx, java/docs/api/class-frame.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-page.mdx, nodejs/docs/api/class-elementhandle.mdx, nodejs/docs/api/class-filechooser.mdx, nodejs/docs/api/class-frame.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/test-assertions.mdx, python/docs/api/class-elementhandle.mdx, python/docs/api/class-filechooser.mdx, python/docs/api/class-frame.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/056997c41f8d23d1bb1199d48d405bd87a3fa2c8
=> feat(roll): roll to ToT Playwright (roll/18-07-24)

dotnet/docs/api/class-apirequest.mdx, dotnet/docs/api/class-browser.mdx, dotnet/docs/api/class-browsertype.mdx, dotnet/docs/api/class-touchscreen.mdx, dotnet/docs/browsers.mdx, java/docs/api/class-apirequest.mdx, java/docs/api/class-browser.mdx, java/docs/api/class-browsertype.mdx, java/docs/api/class-touchscreen.mdx, java/docs/browsers.mdx, nodejs/docs/api/class-apirequest.mdx, nodejs/docs/api/class-browser.mdx, nodejs/docs/api/class-browsertype.mdx, nodejs/docs/api/class-testoptions.mdx, nodejs/docs/api/class-touchscreen.mdx, nodejs/docs/browsers.mdx, python/docs/api/class-apirequest.mdx, python/docs/api/class-browser.mdx, python/docs/api/class-browsertype.mdx, python/docs/api/class-touchscreen.mdx, python/docs/browsers.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/c5b7ce86dc1de0833f344557f7bb1d2dd9a41227
=> feat(roll): roll to ToT Playwright (roll/24-07-24)

dotnet/docs/api/class-apirequest.mdx, dotnet/docs/api/class-browser.mdx, dotnet/docs/api/class-browsertype.mdx, java/docs/api/class-apirequest.mdx, java/docs/api/class-browser.mdx, java/docs/api/class-browsertype.mdx, nodejs/docs/api/class-apirequest.mdx, nodejs/docs/api/class-browser.mdx, nodejs/docs/api/class-browsertype.mdx, nodejs/docs/api/class-testoptions.mdx, python/docs/api/class-apirequest.mdx, python/docs/api/class-browser.mdx, python/docs/api/class-browsertype.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/bdbe4795f137d08c91da6e4363e13743fb3c385f
=> feat(roll): roll to ToT Playwright (roll/25-07-24)

dotnet/docs/api/class-apirequestcontext.mdx, nodejs/docs/api/class-apirequestcontext.mdx, nodejs/docs/best-practices.mdx, python/docs/api/class-apirequestcontext.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/44ce6096bbe78d8d14bc09ce858ab1a742afc590
=> feat(roll): roll to ToT Playwright (roll/30-07-24)

dotnet/docs/api/class-route.mdx, java/docs/api/class-apirequest.mdx, java/docs/api/class-browser.mdx, java/docs/api/class-browsertype.mdx, java/docs/api/class-route.mdx, nodejs/docs/api/class-route.mdx, python/docs/api/class-apirequest.mdx, python/docs/api/class-browser.mdx, python/docs/api/class-browsertype.mdx, python/docs/api/class-route.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/64fe245297725751a7303ffab775d33ed02fe6f9
=> feat(roll): roll to ToT Playwright (roll/31-07-24)

nodejs/docs/test-components.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/6af2635343133a9f85c28c2ea668272ef4ebf229
=> feat(roll): roll to ToT Playwright (roll/01-08-24)

dotnet/docs/clock.mdx, java/docs/clock.mdx, nodejs/docs/clock.mdx, python/docs/clock.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/d0c840f6390e3693fce199507981716be3df62f9
=> feat(roll): roll to ToT Playwright (roll/03-08-24)

dotnet/docs/api/class-browser.mdx, dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/release-notes.mdx, java/docs/api/class-browser.mdx, java/docs/api/class-browsercontext.mdx, java/docs/api/class-page.mdx, java/docs/release-notes.mdx, nodejs/docs/api/class-browser.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/ci-intro.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/release-notes.mdx, python/docs/api/class-browser.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-page.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/bff97b481092b7a5bbe199f359ad86c26d30e078
=> feat(roll): roll to ToT Playwright (roll/06-08-24)

dotnet/docs/api/class-route.mdx, java/docs/api/class-route.mdx, nodejs/docs/api/class-route.mdx, nodejs/docs/auth.mdx, nodejs/docs/test-cli.mdx, nodejs/docs/test-typescript.mdx, python/docs/api/class-route.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/fd9276f2acfe2cbbb535b060735822a9d1137418
=> feat(roll): roll to ToT Playwright (roll/07-08-24)

src/generator.js, src/markdown.js
See https://github.com/microsoft/playwright/pull/32096#issue-2457595568.
=> chore: remove redundant TOC generation

src/markdown.js
Upstream commit: https://github.com/microsoft/playwright/commit/a30a8805c9e75cc3275cdb7d74f946c4f0458db4
=> feat(roll): roll to ToT Playwright (roll/12-08-24)

dotnet/versioned_docs/version-stable/ci-intro.mdx, dotnet/versioned_docs/version-stable/ci.mdx, dotnet/versioned_docs/version-stable/docker.mdx, dotnet/versioned_docs/version-stable/release-notes.mdx, java/versioned_docs/version-stable/ci-intro.mdx, java/versioned_docs/version-stable/ci.mdx, java/versioned_docs/version-stable/docker.mdx, java/versioned_docs/version-stable/intro.mdx, java/versioned_docs/version-stable/test-runners.mdx, python/versioned_docs/version-stable/ci-intro.mdx, python/versioned_docs/version-stable/ci.mdx, python/versioned_docs/version-stable/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/30684a77e764c49aa76ece4af628ef0aaf1f38e5
=> feat(roll): roll to 1.46 Playwright

dotnet/docs/api/class-browser.mdx, dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-cdpsession.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/ci-intro.mdx, dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, java/docs/ci.mdx, java/docs/docker.mdx, nodejs/docs/api/class-apirequestcontext.mdx, nodejs/docs/api/class-browser.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-cdpsession.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, python/docs/api/class-browser.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-cdpsession.mdx, python/docs/api/class-page.mdx, python/docs/ci-intro.mdx, python/docs/ci.mdx, python/docs/docker.mdx, src/documentation.js
Upstream commit: https://github.com/microsoft/playwright/commit/a28f51a0f31b9499849c481b3658d0985b223c06
=> feat(roll): roll to ToT Playwright (roll/13-08-24)

nodejs/docs/api/class-apirequestcontext.mdx, nodejs/docs/api/class-request.mdx, nodejs/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/856c4509a211e7f049c24155ae5a332781926936
=> feat(roll): roll to ToT Playwright (roll/14-08-24)

src/data/feature-videos.tsx, src/data/release-videos.tsx
replace new trace viewer video
add new release video
=> docs: add videos

dotnet/docs/trace-viewer.mdx, java/docs/trace-viewer.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/trace-viewer-intro.mdx, nodejs/docs/trace-viewer.mdx, python/docs/trace-viewer.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/a1d32d997cb1d09a73dafd0eeb8cacb5da07b930
=> feat(roll): roll to ToT Playwright (roll/15-08-24)

nodejs/docs/ci-intro.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/570e05699e3b70b942e902bd93cfc783b73930a4
=> feat(roll): roll to ToT Playwright (roll/17-08-24)

dotnet/docs/api/class-apirequest.mdx, dotnet/docs/api/class-browser.mdx, dotnet/docs/api/class-browsertype.mdx, java/docs/api/class-apirequest.mdx, java/docs/api/class-browser.mdx, java/docs/api/class-browsertype.mdx, nodejs/docs/api/class-apirequest.mdx, nodejs/docs/api/class-browser.mdx, nodejs/docs/api/class-browsertype.mdx, nodejs/docs/api/class-testoptions.mdx, python/docs/api/class-apirequest.mdx, python/docs/api/class-browser.mdx, python/docs/api/class-browsertype.mdx, src/documentation.js
Upstream commit: https://github.com/microsoft/playwright/commit/010778f6c5543d112a65d18fff34556c30bf5776
=> feat(roll): roll to ToT Playwright (roll/19-08-24)

dotnet/docs/ci-intro.mdx, dotnet/docs/ci.mdx, dotnet/docs/evaluating.mdx, java/docs/ci-intro.mdx, java/docs/ci.mdx, java/docs/evaluating.mdx, nodejs/docs/best-practices.mdx, nodejs/docs/ci-intro.mdx, nodejs/docs/ci.mdx, nodejs/docs/evaluating.mdx, python/docs/ci-intro.mdx, python/docs/ci.mdx, python/docs/evaluating.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/6512bccffdb451228361fd8ddfdb1ae1d499cbf3
=> feat(roll): roll to ToT Playwright (roll/21-08-24)

dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/browsers.mdx, java/docs/api/class-browsercontext.mdx, java/docs/api/class-page.mdx, java/docs/browsers.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/browsers.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-page.mdx, python/docs/browsers.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/666a8f22cf175686651e3cfe7bb77184e2497616
=> feat(roll): roll to ToT Playwright (roll/22-08-24)

nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/test-fixtures.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/3a75f23ea1d116a57f6a9d6bf758cf8d693eb7c3
=> feat(roll): roll to ToT Playwright (roll/23-08-24)

dotnet/docs/api/class-browser.mdx, dotnet/docs/api/class-elementhandle.mdx, dotnet/docs/api/class-frame.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/network.mdx, java/docs/api/class-browser.mdx, java/docs/api/class-elementhandle.mdx, java/docs/api/class-frame.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-page.mdx, java/docs/network.mdx, nodejs/docs/api/class-browser.mdx, nodejs/docs/api/class-elementhandle.mdx, nodejs/docs/api/class-frame.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/network.mdx, python/docs/api/class-browser.mdx, python/docs/api/class-elementhandle.mdx, python/docs/api/class-frame.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-page.mdx, python/docs/network.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/54c487c9396d7368eee78b4f19678427e8045124
=> feat(roll): roll to ToT Playwright (roll/24-08-24)

dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-page.mdx, java/docs/api/class-browsercontext.mdx, java/docs/api/class-page.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/test-fixtures.mdx, nodejs/docs/test-typescript.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/6763d5ab6bd20f1f0fc879537855a26c7644a496
=> feat(roll): roll to ToT Playwright (roll/29-08-24)

dotnet/docs/api/class-apiresponse.mdx, java/docs/api/class-apiresponse.mdx, java/docs/mock.mdx, nodejs/docs/api/class-apiresponse.mdx, python/docs/api/class-apiresponse.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/221b77309c249bc7923ae58fcf285143abd87c7b
=> feat(roll): roll to ToT Playwright (roll/03-09-24)

dotnet/docs/api/class-page.mdx, java/docs/api/class-page.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-request.mdx, python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/60631409d63054d253cd8db9dc76f1ab2f109315
=> feat(roll): roll to ToT Playwright (roll/04-09-24)

dotnet/docs/release-notes.mdx, java/docs/release-notes.mdx, nodejs/docs/release-notes.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/a8139b5d77821bd7dfea2756bd5931bafcee9ba4
=> feat(roll): roll to ToT Playwright (roll/05-09-24)

dotnet/versioned_docs/version-stable/release-notes.mdx, java/versioned_docs/version-stable/release-notes.mdx, nodejs/versioned_docs/version-stable/release-notes.mdx, python/versioned_docs/version-stable/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/2c17b1f0d3df44c66935abfc95706ea8f4a7ce91
=> feat(roll): roll to 1.47 Playwright

nodejs/docs/api/class-testinfo.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/7335fa602c47b84fd58e0bc2ed7dbbf15079b2e1
=> feat(roll): roll to ToT Playwright (roll/11-09-24)

dotnet/docs/browsers.mdx, java/docs/browsers.mdx, nodejs/docs/browsers.mdx, python/docs/browsers.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/dc5bbbf295d790922b0b6e6c2a5eb4ab559da059
=> feat(roll): roll to ToT Playwright (roll/12-09-24)

package-lock.json
=> chore: run 'npm audit fix'

dotnet/docs/ci.mdx, java/docs/ci.mdx, nodejs/docs/ci.mdx, python/docs/ci.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/268357238ac27e03ea5309ab23e70ba9261e68f1
=> feat(roll): roll to ToT Playwright (roll/next-16-09-24)

nodejs/sidebars.js
Relates to https://github.com/microsoft/playwright/pull/32687
=> chore: move Location to Test Runner category (sidebar)

dotnet/docs/api/class-frame.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/network.mdx, java/docs/api/class-frame.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-page.mdx, java/docs/network.mdx, nodejs/docs/api/class-frame.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/ci.mdx, nodejs/docs/network.mdx, nodejs/docs/test-sharding.mdx, python/docs/api/class-frame.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-page.mdx, python/docs/network.mdx, src/api_parser.js
Upstream commit: https://github.com/microsoft/playwright/commit/b6783bb18b086d80504d68a9c24fd7a1e0e65172
=> feat(roll): roll to ToT Playwright (roll/next-25-09-24)

dotnet/sidebars.js, java/sidebars.js, nodejs/sidebars.js, python/sidebars.js
=> chore: add WebSocketRoute to sidebar

dotnet/docs/api/class-browser.mdx, dotnet/docs/api/class-browsertype.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/emulation.mdx, java/docs/api/class-browser.mdx, java/docs/api/class-browsertype.mdx, java/docs/api/class-page.mdx, java/docs/emulation.mdx, nodejs/docs/api/class-androiddevice.mdx, nodejs/docs/api/class-browser.mdx, nodejs/docs/api/class-browsertype.mdx, nodejs/docs/api/class-electron.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-testoptions.mdx, nodejs/docs/ci.mdx, nodejs/docs/emulation.mdx, nodejs/docs/test-reporters.mdx, nodejs/docs/test-use-options.mdx, python/docs/api/class-browser.mdx, python/docs/api/class-browsertype.mdx, python/docs/api/class-page.mdx, python/docs/emulation.mdx, src/markdown.js
Upstream commit: https://github.com/microsoft/playwright/commit/ddeabdf770146d83bac72f15a4e956aa9aa24af3
=> feat(roll): roll to ToT Playwright (roll/next-05-10-24)

nodejs/docs/best-practices.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/e6afb650befcbe19ac051e1f151ea9deb4e943f2
=> feat(roll): roll to ToT Playwright (roll/next-07-10-24)

dotnet/docs/api/class-clock.mdx, dotnet/docs/api/class-route.mdx, java/docs/api/class-clock.mdx, java/docs/api/class-route.mdx, nodejs/docs/api/class-clock.mdx, nodejs/docs/api/class-route.mdx, python/docs/api/class-clock.mdx, python/docs/api/class-route.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/0f2cbdedacec25bd6894e22055f63c49c43ea208
=> feat(roll): roll to ToT Playwright (roll/next-08-10-24)

nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/test-sharding.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/6210fef6814caf42b36945e8f214f37270ad84a2
=> feat(roll): roll to ToT Playwright (roll/next-09-10-24)

java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, java/docs/test-runners.mdx, src/generate.js
Fixes https://github.com/microsoft/playwright/issues/33028
This regressed in https://github.com/microsoft/playwright.dev/pull/1535.
=> fix: java version fetching logic

java/versioned_docs/version-stable/ci.mdx, java/versioned_docs/version-stable/docker.mdx, java/versioned_docs/version-stable/intro.mdx, java/versioned_docs/version-stable/test-runners.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/daff1a9025d90bbfab2fc085caa825939f5608bd
=> feat(roll): roll to 1.48 Playwright

nodejs/docs/api/class-test.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/test-configuration.mdx, nodejs/docs/test-timeouts.mdx, nodejs/docs/test-typescript.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/25dd9b5cd49470215c71d77ef46f81a66960ec3d
=> feat(roll): roll to ToT Playwright (roll/next-10-10-24)

dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-locatorassertions.mdx, dotnet/docs/api/class-websocketroute.mdx, dotnet/docs/locators.mdx, dotnet/docs/mock.mdx, dotnet/docs/network.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-locatorassertions.mdx, java/docs/api/class-websocketroute.mdx, java/docs/locators.mdx, java/docs/mock.mdx, java/docs/network.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-websocketroute.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/locators.mdx, nodejs/docs/mock.mdx, nodejs/docs/network.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-locatorassertions.mdx, python/docs/api/class-websocketroute.mdx, python/docs/locators.mdx, python/docs/mock.mdx, python/docs/network.mdx, src/format_csharp.js
=> chore: fix ToT roll & roll to 16th of October

dotnet/docs/locators.mdx, nodejs/docs/api/class-test.mdx, nodejs/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/7af9e93304797481e8f8725581b0ead7530f2a56
=> feat(roll): roll to ToT Playwright (roll/next-17-10-24)

java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, java/docs/test-runners.mdx, nodejs/docs/api/class-testconfig.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/02f8acce028080e3b8dfb79ebe2f51876079a294
=> feat(roll): roll to ToT Playwright (roll/next-18-10-24)

common/links-csharp.md, common/links-java.md, common/links-js.md, common/links-python.md
https://github.com/microsoft/playwright/issues/33205
=> chore: update Dockerfile links to noble

nodejs/docs/getting-started-vscode.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/6bfdad068c1c171a551540df0b7f32a16b10b26c
=> feat(roll): roll to ToT Playwright (roll/next-23-10-24)

nodejs/docs/api/class-testoptions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/9707e978671bb77b44537086839610b730eca544
=> feat(roll): roll to ToT Playwright (roll/next-25-10-24)

nodejs/docs/api/class-testerror.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/test-components.mdx, python/docs/test-runners.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/4b7c8d8a2097a5843efacf970e27edad433b67f7
=> feat(roll): roll to ToT Playwright (roll/next-26-10-24)

dotnet/docs/api/class-keyboard.mdx, java/docs/api/class-keyboard.mdx, nodejs/docs/api/class-keyboard.mdx, nodejs/docs/api/class-testerror.mdx, nodejs/docs/api/class-testinfoerror.mdx, python/docs/api/class-keyboard.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/0221f15f4ff84f18d9d95f0a9ce71b39cdc9e1a6
=> feat(roll): roll to ToT Playwright (roll/next-29-10-24)

nodejs/docs/best-practices.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/6f5c7b43588d2e8b95d716a21c6d2f4682042c1b
=> feat(roll): roll to ToT Playwright (roll/next-30-10-24)

python/docs/browsers.mdx, python/docs/test-runners.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/abcd1ff201f5f7b99e6c4abba26ffaf5ae9d2be5
=> feat(roll): roll to ToT Playwright (roll/next-02-11-24)

dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-locatorassertions.mdx, dotnet/docs/aria-snapshot.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-locatorassertions.mdx, java/docs/aria-snapshot.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/aria-snapshot.mdx, nodejs/docs/test-assertions.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-locatorassertions.mdx, python/docs/aria-snapshot.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/ec8161cb0a8be649c5fb6498343c98ab03859863
=> feat(roll): roll to ToT Playwright (roll/next-05-11-24)

dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-locatorassertions.mdx, dotnet/docs/aria-snapshots.mdx, dotnet/sidebars.js, java/docs/api/class-locator.mdx, java/docs/api/class-locatorassertions.mdx, java/docs/aria-snapshots.mdx, java/sidebars.js, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/aria-snapshots.mdx, nodejs/sidebars.js, python/docs/api/class-locator.mdx, python/docs/api/class-locatorassertions.mdx, python/docs/aria-snapshots.mdx, python/sidebars.js
Upstream commit: https://github.com/microsoft/playwright/commit/d4ad520a9bf0fea78b610c065af0b0c896229666
=> feat(roll): roll to ToT Playwright (roll/next-06-11-24)

dotnet/docs/api/class-tracing.mdx, java/docs/api/class-tracing.mdx, nodejs/docs/api/class-tracing.mdx, python/docs/api/class-tracing.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/7073f80879a9c194abe969fd7b5c145c4b15caaa
=> feat(roll): roll to ToT Playwright (roll/next-08-11-24)

dotnet/docs/browsers.mdx, java/docs/browsers.mdx, nodejs/docs/browsers.mdx, nodejs/docs/release-notes.mdx, nodejs/docs/test-snapshots.mdx, python/docs/browsers.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/503f74da9089cff4425840a5b297ed5a62a8c15b
=> feat(roll): roll to ToT Playwright (roll/next-09-11-24)

nodejs/docs/test-components.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/1b65f26f0287c0352e76673bc5f85bc36c934b55
=> feat(roll): roll to ToT Playwright (roll/next-12-11-24)

dotnet/docs/browsers.mdx, java/docs/browsers.mdx, nodejs/docs/api/class-test.mdx, nodejs/docs/best-practices.mdx, nodejs/docs/browsers.mdx, nodejs/docs/chrome-extensions.mdx, nodejs/docs/release-notes.mdx, python/docs/browsers.mdx, python/docs/chrome-extensions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/9f59dbdc57ea4903d7952412a2670900a5039e58
=> feat(roll): roll to ToT Playwright (roll/next-14-11-24)

dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-locatorassertions.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-locatorassertions.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-locatorassertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/eaf3536014b22bbf6ff3c52ef3820e0209341e0e
=> feat(roll): roll to ToT Playwright (roll/next-15-11-24)

dotnet/docs/api/class-locatorassertions.mdx, dotnet/docs/ci-intro.mdx, dotnet/docs/clock.mdx, dotnet/docs/release-notes.mdx, java/docs/ci-intro.mdx, nodejs/docs/intro.mdx, nodejs/docs/running-tests.mdx, nodejs/docs/trace-viewer-intro.mdx, python/docs/ci-intro.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/a98021499fc11c5fb81fbdbb4d48b9ae44773600
=> feat(roll): roll to ToT Playwright (roll/next-16-11-24)

dotnet/docs/api/class-locatorassertions.mdx, java/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, python/docs/api/class-locatorassertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/ecf6f27159de43cc12964e190e5241b4382abff5
=> feat(roll): roll to ToT Playwright (roll/next-19-11-24)

dotnet/docs/api/class-browsertype.mdx, dotnet/docs/browsers.mdx, java/docs/api/class-browsertype.mdx, java/docs/browsers.mdx, nodejs/docs/api/class-browsertype.mdx, nodejs/docs/api/class-testoptions.mdx, nodejs/docs/browsers.mdx, nodejs/docs/test-fixtures.mdx, python/docs/api/class-browsertype.mdx, python/docs/browsers.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/1afb56ee1b63ffbb972a1773432979b865878072
=> feat(roll): roll to ToT Playwright (roll/next-20-11-24)

dotnet/versioned_docs/version-stable/api/class-browsertype.mdx, dotnet/versioned_docs/version-stable/browsers.mdx, java/versioned_docs/version-stable/api/class-browsertype.mdx, java/versioned_docs/version-stable/browsers.mdx, nodejs/versioned_docs/version-stable/api/class-browsertype.mdx, nodejs/versioned_docs/version-stable/api/class-testoptions.mdx, nodejs/versioned_docs/version-stable/browsers.mdx, python/versioned_docs/version-stable/api/class-browsertype.mdx, python/versioned_docs/version-stable/browsers.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/4b0eca4d2251acc5673b9bf57d17e625a44bd4f5
=> feat(roll): roll to 1.49 Playwright

dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/aria-snapshots.mdx, java/docs/api/class-browsercontext.mdx, java/docs/aria-snapshots.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/aria-snapshots.mdx, nodejs/docs/release-notes.mdx, python/docs/api/class-browsercontext.mdx, python/docs/aria-snapshots.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/fc19e6e7b4224bb9acecb89cbd73a8646a63eccf
=> feat(roll): roll to ToT Playwright (roll/next-21-11-24)

dotnet/docs/api/class-tracing.mdx, dotnet/docs/aria-snapshots.mdx, dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, dotnet/docs/release-notes.mdx, java/docs/api/class-tracing.mdx, java/docs/aria-snapshots.mdx, java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, java/docs/release-notes.mdx, java/docs/test-runners.mdx, nodejs/docs/aria-snapshots.mdx, python/docs/api/class-locatorassertions.mdx, python/docs/aria-snapshots.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/e0f0996bbdeb11e238ac2c2b198dc1a3ecd07a49
=> feat(roll): roll to ToT Playwright (roll/next-22-11-24)

dotnet/docs/actionability.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/intro.mdx, dotnet/docs/languages.mdx, dotnet/docs/library.mdx, dotnet/docs/test-runners.mdx, java/docs/actionability.mdx, java/docs/api/class-locator.mdx, java/docs/languages.mdx, nodejs/docs/actionability.mdx, nodejs/docs/api/class-fullconfig.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/languages.mdx, nodejs/docs/test-cli.mdx, python/docs/actionability.mdx, python/docs/api/class-locator.mdx, python/docs/ci.mdx, python/docs/docker.mdx, python/docs/languages.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/0d9bcd45d57385bddc3ccbeff3ffb2d8314f6be3
=> feat(roll): roll to ToT Playwright (roll/next-24-11-24)

dotnet/docs/intro.mdx, dotnet/docs/languages.mdx, dotnet/docs/library.mdx, dotnet/docs/running-tests.mdx, dotnet/docs/test-assertions.mdx, dotnet/docs/test-runners.mdx, dotnet/docs/trace-viewer-intro.mdx, dotnet/docs/trace-viewer.mdx, dotnet/docs/writing-tests.mdx, java/docs/languages.mdx, nodejs/docs/chrome-extensions.mdx, nodejs/docs/languages.mdx, python/docs/chrome-extensions.mdx, python/docs/languages.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/39285c4667a735f40cf95345407fc9f4ea8622fd
=> feat(roll): roll to ToT Playwright (roll/next-25-11-24)

python/docs/test-runners.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/f3ae940684dd26de1d4674d66dd98b8722b08d50
=> feat(roll): roll to ToT Playwright (roll/next-27-11-24)

dotnet/docs/ci.mdx, dotnet/docs/codegen.mdx, java/docs/ci.mdx, java/docs/codegen.mdx, nodejs/docs/ci.mdx, nodejs/docs/codegen.mdx, python/docs/ci.mdx, python/docs/codegen.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/4e33ade28754a8cdc9fbc0302d3dc3a0f3eb05c0
=> feat(roll): roll to ToT Playwright (roll/next-30-11-24)

dotnet/docs/network.mdx, java/docs/network.mdx, nodejs/docs/network.mdx, python/docs/network.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/9b5f7f77b22858a1db5cbc0efe5c9dc55e7aeb75
=> feat(roll): roll to ToT Playwright (roll/next-03-12-24)

dotnet/docs/api/class-page.mdx, java/docs/api/class-page.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-testoptions.mdx, python/docs/api/class-page.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/733f9a2926a86374e71823150484c7c2c34d162f
=> feat(roll): roll to ToT Playwright (roll/next-06-12-24)

nodejs/docs/ci.mdx, nodejs/docs/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/27060a0f652455b9fc60b2c28af45f4583bc1fcb
=> feat(roll): roll to ToT Playwright (roll/next-10-12-24)

dotnet/docs/clock.mdx, java/docs/clock.mdx, nodejs/docs/clock.mdx, nodejs/docs/test-sharding.mdx, python/docs/clock.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/a14d9750b314c26d72daa9f33598ad9d66d3e61c
=> feat(roll): roll to ToT Playwright (roll/next-11-12-24)

dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/browsers.mdx, java/docs/api/class-browsercontext.mdx, java/docs/api/class-page.mdx, java/docs/browsers.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/browsers.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-page.mdx, python/docs/browsers.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/e3629dc1df67546c10fe0f10d4b8e08ecc3b3d4d
=> feat(roll): roll to ToT Playwright (roll/next-12-12-24)

dotnet/docs/api/class-browser.mdx, dotnet/docs/trace-viewer.mdx, java/docs/api/class-browser.mdx, java/docs/trace-viewer.mdx, nodejs/docs/api/class-browser.mdx, nodejs/docs/test-ui-mode.mdx, nodejs/docs/trace-viewer-intro.mdx, nodejs/docs/trace-viewer.mdx, python/docs/api/class-browser.mdx, python/docs/trace-viewer.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/7ce1a540bcd979096dc4ac3851c675407ede6f5a
=> feat(roll): roll to ToT Playwright (roll/next-17-12-24)

nodejs/docs/api/class-test.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/c9ae644e5f12b1947846282c6a4887233415044c
=> feat(roll): roll to ToT Playwright (roll/next-18-12-24)

nodejs/docs/test-global-setup-teardown.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/a239ab3048baae0a0dcc33b1024ce35002087207
=> feat(roll): roll to ToT Playwright (roll/next-19-12-24)

dotnet/docs/api/class-browsertype.mdx, dotnet/docs/api/class-locator.mdx, dotnet/docs/browsers.mdx, java/docs/api/class-browsertype.mdx, java/docs/api/class-locator.mdx, java/docs/browsers.mdx, nodejs/docs/api/class-browsertype.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-testoptions.mdx, nodejs/docs/browsers.mdx, nodejs/docs/chrome-extensions.mdx, python/docs/api/class-browsertype.mdx, python/docs/api/class-locator.mdx, python/docs/browsers.mdx, python/docs/chrome-extensions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/03cf7429a4b69627a7114ff3fc984a553d05139e
=> feat(roll): roll to ToT Playwright (roll/next-21-12-24)

nodejs/docs/test-webserver.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/1c8e6f0921b1cc517afb5f8549609f356e81cf85
=> feat(roll): roll to ToT Playwright (roll/next-22-12-24)

dotnet/docs/api/class-locatorassertions.mdx, java/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-locatorassertions.mdx, python/docs/api/class-locatorassertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/4819747c85faa8cad0f33d770e1e63f6fb894d49
=> feat(roll): roll to ToT Playwright (roll/next-27-12-24)

nodejs/docs/test-fixtures.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/acdd666d9530277f3a2561f5591b9a8cf1780ce8
=> feat(roll): roll to ToT Playwright (roll/next-02-01-25)

dotnet/docs/input.mdx, dotnet/docs/touch-events.mdx, java/docs/input.mdx, java/docs/touch-events.mdx, nodejs/docs/chrome-extensions.mdx, nodejs/docs/input.mdx, nodejs/docs/touch-events.mdx, python/docs/chrome-extensions.mdx, python/docs/input.mdx, python/docs/touch-events.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/9f32c858e084fdfe0c1f0b6222767452dd2cacfd
=> feat(roll): roll to ToT Playwright (roll/next-09-01-25)

dotnet/docs/api/class-locatorassertions.mdx, java/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-androiddevice.mdx, nodejs/docs/api/class-locatorassertions.mdx, python/docs/api/class-locatorassertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/b32d5461590f355801f6db2916a05b68b8ac103c
=> feat(roll): roll to ToT Playwright (roll/next-10-01-25)

dotnet/docs/api/class-locator.mdx, dotnet/docs/api/class-locatorassertions.mdx, dotnet/docs/aria-snapshots.mdx, dotnet/docs/release-notes.mdx, java/docs/api/class-locator.mdx, java/docs/api/class-locatorassertions.mdx, java/docs/aria-snapshots.mdx, java/docs/release-notes.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-test.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/aria-snapshots.mdx, nodejs/docs/release-notes.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-locatorassertions.mdx, python/docs/aria-snapshots.mdx, python/docs/release-notes.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/be6caed8df159ad15c6a9ed0eb23f6c1b9e65d79
=> feat(roll): roll to ToT Playwright (roll/next-16-01-25)

dotnet/docs/api/class-locatorassertions.mdx, java/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-locatorassertions.mdx, python/docs/api/class-locatorassertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/40b92eaf2a0d2dbb1ea40fa0719608a92481051b
=> feat(roll): roll to ToT Playwright (roll/next-17-01-25)

.github/workflows/roll-stable.yml
=> devops: do not roll stable on timer

dotnet/docs/api/class-locator.mdx, java/docs/api/class-locator.mdx, nodejs/docs/api/class-locator.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/test-cli.mdx, python/docs/api/class-locator.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/f11768436ae0888fa2cc0803eb7a79e0dedb7d5b
=> feat(roll): roll to ToT Playwright (roll/next-24-01-25)

nodejs/versioned_docs/version-stable/api/class-locatorassertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/b7b0f9571ded164ccc37fd55a4536c671dd3c814
=> feat(roll): roll to 1.50 Playwright

dotnet/docs/api/class-pageassertions.mdx, java/docs/api/class-pageassertions.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-pageassertions.mdx, python/docs/api/class-pageassertions.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/245f4b5b8630d054fb3472097f2777df761e6089
=> feat(roll): roll to ToT Playwright (roll/next-25-01-25)

src/format_python.js
Fixes https://github.com/microsoft/playwright/issues/34184
=> fix(python): render Serializable as dict

dotnet/docs/api/class-browser.mdx, dotnet/docs/api/class-browsertype.mdx, dotnet/docs/api/class-page.mdx, java/docs/api/class-browser.mdx, java/docs/api/class-browsertype.mdx, java/docs/api/class-page.mdx, java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, java/docs/test-runners.mdx, nodejs/docs/api/class-androiddevice.mdx, nodejs/docs/api/class-browser.mdx, nodejs/docs/api/class-browsertype.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/ci.mdx, python/docs/api/class-apirequestcontext.mdx, python/docs/api/class-apiresponse.mdx, python/docs/api/class-browser.mdx, python/docs/api/class-browsertype.mdx, python/docs/api/class-elementhandle.mdx, python/docs/api/class-frame.mdx, python/docs/api/class-jshandle.mdx, python/docs/api/class-locator.mdx, python/docs/api/class-page.mdx, python/docs/api/class-request.mdx, python/docs/api/class-response.mdx, python/docs/api/class-route.mdx, python/docs/api/class-worker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/fb3e8ed114f19300624fc9ecbd94a4fa8d950f05
=> feat(roll): roll to ToT Playwright (roll/next-05-02-25)

dotnet/docs/api/class-apirequest.mdx, dotnet/docs/api/class-browser.mdx, dotnet/docs/api/class-browsertype.mdx, java/docs/api/class-apirequest.mdx, java/docs/api/class-browser.mdx, java/docs/api/class-browsertype.mdx, nodejs/docs/api/class-androiddevice.mdx, nodejs/docs/api/class-apirequest.mdx, nodejs/docs/api/class-browser.mdx, nodejs/docs/api/class-browsertype.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/aria-snapshots.mdx, python/docs/api/class-apirequest.mdx, python/docs/api/class-browser.mdx, python/docs/api/class-browsertype.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/58db3f7e3f897327ea031c6ad1d8483bb88a09b7
=> feat(roll): roll to ToT Playwright (roll/next-27-02-25)

dotnet/docs/api/class-browsercontext.mdx, dotnet/docs/api/class-page.mdx, dotnet/docs/network.mdx, java/docs/api/class-browsercontext.mdx, java/docs/api/class-page.mdx, java/docs/network.mdx, nodejs/docs/api/class-browsercontext.mdx, nodejs/docs/api/class-page.mdx, nodejs/docs/api/class-test.mdx, nodejs/docs/api/class-testconfig.mdx, nodejs/docs/api/class-testoptions.mdx, nodejs/docs/api/class-teststepinfo.mdx, nodejs/docs/network.mdx, nodejs/docs/release-notes.mdx, python/docs/api/class-browsercontext.mdx, python/docs/api/class-page.mdx, python/docs/network.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/cd437c972d570aef2c32d2ab19b40021eea5706c
=> feat(roll): roll to ToT Playwright (roll/next-01-03-25)

dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, java/docs/ci.mdx, java/docs/docker.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, nodejs/docs/release-notes.mdx, python/docs/ci.mdx, python/docs/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/1b02458988dc8f02b9519ba51c8e96b0b7316e4a
=> feat(roll): roll to ToT Playwright (roll/next-04-03-25)

nodejs/docs/ci.mdx, nodejs/docs/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/7fe17776e855821246f8b8df3b652f1f9bf28ea4
=> feat(roll): roll to ToT Playwright (roll/next-07-03-25)

dotnet/docs/api/class-apirequest.mdx, dotnet/docs/api/class-browsertype.mdx, dotnet/docs/ci-intro.mdx, dotnet/docs/ci.mdx, dotnet/docs/docker.mdx, java/docs/api/class-apirequest.mdx, java/docs/api/class-browsertype.mdx, java/docs/ci-intro.mdx, java/docs/ci.mdx, java/docs/docker.mdx, java/docs/intro.mdx, java/docs/test-runners.mdx, nodejs/docs/api/class-apirequest.mdx, nodejs/docs/api/class-browsertype.mdx, nodejs/docs/ci-intro.mdx, nodejs/docs/ci.mdx, nodejs/docs/docker.mdx, python/docs/api/class-apirequest.mdx, python/docs/api/class-browsertype.mdx, python/docs/ci-intro.mdx, python/docs/ci.mdx, python/docs/docker.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/66b3efa826c4d524c08b7d70635ad4bf12900c58
=> feat(roll): roll to ToT Playwright (roll/next-18-03-25)

dotnet/docs/trace-viewer.mdx, java/docs/trace-viewer.mdx, nodejs/docs/test-global-setup-teardown.mdx, nodejs/docs/test-projects.mdx, nodejs/docs/trace-viewer.mdx, python/docs/trace-viewer.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/eafcbd343788f6c5626654bcad1887c4f6612255
=> feat(roll): roll to ToT Playwright (roll/next-19-03-25)

dotnet/docs/api/class-locatorassertions.mdx, dotnet/docs/api/class-route.mdx, java/docs/api/class-locatorassertions.mdx, java/docs/api/class-route.mdx, nodejs/docs/api/class-locatorassertions.mdx, nodejs/docs/api/class-route.mdx, nodejs/docs/mock-browser.mdx, python/docs/api/class-locatorassertions.mdx, python/docs/api/class-route.mdx
Upstream commit: https://github.com/microsoft/playwright/commit/53ed2f601b877ea79b9244f53b6c0410a9db55e4
=> feat(roll): roll to ToT Playwright (roll/next-21-03-25)

.github/workflows/roll-next.yml
=> chore(workflow): update cron schedule to run on weekdays only

src/components/ProfileCard/index.tsx, src/components/ProfileCard/styles.module.css
Closes https://github.com/microsoft/playwright.dev/issues/1760, https://github.com/microsoft/playwright.dev/issues/1761
=> fix(a11y): ambassadors page

src/generator.js
=> chore: render class deprecation warning
